Re-Fungible Token
ethereum/EIPs pull request #1633
Opened 2018-12-02 14:35 UTC by okwme

The intention of this proposal, the Re-Fungible Token Standard, is to extend the ERC-20 Token Standard and utilize ERC-165 Standard Interface Detection in order to represent the shared ownership of an ERC-721 Non-Fungible Token. The ERC-20 Token Standard was modified as little as possible in order to allow this new class of token to operate in all of the ways and locations which are familiar to assets that follow the original ERC-20 specification. While there are many possible variations of this specification that would enable many different capabilities and scenarios for shared ownership, this proposal is focused on the minimal commonalities to enable as much flexibility as possible for various further extensions. This proposal makes it possible to verify, from the contract level or from an external query, whether a fungible token represents a form of shared ownership of a non-fungible token. The inclusion of ERC-165 makes it possible to verify, from the contract level or from an external query, whether a non-fungible token is owned by ERC-20 token representing shared ownership.

2019-05-09 23:31 UTC, axic commented
Without fully reading the proposal, this seems to be similar to #1513. Would it be possible to merge efforts?

2019-05-10 00:12 UTC, okwme commented
hi @axic 
i tried to get the conversation started with @tlxsam here: https://github.com/ethereum/EIPs/issues/1634#issuecomment-452044524 but never got a response.

2019-05-10 14:49 UTC, tlxsam commented
hi @okwme the proposals are under review, will discuss further soon.

2020-09-15 20:31 UTC, tlxsam commented
We are upgrading the implementation based on the latest contract definitions and will resubmit for review.

2020-09-30 09:31 UTC, lightclient commented
@tlxsam do you plan to use this PR or close?

2020-10-05 22:09 UTC, JamesDoe commented
@okwme, thanks so much for sending me a link to this Git! 
As mentioned in my previous post, you guys have an amazing proposal on your hands! 

It aligns with my current necessity to find an applicable standard for NFTs that can have several, non-owner participants associated with it. In my use case, I'm creating a 'living' securities strategy, whereby the author sets the parameters of the strategy (exit points, risk thresholds - such as 'theta' and 'IV' limits, minimum input thresholds for ERC20 participation, etc.) and then unleashes the NFT into the wild.

Once the NFT hits the main net, its internal parameters become immutable. The trick is that the NFT can only 'survive' by 
 being 'fed' a particular ERC20 from other addresses... i.e. 'participants', who basically act as investors. 

The participants are rewarded if/when the decentralized securities play exits with a profit, and the author in return, is rewarded a nominal commission that is applied as value against the NFT token. The author is also mandated to hold a set stake in the NFT. 

Lastly, while participants can not exit prior to the pre-programmed thresholds/conditions, they are free to 'sell' or 'trade' their vestments in the NFT.

So, there a lot of moving pieces that benefit from less stricture on the ERC-standard side of things.
I'm looking forward to presenting my build-out to you all, and getting feedback on how applicable it may or may not be to the standard you guys are creating. Optimally, I intend to stay as closely aligned with your initial proposal's ideas as possible. 

The beauty in your concept, is the careful attention paid to a separation of concerns. 

In my use case, that separation will be vital — as the author needs some maneuverability when dictating the behavior of the NFT, and I have to carefully weigh that customizability against security concerns (preventing rogue actions that would break securities laws in my country).

2020-12-05 10:27 UTC, okwme commented
glad to hear it @JamesDoe 
I'll change the status to last call if there are no other changes requested

2020-12-05 10:27 UTC, okwme commented on EIPS/eip-1633.md
> +status: Draft
```suggestion
status: Last Call
```

2020-12-06 10:01 UTC, MicahZoltu requested changes
Minimum changes to merge as Draft:
Change status to Draft, remove template comments, add Security Considerations section.

The rest of the feedback should be considered prior to submitting for Review status.

2021-01-06 15:49 UTC, okwme commented on EIPS/eip-1633.md
> +status: Last Call
```suggestion
status: Draft
```

2021-01-06 15:50 UTC, okwme commented on EIPS/eip-1633.md
> +status: Last Call
changed back to "Draft", thanks for the outline of the process!

2021-01-06 19:54 UTC, lightclient requested changes

2021-01-06 19:54 UTC, lightclient commented on EIPS/eip-1633.md
> +#### Inital Contact with the Re-Fungible Token
```suggestion
#### Initial Contact with the Re-Fungible Token
```

2021-01-06 19:54 UTC, lightclient commented on EIPS/eip-1633.md
> +#### Inital Contact with the Non-Fungible Token
```suggestion
#### Initial Contact with the Non-Fungible Token
```

2021-01-06 19:54 UTC, lightclient commented on EIPS/eip-1633.md
> +  * Not ERC-721 backwards compatibile
```suggestion
  * Not ERC-721 backwards compatible
```

2021-01-06 20:08 UTC, DGKSK8LIFE commented on EIPS/eip-1633.md
> +  * Not ERC-721 backwards compatibile
Good catch! Change request LGTM

2021-03-08 15:40 UTC, lightclient requested changes

2021-03-08 15:40 UTC, lightclient commented on EIPS/eip-1633.md
> +author: Billy Rennekamp (@okwme), Dan Long (dan@artblx.com), Kiryl Yermakou (kiryl@artblx.com), Nate van der Ende (nate@artblx.com)
```suggestion
author: Billy Rennekamp (@okwme), Dan Long <dan@artblx.com>, Kiryl Yermakou <kiryl@artblx.com>, Nate van der Ende <nate@artblx.com>
```

2021-03-09 14:28 UTC, van-der-ende requested changes

2021-03-09 14:28 UTC, van-der-ende commented on EIPS/eip-1633.md
> +author: Billy Rennekamp (@okwme), Dan Long <dan@artblx.com>, Kiryl Yermakou <kiryl@artblx.com>, Nate van der Ende <nate@artblx.com>
```suggestion
author: Billy Rennekamp (@okwme), Dan Long <dan@artblx.com>, Kiryl Yermakou <kiryl@artblx.com>, Nate van der Ende (@van-der-ende)
```

2021-03-11 04:54 UTC, merged