Automatic signatures
ethereum/EIPs pull request #2224
Opened 2019-08-01 17:47 UTC by wighawag

## Simple Summary
It is common for applications with a backend component to need to authentify wallet owner with their private key. Wallet currently provide application a way to fetch the address of the users but application can't be sure they are the one owning the private key.
with `wallet_autoSign` application can request to sign specific payloads to ensure the user has indeed access to the privateKey behind the ethereum address. This can also be used to communicate authentically with a backend without session tracking.

## Abstract
Application can request the wallet to sign specific payload on behalf of the users without prior's user confirmation.

## Motivation
Currently, applications with a backend component that requires to authenticate ethereum address, requests users to sign a message. In some case, these messages (for a better appearance maybe) are static, vulnerable to replay attack. 
Such user interaction is less than ideal and technically unecessary. If we can restrict the type of payload such automatic signature can sign, the request can go through, behind the scene, without involving the user. There is no risk for the user as the payload is prepended with a unique string.

## Specification
The JSON RPC method `wallet_autoSign`  require 2 parameters :

### Required Parameters
- account (string): the ethereum address expected to sign the payload
- payload (string): any string the application want to authenticate

The wallet needs to prepend "Automatic Signature" to the payload before signing to prevent the application from requesting signature for other purpose. 

### Example
A JSON-RPC request to authenticate via a specific challenge :
```json
{
  "id":1,
  "jsonrpc": "2.0",
  "method": "wallet_autoSign",
  "params": ["0x50545c559a4110c2a1216976b3667b3208a71c0e", ": any string"]
}
```

This would actually sign the string "Automatic Signature: any string" with "0x50545c559a4110c2a1216976b3667b3208a71c0e"'s private key.

This assume #1102's ```eth_requestAccounts``` was approved by the user first to preserve privacy

## Open questions

- Is it secure to let applications sign at will (even if the message is prepended by  "Automatic Signature") ?
- Or should we do such signing using a non-hardened derived key ?
- If so could #1102's eth_requestAccounts be used to provide the parameter to derive from (could be one based on the origin of the document) ?
- Should we rate-limit the requests ?

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

2019-09-04 17:38 UTC, tomhschmidt commented
Hey! Just discovered this. Are you still working on this EIP @wighawag? I think it's a great idea and very useful for some of the things we're working on at 0x.

Seems like the trick here is in figuring out a templating system so that a user can reasonably allow a dApp to sign any set of strings in the template. "Any strings" seems way too dangerous given the prevalence of off-chain message signing dApps (dY/dX, Nuo, 0x, etc.). Maybe using a RegEx or an EIP-712 envelope?

2019-09-05 10:51 UTC, wighawag commented
Hey @tomhschmidt
 
I am still interested to bring that proposal forward, few others are too, as you can see in the ethereum magicians forum. I need to fix the spelling mistake to get this merged :)

For the template, the current proposal proposes the prefix `Automatic Signature` 
I like its simplicity but if you have other concrete suggestions, I am all ears.

we could be a specific non-hardened keys too assuming we can have an easy way to recover the account from which it was derived from.

2020-09-08 19:54 UTC, wighawag commented
This is ready for review

2020-09-08 23:36 UTC, axic commented on EIPS/eip-2224.md
> +category: ERC
```suggestion
category: Interface
```

2020-09-08 23:37 UTC, axic commented on EIPS/eip-2224.md
> +This assume #1102's ```eth_requestAccounts``` was approved by the user first to preserve privacy
```suggestion
This assume [EIP-1102](https://eips.ethereum.org/EIPS/eip-1102)'s ```eth_requestAccounts``` was approved by the user first to preserve privacy
```

Likewise in other places.

2020-09-08 23:38 UTC, axic commented on EIPS/eip-2224.md
> +## Open questions
There should be no questions in drafts. Some drafts have "options", which also seems to get discouraged.

I'd suggest to move these under a rationale section explaining what decisions informed the current specification and move other questions to the discussion url.

2020-09-08 23:39 UTC, axic requested changes
Missing section:
- Rationale
- Implementation
- Test Cases
- Backwards Compatibility
- Security Consideration

2020-11-15 01:13 UTC, closed without merging

2025-05-15 17:22 UTC, wighawag commented
Hey @sscovil thanks for the edits

I reviewed them and modified slightly. There was inaccurate references to EIP-712. I think you meant EIP-191 for the signature scheme. EIP-712 is a higher level construct to sign structured messages and automatic-signatures does not need it.

Anyway this repo is now only for consensus changes, there is a new repo for ERCs : https://github.com/ethereum/ERCs

I made a branch on my fork here : https://github.com/wighawag/ERCs/tree/automatic-signatures where I put the new version: https://github.com/wighawag/ERCs/blob/automatic-signatures/ERCS/erc-automatic-signatures.md

But I think before moving forward and making a PR, we should discuss further in the ethereum-magicians thread. The more I think about it, the more I think the correct approach is to have authentication as part of eth_requestAccounts unless there are use-cases that require generic automatic-signatures