Add EIP-684 to Byzantium Meta
ethereum/EIPs pull request #2252
Opened 2019-08-27 11:53 UTC by soc1c

fix #2220 

to my knowledge, all clients implement it

2019-08-27 12:09 UTC, axic commented on EIPS/eip-609.md
> +  - [EIP 684](https://eips.ethereum.org/EIPS/eip-684) (Prevent overwriting contracts)
This is a broken url.

2019-09-05 09:38 UTC, soc1c commented on EIPS/eip-609.md
> +  - [EIP 684](https://eips.ethereum.org/EIPS/eip-684) (Prevent overwriting contracts)
yeah, right, 684 is not even an EIP yet

2020-08-28 23:49 UTC, axic commented
There is a discussion in https://ethereum-magicians.org/t/eip-689-address-collision-of-contract-address-causes-exceptional-halt/3542 about this. I think we should do what was suggested in that discussion and then merge this.

I'd be against merging this PR as-is because currently all the "hard fork metas" are somewhat of a higher quality with linking to well-formatted EIPs. Compared to that this PR would link to a non-EIP-formatted link.

2020-08-28 23:50 UTC, axic requested changes
I think we should make 684 into an EIP and not linking to an issue here.

2020-11-04 01:10 UTC, closed without merging