historic-blockhashes
ethereum/EIPs pull request #2427
Opened 2019-12-04 18:52 UTC by zmitton

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

2020-09-09 08:27 UTC, MicahZoltu requested changes
Along with the suggested changes, this EIP also needs all of the sections found in the template: https://raw.githubusercontent.com/ethereum/EIPs/master/eip-template.md

Is there still interest in this over https://eips.ethereum.org/EIPS/eip-2935 ?  If not, it may be worthwhile to consolidate effort into one of the two.

2020-09-09 08:27 UTC, MicahZoltu commented on EIPS/eip-2427.md
> +lang: en
```suggestion
```
This isn't a valid EIP field.

2020-09-09 08:27 UTC, MicahZoltu commented on EIPS/eip-2427.md
> +replaces: 210
```suggestion
```
Only final EIPs can be replaced.

2020-09-09 08:27 UTC, MicahZoltu commented on EIPS/eip-2427.md
> +discussions-to: https://github.com/ethereumclassic/ECIPs/issues/242
```suggestion
discussions-to: https://github.com/ethereumclassic/ECIPs/issues/242
status: Draft
type: Standards Track
category: Core
created: 2019-12-04
```
Moves discussion-to up to match template for consistency.

2020-09-10 16:07 UTC, zmitton commented
I posted this nearly a year ago after aggregating the best research from multiple other EIPs (themselves over 3 years old). Didn't receive so much as a single comment until now. Might as well just close this one because Vitalik has written one now which will probably actually be payed attention to.

2020-09-10 16:07 UTC, closed without merging

2020-09-10 16:12 UTC, lightclient commented
@zmitton do you have any feedback on how this process can be improved? It is really unfortunate this EIP received no traction when you authored it. Did you share this with anyone in the community (e.g. twitter, eth magicians, etc)?

2020-10-21 18:42 UTC, zmitton commented
I guess my suggestion is that the person assigned to review it, does so. It was clear there was interest, so that means it should get moved to the next step of the process, or given a reason why not?

2020-10-22 10:20 UTC, MicahZoltu commented
We have a had a problem historically of editors not proactively reading EIPs, which meant the only way to get them through the process was to find and pester an editor to read your EIP and review it.  We have gotten better and started to work through the backlog, but editors are still greatly understaffed so this generally continues to be a problem.