EIP: Coinbase calls
ethereum/EIPs pull request #2474
Opened 2020-01-19 06:05 UTC by 3esmit

## Simple Summary

Allow contracts to be called by validator/miner (`block.coinbase`) without a transaction.

## Abstract

Validators/miners can choose become Gas Relayers to pick up fees from meta transactions, they do so by signing a transaction wrapping the meta transaction. However this brings an overhead of a signed transaction by validator that does nothing. This proposal makes possible to remove this unused ecrecover.

## Motivation

In order to reduce the overall overhead of gas abstraction.

## Specification

The calls to be executed by `block.coinbase` would be included first at block, and would consume normally the gas of block, however they won't pay/cost gas, instead the call logic would pay the validator in other form. 

Would be valid to execute any calls without a transaction by the block coinbase, except when the validator call tries to read `msg.sender`, which would throw an invalid jump.

Calls included by the validator would have `tx.origin = block.coinbase` and `gas.price = 0` for the rest of call stack, the rest follows a normal transactions.

## Rationale

TBD

## Backwards Compatibility

TBD

## Test Cases

TBD

## Implementation

TBD

## Security Considerations

TBD

## Copyright

Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

2020-09-09 08:11 UTC, MicahZoltu requested changes
Minor formatting adjustments, but otherwise looks good to merge.  @3esmit is this still desired given that EIP-1559 is likely to make it so miners have to pay some amount for gas?

2020-09-09 08:11 UTC, MicahZoltu commented on EIPS/eip-2474.md
> +
```suggestion
```

2020-09-09 08:11 UTC, MicahZoltu commented on EIPS/eip-2474.md
> +A notable example would be when a validator want to act as an [EIP-1077] Gas Relayer, incentivized to pick up fees from meta transactions.
```suggestion
A notable example would be when a validator want to act as an [EIP-1077](./eip-1077.md) Gas Relayer, incentivized to pick up fees from meta transactions.
```

2020-09-09 08:11 UTC, MicahZoltu commented on EIPS/eip-2474.md
> +[EIP-1077]: https://eips.ethereum.org/EIPS/eip-1077
```suggestion
```

2020-09-30 09:28 UTC, lightclient commented
It looks like there was activity after the initial stale notice, so this shouldn't have been closed?

2020-09-30 11:11 UTC, MicahZoltu commented
Hmm, good point...

2020-09-30 11:12 UTC, MicahZoltu commented
@3esmit Waiting to merge this until I heard back from you on https://github.com/ethereum/EIPs/pull/2474#pullrequestreview-484760851

2020-09-30 19:38 UTC, 3esmit commented on EIPS/eip-2474.md
> +[EIP-1077]: https://eips.ethereum.org/EIPS/eip-1077
Done in 9e97881

2020-09-30 19:39 UTC, 3esmit commented
@MicahZoltu This shouldn't relate to EIP-1559. 
The proposed change in EIP 2474 makes possible to miners to include transactions that don't need a signer, because the validation is done in the smart contract. 
If EIP-1559 makes miners have to pay some gas, this don't changes the fact that some transactions don't need a `msg.sender`. 

This EIP is likely being replaced by #2938

2020-10-01 04:08 UTC, MicahZoltu approved these changes
@3esmit Would you prefer to close this PR in favor of Account Abstraction, or do you still want to pursue this separate from AA?  If you want to pursue it, accept the suggested code change so the bot green lights and then @mention me so I remember to come back and merge.  😄

2020-10-01 04:08 UTC, MicahZoltu commented on EIPS/eip-2474.md
> +type: Standards Track
```suggestion
type: Standards Track
```
To satisfy the validator bot.

2020-10-01 12:31 UTC, 3esmit commented
@MicahZoltu Ok, you can merge. For now we can left it as draft. Once AA gets defined/final, then move this to "abandoned".

2020-10-03 01:48 UTC, merged

2020-10-03 17:14 UTC, lightclient commented
@3esmit FYI in case you haven't seen, #2938 defines AA (with working code!).

2020-10-04 22:51 UTC, 3esmit commented
> @3esmit FYI in case you haven't seen, #2938 defines AA (with working code!).

Awesome. Once 2938 gets final I will move this one to abandoned as it would not be necessary anymore.