Short Weierstrass wrapping curve for BLS12-377
ethereum/EIPs pull request #2541
Opened 2020-02-27 17:53 UTC by shamatar

This EIP adds specification to support an "outer" wrapping curve to allow aggregation of proof and signatures on BLS12-377 (Zexe curve).

2020-06-09 13:34 UTC, iAmMichaelConnor commented on EIPS/eip-2541.md
> +Group order has 377 bits so scalars for multiplication operation is redundantly encoded as `48` bytes by performing BigEndian encoding of the corresponding (unsigned) integer. Corresponding integer i
@shamatar to be compatible with `32`-byte 'words' of the EVM/Solidity (and to allow easy `mload` and `mstore` operations of 32-byte values in assembly), perhaps scalars should be encoded as `64` bytes instead?
Either:
- the first `16`-bytes could be _enforced_ to be all zeros; or 
- any 64-byte integer could be permitted, and precompiles would need to coerce any `64`-byte value into an element of `Fr` (where `r` is the 377-bit main subgroup order).
(I prefer the first option)

It'd be great to get your thoughts.

I'm facing the same decision making process for an EIP for the BW6-761 curve (which also has a 377-bit scalar field).

2020-09-09 07:44 UTC, MicahZoltu requested changes
Just need to remove the comments and pick a new discussions-to location.

2020-09-09 07:44 UTC, MicahZoltu commented on EIPS/eip-2541.md
> +
```suggestion
```

2020-09-09 07:44 UTC, MicahZoltu commented on EIPS/eip-2541.md
> +
```suggestion
```

2020-09-09 07:44 UTC, MicahZoltu commented on EIPS/eip-2541.md
> +
```suggestion
```

2020-09-09 07:44 UTC, MicahZoltu commented on EIPS/eip-2541.md
> +
```suggestion
```

2020-09-09 07:44 UTC, MicahZoltu commented on EIPS/eip-2541.md
> +
```suggestion
```

2020-09-09 07:44 UTC, MicahZoltu commented on EIPS/eip-2541.md
> +<!--The implementations must be completed before any EIP is given status "Final", but it need not be completed before the EIP is accepted. While there is merit to the approach of reaching consensus o
```suggestion
```

2020-09-09 07:44 UTC, MicahZoltu commented on EIPS/eip-2541.md
> +<!--All EIPs must contain a section that discusses the security implications/considerations relevant to the proposed change. Include information that might be important for security discussions, surf
```suggestion
```

2020-09-09 07:44 UTC, MicahZoltu commented on EIPS/eip-2541.md
> +discussions-to: https://github.com/ethereum/EIPs/pull/2541
This cannot be the Pull Request.  You can create a thread on https://ethereum-magicians.org/ or you can create an issue here on GitHub.

2020-09-09 09:25 UTC, axic commented on EIPS/eip-2541.md
> +requires : 1109, 2046
```suggestion
requires: 1109, 2046
```

2020-09-16 10:08 UTC, closed without merging