1363: Move to Last Call
ethereum/EIPs pull request #2617
Opened 2020-04-26 11:02 UTC by vittominacori

Moves EIP 1363 to Last Call.

2020-04-26 11:05 UTC, eip-automerger commented
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - Trying to change EIP 1363 state from Draft to Last Call

2020-09-03 23:14 UTC, axic commented
It is not possible to move from draft to final in a single step, please refer to EIP-1.

2020-09-05 08:37 UTC, vittominacori commented
Updated to Last Call.

It was Last Call first but automerger fails. So I moved to final.

2020-09-05 17:33 UTC, MicahZoltu requested changes
Last Call must have a `review-period-end` of at least 2 weeks in the future.

2020-09-05 17:33 UTC, MicahZoltu commented on EIPS/eip-1363.md
> +status: Last Call
```suggestion
status: Last Call
review-period-end: 2020-09-20
```

2020-09-09 04:57 UTC, MicahZoltu commented
`## Security Considerations` section is required for all EIPs.  It comes right before the Copyright section.  If you believe there are no security considerations, the section can just include one-sentence saying as much.

2020-09-09 04:58 UTC, MicahZoltu commented
I would also recommend changing:
```
Every Payable Token compliant contract MUST implement the ERC-1363 interface other than ERC-20 and ERC-165 interfaces.
```
to
```
Every Payable Token compliant contract **MUST** implement the ERC-1363 interface as well as the ERC-20 and ERC-165 interfaces.
```

2020-09-09 04:59 UTC, MicahZoltu commented
I recommend using the RFC 2119 style for `**MUST**` rather than `MUST`.

2020-09-09 05:02 UTC, MicahZoltu commented
Recommend changing:
```
Description of a Payable Token compatible with the ERC-20 definition. Also description of a Token Receiver and/or Spender that accepts Payable Token payments.
```
to
```
Defines a token interface for ERC-20 tokens that supports executing recipient code on transfer.
```

2020-09-09 05:20 UTC, MicahZoltu commented
Recommend changing the abstract to be a bit more descriptive, maybe mentioning the highlights of the new functions.  I generally recommend the abstract contain a human-readable and terse version of the specification.  Something like, "Adds a `transferAndCall` method that allows the caller to specify that the that the recipient contract will be called with calldata supplied by the caller. ...".  Maybe add a sentence or two about some other features, but I recommend leaving out the specific details like all of the overloads, and the exact mechanism for callbacks, etc.

Basically, state the core protocol in human readable words, but don't cover all of the edge cases and little details.

2020-09-09 05:21 UTC, MicahZoltu requested changes
The Security Considerations section is a hard requirement.  The rest are feedback that I encourage applying, but aren't strictly required to move to Last Call.

2020-09-13 05:57 UTC, MicahZoltu commented
I know I said that the other changes were optional, but on doing a final review I think this change is necessary afterall because the current wording doesn't align with the rest of the document:
> Every Payable Token compliant contract **MUST** implement the ERC-1363 interface other than ERC-20 and ERC-165 interfaces.

to
> Every Payable Token compliant contract **MUST** implement the ERC-1363 interface as well as the ERC-20 and ERC-165 interfaces.

"other than" implies that someone implementing this standard **MUST NOT** implement ERC-20 and ERC-165, which I don't think was the intent.

Along with that change, please also set the review period end to 2 weeks from the date of that change as I *hope* this is the last change before Last Call.  😄

2020-09-13 10:23 UTC, MicahZoltu approved these changes

2020-09-13 10:24 UTC, merged