Initial cut of wallet layout EIP.
ethereum/EIPs pull request #2680
Opened 2020-05-29 13:05 UTC by mcdee

Initial wallet layout proposal.

2020-07-17 11:19 UTC, MicahZoltu commented
I don't know why CI is failing for a bunch of unrelated PRs, but once we figure that out I'm good to merge this.

2020-07-18 08:43 UTC, MicahZoltu commented
Kicking CI.

2020-07-18 08:56 UTC, MicahZoltu commented on EIPS/eip-2680.md
> +## Non-hierarchical store example
This and the following sections should be in one of the template sections.  My guess is you just forgot a `#` at the start?
```suggestion
### Non-hierarchical store example
```

2020-07-18 08:56 UTC, MicahZoltu commented on EIPS/eip-2680.md
> +## Protecting against concurrent write access
```suggestion
### Protecting against concurrent write access
```

2020-07-18 08:57 UTC, MicahZoltu commented on EIPS/eip-2680.md
> +## Iterating over wallets
```suggestion
### Iterating over wallets
```

2020-07-18 08:57 UTC, MicahZoltu commented on EIPS/eip-2680.md
> +## Iterating over accounts
```suggestion
### Iterating over accounts
```

2020-07-18 08:57 UTC, MicahZoltu commented on EIPS/eip-2680.md
> +## Index format.
```suggestion
### Index format
```

2020-07-18 08:59 UTC, MicahZoltu commented on EIPS/eip-2680.md
> +## Copyright
The `Security Considerations` section is missing, and is required.
```suggestion
## Security Considerations
TBD

## Copyright
```

2020-10-31 07:17 UTC, MicahZoltu requested changes
One last (hopefully) item to get this merged.

2020-10-31 07:17 UTC, MicahZoltu commented on EIPS/eip-2680.md
> +}
````suggestion
}
```
````
Missing code block close ticks.

2020-10-31 07:18 UTC, MicahZoltu commented
We are trying to get rid of external links from EIPs as much as possible.  While it won't block merging as draft, it *may* cause problems down the road when merging as Last Call or Final.  Can you look into inlining the content of the external links into this EIP, or adding them as assets in `../assets/eip-2680/`?

2020-10-31 07:31 UTC, MicahZoltu commented
Sorry, I missed that this one wasn't addressed yet: https://github.com/ethereum/EIPs/pull/2680#discussion_r456768459  Also required for merge.

2020-10-31 07:46 UTC, mcdee commented
Updated one of the external links with an internal asset.  Wanted to confirm this is what is desired, as I can't see any non-image assets elsewhere.  Also, if this is correct do we _really_ want to take local copies of RFCs?

2020-10-31 08:57 UTC, MicahZoltu commented
Yeah, that is what I meant.

There exists a spectrum between "link to an RFC" and "link to page that is obviously marketing material meant to pump a shitcoin and will likely 404 by the end of the year".  EIP Editors have a long history of taking no political stance and picking hard line rules that don't require judgement to enforce, and this is one of those stances.  If we let RFCs through, why not IEEE, why not W3C, why not BIPs, why not ShitcoinIPs, etc.  It is easier for us to just have a blanket rule for no external links than to try to enforce a fuzzy line.

To be clear, this isn't a hard and fast rule and the editors may decide to let RFC links through, but the process has less chance of contention if you inline the assets.

2020-10-31 08:57 UTC, merged