Forwarder eip
ethereum/EIPs pull request #2770
Opened 2020-07-05 16:32 UTC by forshtat

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

2020-08-05 11:49 UTC, MicahZoltu commented on EIPS/eip-2770.md
> +In this ERC we propose to introduce a singleton contract whose responsibility is to validate transaction signatures on-chain,
```suggestion
 In this ERC we introduce a singleton contract whose responsibility is to validate transaction signatures on-chain,
```

2020-08-05 11:53 UTC, MicahZoltu commented
Check out #2711 and after reviewing it let me know if you still want me to merge this as a DRAFT.  I believe 2711 solves this problem at layer 1 in a way that is more generalized, and I just want to check with you to see if you still want to proceed with this after knowing about 2711.

2020-08-05 16:10 UTC, lightclient commented on EIPS/eip-2770.md
> +On the other hand, this introduces a requirement for the caller account to have a sufficient amount of Ether to pay for the gas.
`ether` is generally preferable to `Ether`

```console
rg " ether " EIPS | wc -l
64

rg " Ether " EIPS | wc -l
22
```

2021-02-08 20:38 UTC, frangio commented
@forshtat Is this EIP meant to be merged at some point? I'm looking for documentation about `TrustedForwarder` and this is the only thing I could find.

2021-02-09 19:08 UTC, forshtat commented
> @forshtat Is this EIP meant to be merged at some point? I'm looking for documentation about `TrustedForwarder` and this is the only thing I could find.

Hi @frangio ! Yes, this EIP is supposed to supplement the ERC #2771 as a the basic Forwarder contract for a generic meta-transactions infrastructure. 

We were a bit busy and did not update the EIP and was automatically closed, but I think it has to be updated and merged. 

This is the latest code in the GSN repo (it will be published separately from the rest of GSN contracts soon, once we merge some changes in):
https://github.com/opengsn/gsn/blob/master/packages/contracts/src/forwarder/Forwarder.sol

There is a mention of it in our documentation site, but nothing fancy tbh:
https://docs.opengsn.org/contracts/#trusted-forwarder-minimum-viable-trust

@MicahZoltu can you please help reopen this PR? 
The EIP #2711 is proposing a change to the Ethereum protocol, which have taken long to introduce. This ERC, on the other hand, allows contracts to achieve similar results within the existing protocol.

2021-02-10 12:39 UTC, MicahZoltu commented on EIPS/eip-2770.md
> +author: Dror Tirosh <dror.tirosh@gmail.com>, Alex Forshtat <forshtat1@gmail.com>
```suggestion
author: Alex Forshtat (@forshtat) Dror Tirosh <dror.tirosh@gmail.com>, Alex Forshtat <forshtat1@gmail.com>
```
```suggestion
author: Alex Forshtat (@forshtat) Dror Tirosh <dror.tirosh@gmail.com>
```
Either is acceptable, but at least one of the authors should be reachable on GitHub.

2021-02-10 12:41 UTC, MicahZoltu commented on EIPS/eip-2770.md
> +The implementation can be found at https://github.com/opengsn/forwarder
Implementations should either be inline or live in `../assets/eip-2770/<files>`, not be external links.  Alternatively, you can just leave this section out entirely as it is optional.

2021-02-10 12:42 UTC, MicahZoltu commented on EIPS/eip-2770.md
> +#### Forwarder data type registration
```suggestion
### Forwarder data type registration
```
Same for other subsections.  The ToC renders incorrectly in some places when you skip nesting levels.

2021-02-17 09:04 UTC, MicahZoltu requested changes
At the least, the header metadata needs to be fixed and the implementation section addressed (I recommend just removing it).  The rest can be looked into after merge as draft.

Separately, I recommend considering championing one of the proposals that solves sponsored transactions at layer 1 rather than putting a bunch of effort into solving this problem at layer 2 only to have those solutions be significantly worse for UX than layer 1 solutions.

2021-02-21 19:26 UTC, forshtat commented on EIPS/eip-2770.md
> +discussions-to: https://github.com/ethereum/EIPs/pull/2770
Replaced with a link to ethereum-magicians.org, thanks

2021-02-21 19:28 UTC, forshtat commented on EIPS/eip-2770.md
> +for them individually.
Is this rule specific for links, or any mention of draft ERCs is forbidden? Many ERCs remain drafts for many years, while being widely implemented.

2021-02-21 19:28 UTC, forshtat commented on EIPS/eip-2770.md
> +requires: 712, 2770
Sorry, fixed.

2021-02-21 19:30 UTC, forshtat commented on EIPS/eip-2770.md
> +`validUntil` - the highest block number the request can be forwarded in, or 0 if request validity is not time-limited
Added a short rationale. I think this can be taken to the discussion forum if this is a contentious decision.

2021-02-21 19:41 UTC, forshtat commented on EIPS/eip-2770.md
> +```
That is true, gas prices can change and such change will have to be reflected in this ERC and its implementation. If there is a way to solve the problem without relying on current EVM implementation, I will be thrilled to learn about it.
Many contracts already have hard-coded gas values, and so far solving these problems with a solution that can be broken some time into the future has been a lesser evil than not solving those at all.

2021-02-21 20:00 UTC, forshtat commented
> At the least, the header metadata needs to be fixed and the implementation section addressed (I recommend just removing it). The rest can be looked into after merge as draft.
> 
> Separately, I recommend considering championing one of the proposals that solves sponsored transactions at layer 1 rather than putting a bunch of effort into solving this problem at layer 2 only to have those solutions be significantly worse for UX than layer 1 solutions.

I think the header is fixed and implementation section removed.

Regarding the second point, championing the change to Layer 1 implementation, as well as the ongoing discussion about removing gas observability.

These kinds of changes take many years to materialise, if they ever do. They are also risky, expensive and sometimes breaking to existing code.

On the other hand, this ERC does not take nearly as much effort as a Layer-1 change, while providing a solution here and now, as well as a great learning opportunity to such changes in the future. 

You say in ERC-2711 "The arrangements that enable the covering of gas costs is out of scope for this EIP". Well, in GSN we provide a Paymaster interface that can be used to decide whether to pay gas or not. This can enable us to create multiple such arrangements, use them in production code, and experiment with them before we can finalise a viable spec for Layer-1 gas/account abstraction.

As for 'gas observability', I don't believe it is feasible this will happen in the timeframe this ERC is expected to be relevant.  The genie is out of the bottle and production code relies on gas observability all over the place. Once gas stops being observable on Ethereum, this ERC can be abandoned with no harm done.

2021-02-22 16:07 UTC, lightclient approved these changes

2021-02-22 16:07 UTC, merged

2022-12-05 21:38 UTC, ZitRos commented
@forshtat and others – thanks a ton for your hard work.

I've got a quick question. Let me know if this isn't the place to ask it.

I am currently evaluating how nice is GSN. After reading a lot of specs, comments and implementation I still can't answer these 2 design-level questions:

1. We seem to don't need "Trusted forwarder" in our system, since the recipient contract doesn't care who the sender is and does the validation magic on its own. As far as I understand, we have no option but just waste some gas since the framework requires us to have that contract.
2. In Ethereum and other EVMs, you may not only want to cover ETH for the gas, but also pay ETH to other contracts that accept it (`payable`). How one could achieve this? What is the correct approach to achieve this? Putting the ETH payment logic into the TrustedForwarder contract to invoke payable functions is the best I can come up with, but it feels hacky.

It would be awesome if you could give a short hint on achieving the above, and documenting it will help others too. Thanks a ton!