SET_INDESTRUCTIBLE opcode
ethereum/EIPs pull request #2937
Opened 2020-09-04 05:25 UTC by vbuterin

Add a `SET_INDESTRUCTIBLE` opcode that prevents the contract from calling `SELFDESTRUCT`.

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

2020-09-04 13:13 UTC, lightclient approved these changes

2020-09-04 13:13 UTC, lightclient commented on EIPS/eip-2937.md
> +Add a `SET_INDESTRUCTIBLE (0xA8)` opcode that prevents the contract from calling `SELFDESTRUCT (0xff)`.
```suggestion
Add a `SET_INDESTRUCTIBLE (0xA8)` opcode that prevents the contract from calling `SELFDESTRUCT (0xFF)`.
```

2020-09-04 13:13 UTC, lightclient commented on EIPS/eip-2937.md
> +Add a context-wide variable `locals.indestructible` (ie. a variable that lives in the same "space" as memory, stack, PC...), initialized to `False`.
```suggestion
Add a context-wide variable `locals.indestructible` (i.e. a variable that lives in the same "space" as memory, stack, PC...), initialized to `False`.
```

2020-09-04 13:13 UTC, lightclient commented on EIPS/eip-2937.md
> +## Motivation
Motivation is usually above specification.

2020-09-05 09:13 UTC, MicahZoltu requested changes
Formatting stuff needs to be addressed before merge.

2020-09-05 09:13 UTC, MicahZoltu commented on EIPS/eip-2937.md
> +## Specification
```suggestion
## Abstract

## Specification
```
Try to match the template whenever possible as it allows us to do fancy things with automated tooling in the future.

2020-09-05 09:13 UTC, MicahZoltu commented on EIPS/eip-2937.md
> +## Forwards Compatibility and Security
```suggestion
## Rationale

TBD

## Backwards Compatibility

TBD

## Security Considerations

TBD
```

2020-09-05 09:13 UTC, MicahZoltu commented on EIPS/eip-2937.md
> +If `SELFDESTRUCT` is ever removed in the future, this EIP would simply become a no-op.
I'm not personally a fan of forward compatibility stuff in an EIP.  This feels like something much more appropriate in the discussion-to link, or in the HF inclusion discussions.  If you imagine reading this EIP 5 years in the future after it has been implemented, this section won't really provide any significant value to those readers.

2020-09-10 06:06 UTC, MicahZoltu approved these changes

2020-09-10 06:07 UTC, merged