add EIP-2266 example
ethereum/EIPs pull request #2964
Opened 2020-09-10 10:52 UTC by HAOYUatHZ

re: https://github.com/ethereum/EIPs/issues/2266#issuecomment-689996097

2020-09-10 11:00 UTC, eip-automerger commented
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - File assets/eip-2266/Example.sol is not an EIP
 - EIP 2266 requires approval from one of (@sebastianelvis, jiangshan.yu@monash.edu, chris.haoyul@gmail.com)

2020-09-10 11:20 UTC, SebastianElvis approved these changes

2020-09-11 01:24 UTC, MicahZoltu requested changes

2020-09-11 01:24 UTC, MicahZoltu commented on EIPS/eip-2266.md
> +Please visit [here](https://github.com/ethereum/EIPs/blob/master/assets/eip-2266/Example.sol) to find our example implementation.
```suggestion
Please visit [here](../assets/eip-2266/Example.sol) to find our example implementation.
```
Relative path will make this link work in all environments, such as the official EIPs website.

2020-09-11 01:36 UTC, MicahZoltu approved these changes

2020-09-11 01:36 UTC, merged