Add EIP-1654: Off-chain dapp-wallet authentication process
ethereum/EIPs pull request #2995
Opened 2020-09-22 19:22 UTC by pazams

## Replacing and updating a stale PR

This is a new PR following the kind closure of https://github.com/ethereum/EIPs/pull/2119. This PR is now updated to reflect the recent changes to [EIP-1271](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1271.md) and adds it as a required dependency with this commit https://github.com/ethereum/EIPs/commit/a1e98ed7d89e47644c06a83cf5e51c70ae638200

## Context

The "request for comments" phase on EIP 1654 has converged to a stable spec on #1654 .

Additionally, the process in this spec has been implemented successfully by a large number of dapps, including:
Crypto Kitties - https://www.cryptokitties.co/
Cheeze Wizards - https://www.cheezewizards.com/
MyCryptoHeroes - https://www.mycryptoheroes.net/
Etheremon - https://www.etheremon.com/
Megacryptopolis - https://www.megacryptopolis.com/
Blockchain Cuties Universe - https://blockchaincuties.com/
Hyperdragons - https://hyperdragons.alfakingdom.com/

2020-09-23 14:24 UTC, MicahZoltu requested changes
Most of the content in this specification doesn't seem like stuff that needs to be a standard.  While it may be a Good Idea, not all Good Ideas need to be standardized.  If two dapps each utilize a different mechanism for signature validation that is OK.

Why is more than just EIP-1271 required here?  If a contract implements 1271 then it can validate arbitrary signatures and there is no need to have all apps verify the same signature.  Each one can verify something else and that is OK.

2020-09-23 14:24 UTC, MicahZoltu commented on EIPS/eip-1654.md
> +## Copyright
```suggestion
## Security Considerations
TBD

## Copyright
```

2020-09-23 14:24 UTC, MicahZoltu commented on EIPS/eip-1654.md
> +
I believe this section is no longer required, and I encourage removing it if you don't have an inline reference implementation.

2020-09-23 14:24 UTC, MicahZoltu commented on EIPS/eip-1654.md
> +Thanks to @dete @Arachnid @igorbarbashin @turbolent @jordanschalm @hwrdtm for feedback and suggestions
```suggestion
```
EIPs are not the right forum for giving thanks/kudos/props/shout-outs.  If people want, they can look at the discussion-to link for some out of band history.

2020-09-23 14:24 UTC, MicahZoltu commented on EIPS/eip-1654.md
> +- Contract wallets need to support `isValidSignature()` as specified in this document.
Why not EIP-1820 so any contract that supports arbitrary execution can also work?

2020-09-23 14:24 UTC, MicahZoltu commented on EIPS/eip-1654.md
> +[EIP-1271](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1271.md) has done a great work with standardising the signature validation method for contracts. This proposal builds on top of it a p
```suggestion
TBD
```
Rationale is a section for explaining why you made some specific choices that you made.  This statement seems closer to a motivation... though it doesn't really add any value so I recommend deleting it entirely.

2020-09-23 14:24 UTC, MicahZoltu commented on EIPS/eip-1654.md
> +Must implement latest [EIP-1271](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1271.md) with `MAGICVALUE = 0x1626ba7e`.
Consider mentioning in the rationale where this number comes from and why it was chosen (could just be a one-liner if it is obvious).

2020-09-23 14:24 UTC, MicahZoltu commented on EIPS/eip-1654.md
> +Dapps frequently offer a customised off-chain user experience in addition to their smart-contract interface. For example, a dapp may provide a push notification feature to their users, allowing them
I would like to see a section added to the motivation section that explains why it is reasonable for a dapp to "authenticate" a user before letting them view things.  If the data is coming from Ethereum, then it is all public and it gives the user a false sense of security.

2020-09-23 14:24 UTC, MicahZoltu commented on EIPS/eip-1654.md
> +
This isn't a section in the [template](https://raw.githubusercontent.com/ethereum/EIPs/master/eip-template.md).  Recommend moving it to the `## Specification`.

2020-09-23 14:24 UTC, MicahZoltu commented on EIPS/eip-1654.md
> +type: Meta
At best this is `Informational`.  I'm personally pretty against Informational EIPs in general though and think this is just a Good Idea which isn't appropriate for an EIP.

2020-09-24 22:46 UTC, pazams commented
@MicahZoltu 

> Most of the content in this specification doesn't seem like stuff that needs to be a standard. While it may be a Good Idea, not all Good Ideas need to be standardized. If two dapps each utilize a different mechanism for signature validation that is OK.

It is ok, but since a SC needs to know which to support in advance, it's better if everyone can agree instead of having separate clusters of dapps and wallets that work together for the purpose of authentication. That will be the blockchain equivalent of the "browser wars" era of the web.

> Why is more than just EIP-1271 required here? If a contract implements 1271 then it can validate arbitrary signatures and there is no need to have all apps verify the same signature. Each one can verify something else and that is OK.

Indeed this proposal is different than most other EIPs and the debate of its worthiness is important.
This is foremost an offchain algorithm that has been established as a de-facto practice by a wide range of apps listed at the top of this pull request.

The reason why so many apps were able to come together and use the same process was because of this draft.

Now, when a new app developer reaches out to Etheremon to enquire "Hey Etheremon, how did you guys manage to have offchain authentication to work both with Smart Contract wallets and "regular" EOA wallets".

Then Etheremon devs can reply with either:

- Oh well, we recovered the public key from signature, then if it matches with authentication address we are like "great", but if it doesn't, we take the wallet address of the public key, and make a contract call to isValidSignature as specified by EIP 1271, and see if it matches there.

- We use EIP 1654.

If Ethereum is a dev-first community, the second option would make sense as it will make life easier for them. If this proposal needs to be closed, I just hope people can still reach the information needed via the issue https://github.com/ethereum/EIPs/issues/1654

2020-09-27 07:38 UTC, MicahZoltu commented
> Now, when a new app developer reaches out to Etheremon to enquire "Hey Etheremon, how did you guys manage to have offchain authentication to work both with Smart Contract wallets and "regular" EOA wallets".

The third option, which I recommend, is "See https://awesome.blog.example.com/how-to-have-off-chain-authentication-work-with-both-contract-and-eoa"

2020-11-09 08:31 UTC, Souptacular commented
I agree with @MicahZoltu. This EIP delves beyond what Meta EIPs traditionally are. When we talk about "process" in Meta EIPs we are talking about human processes and changes in how things are determined, primarily from a hard fork and EIP process perspective (and we are starting to move away from Meta EIPs that involve hard forks now that we have https://github.com/ethereum/eth1.0-specs/ and https://github.com/ethereum/eth2.0-specs). This EIP is more technical than "process oriented" based on the EIP repo definition of process as it is implied by previous EIPs so I don't think we should merge this.

2020-11-09 17:32 UTC, closed without merging