EIP X: On-chain enactment for off-chain voting
ethereum/EIPs pull request #3000
Opened 2020-09-24 11:10 UTC by izqui

2020-10-07 16:04 UTC, MicahZoltu commented
@izqui Discussed this in EIPIP meeting.  Please add content to this EIP (i.e., get it into draft) ASAP if you want to keep this number.

2020-10-07 16:42 UTC, izqui commented
@MicahZoltu alright, will do before the end of the week. Thanks for the notice

2020-10-12 20:55 UTC, izqui commented
Ready for review and merging an initial draft @MicahZoltu

2020-10-13 08:01 UTC, MicahZoltu requested changes
The discussion-to change is required before merging as a draft.  The rest are either suggestions or may be required changes prior to moving this to Review (the phase after Draft).

2020-10-13 08:01 UTC, MicahZoltu commented on EIPS/eip-3000.md
> +A ERC-3000 configuration specifies the resolver for challenges over scheduled items.
```suggestion
Configuration specifies the resolver for challenges over scheduled items.
```

2020-10-13 16:41 UTC, izqui commented
Thanks for the thorough review @MicahZoltu. All concerns should have been addressed!

2020-10-14 06:24 UTC, MicahZoltu approved these changes
Just needs a Rationale section to be merged as draft.  I still recommend heading the other feedback and getting merged to Review is a bit harder (more strict requirements), but all of that can wait until after Draft is merged except this one.

2020-10-14 06:24 UTC, MicahZoltu commented on EIPS/eip-3000.md
> +## Implementations
```suggestion
## Rationale
TBD

## Implementations
```
Rationale is a required section.  It should focus on stating the reason why specific decisions were made over alternate choices.  Some of the content currently is the Motivation would be more appropriate in the Rationale.

2020-10-14 06:56 UTC, izqui commented
Alright @MicahZoltu, ready to go now!

Thanks for the review, and I will make further changes before asking to change to Review.

2020-10-14 09:41 UTC, merged