Create eip-2228.md
ethereum/EIPs pull request #3141
Opened 2020-11-30 03:25 UTC by fulldecent

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

2020-12-03 11:38 UTC, MicahZoltu commented
Seems like it should be `Ethereum Mainnet` as the canonical name, and `Mainnet` for short.  This comes up specifically in one of the examples where I think `Mainnet on Ethereum` is incorrect, it should read `Ethereum Mainnet` as `Ethereum` isn't a thing something can be "on", but `Ethereum Mainnet` or `Ethereum Ropsten` is something that something can be "on".

2020-12-03 11:38 UTC, MicahZoltu commented
I dislike Informational EIPs, so I'll leave this EIP to someone else to do a full review of.

2020-12-03 11:40 UTC, MicahZoltu commented on EIPS/eip-2228.md
> +The Ethereum network with chainid 1 is referenced from authoritative sources using several names that are conflicting. This standard specifies the name for this network and provides reference example
This summary is too long.  Thin email subject title or GitHub pull request title.  Perhaps something like:
> Defines the naming convention of Ethereum Mainnet.

2020-12-03 11:40 UTC, MicahZoltu commented on EIPS/eip-2228.md
> +The Ethereum network with chainid 1 is referenced from authoritative sources using several names that are conflicting. This standard specifies the name for this network and provides reference example
Also, this simple summary currently includes motivational content, which should be moved to the Motivation section.

2020-12-03 16:28 UTC, lightclient requested changes
One thing about Informational EIP is that many of the EIP headings no longer make sense. I recommend i) addressing Micah's feedback and ii) renaming the sections / reorganizing the EIP to flow more naturally - instead of being constrained via the EIP headings (e.g. backward compatibility, test cases, implementation, etc).

2020-12-03 21:07 UTC, fulldecent commented
Summary is minified at 37e6e07f96009affd80e200d93902136e1433e24.

# This is an informational EIP and should not be merged [straw man argument]

Informational EIPs are in-scope for the EIPs project as defined at https://eips.ethereum.org/EIPS/eip-1 and this draft follows those rules.

# Sections should be renamed/excluded

I disagree. This Informational EIP draft is a specification for how to use language. Test cases and backwards compatibilities section are appropriate for specifications, and I have included them.

If the section heading names are obtuse this should be argued in the context of updating EIP-1 and it should be out of scope in this context of considering a technically-valid EIP draft for publication.

# Summary

I have addressed all technical concerns in this review and request please that this draft be published. Additional discussion on the draft can proceed as comments on the draft content.

2020-12-04 20:04 UTC, lightclient commented on EIPS/eip-2228.md
> +## Implementation
I recommend removing this section.

2020-12-04 20:15 UTC, lightclient approved these changes
As this EIP meets the minimum requirements, I will accept it as a draft. Please consider the feedback regarding the section names. Thank you!

2020-12-04 20:15 UTC, lightclient commented on EIPS/eip-2228.md
> +## Implementation
I recommend removing this section.

2020-12-04 20:15 UTC, lightclient commented on EIPS/eip-2228.md
> +## Test Cases
I recommend renaming this to something more appropriate. "Test Cases" clearly refer to testing technical specifications, whereas this is a change in nomenclature. Something along the lines of "Usage" would be preferred.

2020-12-04 20:16 UTC, merged