After two weeks in "Review", change status to "Last Call"
ethereum/EIPs pull request #3201
Opened 2021-01-14 08:57 UTC by nagydani

There have been no objections for two weeks while the status was "Review", so it is time to move on to "Last Call".

2021-01-15 03:48 UTC, MicahZoltu requested changes
```
ethereum_address        = ( "0x" 40*40HEXDIG ) / ENS_NAME
```
I believe this is a typo, should be `40*HEXDIG`?

2021-01-15 03:48 UTC, MicahZoltu commented on EIPS/eip-681.md
> +status: Last Call
```suggestion
status: Last Call
review-period-end: 2021-01-29
```

2021-01-22 14:33 UTC, nagydani commented
> ```
> ethereum_address        = ( "0x" 40*40HEXDIG ) / ENS_NAME
> ```
> 
> I believe this is a typo, should be `40*HEXDIG`?

Yes, it is a typo, you are correct.

2021-01-22 15:28 UTC, eip-automerger commented
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - Trying to change EIP 681 state from Review to Last Call

2021-01-23 09:00 UTC, MicahZoltu commented on EIPS/eip-681.md
> +review-period-end: 2021-01-30
```suggestion
review-period-end: 2021-02-07
```

2021-01-23 09:01 UTC, MicahZoltu commented
I went ahead and adjusted the review period end to be just over 2 weeks from today so we don't have to wait for another round of dialog with the author.  Once CI passes I'll merge as review.

2021-01-23 09:57 UTC, merged