Change EIP-2718 status from "Draft" to "Review"
ethereum/EIPs pull request #3232
Opened 2021-01-28 20:16 UTC by poojaranjan

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

2021-01-29 03:57 UTC, eip-automerger commented
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - Trying to change EIP 2718 state from Draft to Review
 - EIP 2718 requires approval from one of (@micahzoltu)

2021-01-30 08:06 UTC, MicahZoltu approved these changes

2021-01-30 21:36 UTC, lightclient requested changes

2021-01-30 21:36 UTC, lightclient commented on EIPS/eip-2718.md
> +When designing a new 2718 transaction type, it is **STRONGLY** recommended to include the tranasction type as the first byte of the signed payload.  If you fail to do this, it is possible that your t
```suggestion
When designing a new 2718 transaction type, it is **STRONGLY** recommended to include the transaction type as the first byte of the signed payload.  If you fail to do this, it is possible that your transaction may be signature compatible with transactions of another type which can introduce security vulnerabilities for users.
```

2021-01-31 02:46 UTC, merged