EIP-3198 Draft -> Review
ethereum/EIPs pull request #3330
Opened 2021-03-05 15:32 UTC by abdelhamidbakhta

As discussed during ACD we change EIP-3198 Status to Review

2021-03-05 15:35 UTC, eip-automerger commented
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - Trying to change EIP 3198 state from Draft to Review

2021-03-06 06:08 UTC, MicahZoltu requested changes
Needs an Abstract.  Consider renaming Simple Summary to Abstract and then writing a new Simple Summary like "Adds an opcode that gives the EVM access to the block's base fee.".

----

Needs Rationale to be filled out.  I recommend at least discussing why you decided on the chosen gas cost.

----

Needs Security Considerations.  If there are no known security considerations mention that.

----

Recommend rewording Backward Compatibility to "There are no known backward compatibility issues with this opcode." to match phrasing in other EIPs.

2021-03-08 07:57 UTC, abdelhamidbakhta commented
> Needs an Abstract. Consider renaming Simple Summary to Abstract and then writing a new Simple Summary like "Adds an opcode that gives the EVM access to the block's base fee.".
> 
> Needs Rationale to be filled out. I recommend at least discussing why you decided on the chosen gas cost.
> 
> Needs Security Considerations. If there are no known security considerations mention that.
> 
> Recommend rewording Backward Compatibility to "There are no known backward compatibility issues with this opcode." to match phrasing in other EIPs.

Thanks for your review. I addressed your comments. Let me know if there is anything to change.

2021-03-08 15:43 UTC, lightclient approved these changes

2021-03-08 15:43 UTC, lightclient commented on EIPS/eip-3198.md
> +
Probably don't need this extra space.

2021-03-08 15:43 UTC, MicahZoltu commented on EIPS/eip-3198.md
> +
```suggestion
```

2021-03-09 11:37 UTC, merged