EIP 3529: alternative refund reduction
ethereum/EIPs pull request #3529
Opened 2021-04-24 17:28 UTC by vbuterin

An alternative way to reduce refunds to deal with the issues addressed in EIPs 3298 and 3403.

2021-04-24 17:32 UTC, alita-moore commented
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):


	 - File with name EIPS/eip-3529.md is new and new files must be reviewed

2021-04-24 18:36 UTC, holiman approved these changes
LGTM

2021-04-25 12:55 UTC, MicahZoltu requested changes
Only blockers are the external EIP links and the non-standard section.  The other points of feedback are not required for Draft.

2021-04-25 12:55 UTC, MicahZoltu commented on EIPS/eip-3529.md
> +In [EIP 2200](https://eips.ethereum.org/EIPS/eip-2200#specification), three cases for refunds were introduced:
```suggestion
In [EIP-2200](./eip-2200.md#specification), three cases for refunds were introduced:
```

2021-04-25 12:55 UTC, MicahZoltu commented on EIPS/eip-3529.md
> +A criticism of earlier refund removal EIPs ([EIP 3298](https://eips.ethereum.org/EIPS/eip-3298) and [EIP 3403](https://eips.ethereum.org/EIPS/eip-3403)) is that these EIPs fully remove the incentive
```suggestion
A criticism of earlier refund removal EIPs ([EIP-3298](./eip-3298.md) and [EIP-3403](./eip-3403.md)) is that these EIPs fully remove the incentive to set a value to zero, encouraging users to not fully clear a storage slot if they expect even the smallest probability that they will want to use that storage slot again.
```

2021-04-25 12:55 UTC, MicahZoltu commented on EIPS/eip-3529.md
> +If this EIP were to be implemented, a refund of 4800 gas would remain, so there would only be an incentive to keep a storage slot nonzero if you expect a probability of more than `4800 / 17100 = 28.1
EIPs should be written for a target audience of future readers after it has been decided that it is desirable.
```suggestion
A refund of 4800 gas remains, so there is only be an incentive to keep a storage slot nonzero if you expect a probability of more than `4800 / 17100 = 28.1%` that you will use that slot again. This is not perfect, but it is likely higher than the average person's expectations of later re-acquiring a token with the same address if they clear their entire balance of it.
```

2021-04-25 12:55 UTC, MicahZoltu commented on EIPS/eip-3529.md
> +
This isn't a valid EIP section.  Consider converting this into a test case, or putting it as a subheading in the Rationale section.
```suggestion
```

2021-04-25 12:55 UTC, MicahZoltu commented on EIPS/eip-3529.md
> +A criticism of earlier refund removal EIPs ([EIP 3298](https://eips.ethereum.org/EIPS/eip-3298) and [EIP 3403](https://eips.ethereum.org/EIPS/eip-3403)) is that these EIPs fully remove the incentive
EIP-3298 and 3403 are unlikely to be finalized before this one, which means referencing them will block this EIP from moving to final.  Recommend removing references to them and instead just vaguely discuss alternative proposals directly here like "Another option would be to do X, but that would have problem Y."

2021-04-25 14:44 UTC, alita-moore reviewed
testing bot

2021-04-25 16:36 UTC, vbuterin commented on EIPS/eip-3529.md
> +Remove gas refunds for SELFDESTRUCT, and reduce gas refunds for SSTORE.
```suggestion
Remove gas refunds for SELFDESTRUCT, and reduce gas refunds for SSTORE to a lower level where the refunds are still substantial, but they are no longer high enough for current "exploits" of the refund mechanism to be viable.
```

2021-04-25 16:37 UTC, vbuterin commented on EIPS/eip-3529.md
> +discussions-to: https://ethereum-magicians.org/t/eip-3298-removal-of-refunds/5430
```suggestion
discussions-to: https://ethereum-magicians.org/t/eip-3529-reduction-in-refunds-alternative-to-eip-3298-and-3403-that-better-preserves-existing-clearing-incentives/6097
```

2021-04-25 19:26 UTC, alita-moore reviewed
test bot

2021-04-26 04:45 UTC, vbuterin commented on EIPS/eip-3529.md
> +2. Replace `SSTORE_CLEARS_SCHEDULE` with `SSTORE_RESET_GAS + ACCESS_LIST_STORAGE_KEY_COST` (4,800 gas as of [EIP-2929](./eip-2929.md) + [EIP-2930](./eip-2930.md))
```suggestion
2. Replace `SSTORE_CLEARS_SCHEDULE` (as defined in [EIP-2200](./eip-2929.md)) with `SSTORE_RESET_GAS + ACCESS_LIST_STORAGE_KEY_COST` (4,800 gas as of [EIP-2929](./eip-2929.md) + [EIP-2930](./eip-2930.md))
```

2021-04-26 04:45 UTC, vbuterin commented on EIPS/eip-3529.md
> +2. Replace `SSTORE_CLEARS_SCHEDULE` (as defined in [EIP-2200](./eip-2929.md)) with `SSTORE_RESET_GAS + ACCESS_LIST_STORAGE_KEY_COST` (4,800 gas as of [EIP-2929](./eip-2929.md) + [EIP-2930](./eip-2930
```suggestion
2. Replace `SSTORE_CLEARS_SCHEDULE` (as defined in [EIP-2200](./eip-2200.md)) with `SSTORE_RESET_GAS + ACCESS_LIST_STORAGE_KEY_COST` (4,800 gas as of [EIP-2929](./eip-2929.md) + [EIP-2930](./eip-2930.md))
```

2021-04-26 08:10 UTC, MicahZoltu approved these changes
One more suggestion, but not a blocker.

2021-04-26 08:10 UTC, MicahZoltu commented on EIPS/eip-3529.md
> +Remove gas refunds for SELFDESTRUCT, and reduce gas refunds for SSTORE to a lower level where the refunds are still substantial, but they are no longer high enough for current "exploits" of the refun
Recommend shortening this up.  Think email subject line or forum thread title or GitHub PR title.
```suggestion
Remove gas refunds for SELFDESTRUCT, and reduce gas refunds for SSTORE.
```
The latter part of this sentence should be left for the motivation section.

2021-04-26 08:10 UTC, merged

2025-12-14 17:06 UTC, abo-L commented
> An alternative way to reduce refunds to deal with the issues addressed in EIPs 3298 and 3403.

2025-12-14 17:07 UTC, abo-L commented on EIPS/eip-3529.md
> +discussions-to: https://ethereum-magicians.org/t/eip-3298-removal-of-refunds/5430
@ABOLFAZL4343