Add EIP: Assembly NFT
ethereum/EIPs pull request #3589
Opened 2021-05-24 09:07 UTC by Ungigdu

This standard defines a token which can presents a combination of assets.

2021-05-24 09:07 UTC, alita-moore commented
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):


	 - File with name EIPS/eip-draft_assembly_nft.md is new and new files must be reviewed
	 - This PR requires review from one of [@MicahZoltu, @lightclient]
 @MicahZoltu @lightclient

2021-05-29 11:30 UTC, Ungigdu commented
> Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):
> 
> ```
>  - File with name EIPS/eip-3589.md is new and new files must be reviewed
>  - This PR requires review from one of [@MicahZoltu, @lightclient]
> ```
> 
> @MicahZoltu @lightclient

Should I wait?

2021-05-31 13:43 UTC, MicahZoltu commented
> Should I wait?

Yeah.  I don't handle ERCs, so you'll need to wait for an editor who reviews ERCs to get a chance to take a look (it can sometimes take a while as we are short staffed).

2021-06-02 00:09 UTC, lightclient requested changes
Please review my comments. There are several grammatical errors in this EIP. I recommend going it over a few more times to avoid any other grammatical errors or types. Thanks!

2021-06-02 00:09 UTC, lightclient commented on EIPS/eip-3589.md
> +This standard defines a token which can presents a combination of assets.
```suggestion
This standard defines a token which can represent a combination of assets.
```
please consider this update for clarity

2021-06-02 00:09 UTC, lightclient commented on EIPS/eip-3589.md
> +The ERC-1155 multi token contract defines a way to batch transfer tokens, but those tokens must be mint by the ERC-1155 contract itself. This eip is an ERC-721 extension with ability to assemble asse
```suggestion
The ERC-1155 multi-token contract defines a way to batch transfer tokens, but those tokens must be minted by the ERC-1155 contract itself. This EIP is an ERC-721 extension with ability to assemble assets such as ether, ERC-20 tokens, ERC-721 tokens and ERC-1155 tokens into one ERC-721 token whose token id is also the asset's signature. As assets get assembled into one, batch transfer or swap can be implemented very easily.
```

2021-06-02 00:09 UTC, lightclient commented on EIPS/eip-3589.md
> +As NFT arts and collectors rapidly increases, some collectors are not satisfied with traditional trading methods. When two collectors want to swap some of their collections, currently they can list t
```suggestion
As NFT arts and collectors rapidly increases, some collectors are not satisfied with traditional trading methods. When two collectors want to swap some of their collections, currently they can list their NFTs on the market and notify the other party to buy, but this is inefficient and gas-intensive. Instead, some collectors turn to social media or chat group looking for a trustworthy third party to swap NFTs for them. The third party takes NFTs from both collector A and B, and transfer A's collections to B and B's to A. This is very risky.
```

2021-06-02 00:09 UTC, lightclient commented on EIPS/eip-3589.md
> +The safest way to do batch swap, is to transform batch swap into atomic swap, i.e. one to one swap. But first we should "assemble" those Eth, ERC-20 tokens, ERC-721 tokens and ERC-1155 tokens togethe
```suggestion
The safest way to do batch swap, is to transform batch swap into atomic swap, i.e. one to one swap. But first we should "assemble" those ether, ERC-20 tokens, ERC-721 tokens and ERC-1155 tokens together, and this is the main purpose of this EIP.
```

2021-06-02 00:09 UTC, lightclient commented on EIPS/eip-3589.md
> +  function sateMint(address _to, address[] memory _addresses, uint256[] memory _numbers) payable external override returns(uint256 tokenId){
```suggestion
  function safeMint(address _to, address[] memory _addresses, uint256[] memory _numbers) payable external override returns(uint256 tokenId){
```

2021-06-02 01:33 UTC, Ungigdu commented
> Please review my comments. There are several grammatical errors in this EIP. I recommend going it over a few more times to avoid any other grammatical errors or types. Thanks!

I fixed those grammatical errors, thank you! Need to imporve my english😊

2021-06-02 01:34 UTC, Ungigdu commented
> Please review my comments. There are several grammatical errors in this EIP. I recommend going it over a few more times to avoid any other grammatical errors or types. Thanks!

I fixed those grammatical errors, thank you! Need to imporve my english😊

2021-06-02 12:40 UTC, lightclient requested changes

2021-06-02 12:40 UTC, lightclient commented on EIPS/eip-3589.md
> +## Reference Implementation
```suggestion
## Implementation
```

2021-06-02 12:40 UTC, lightclient commented on EIPS/eip-3589.md
> +
```suggestion
```

2021-06-02 12:41 UTC, lightclient commented
> Need to imporve my english :blush: 

No worries! Welcome :)

2021-06-02 12:49 UTC, lightclient approved these changes

2021-06-02 13:01 UTC, merged