EIP: Reject transactions from senders with deployed code
ethereum/EIPs pull request #3607
Opened 2021-06-10 18:53 UTC by dankrad

This EIP fixes the most sever problem with EOA and contract address collisions, by rejecting all transactions that come from accounts with deployed code (i.e. contracts)

2021-06-10 18:54 UTC, alita-moore commented
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):


	 - File with name EIPS/eip-reject-transactions-from-senders-with-deployed-code.md is new and new files must be reviewed
	 - This PR requires review from one of [@MicahZoltu, @lightclient]
 @MicahZoltu @lightclient

2021-06-10 18:56 UTC, dankrad commented
Discussion to: https://github.com/ethereum/EIPs/issues/3608

2021-06-10 20:06 UTC, fjl commented on EIPS/eip-reject-transactions-from-senders-with-deployed-code.md
> +```
This example doesn't need to be Go code, you could just list the basic values.

2021-06-10 22:02 UTC, lightclient requested changes
Nice EIP, just a couple nits.

2021-06-10 22:02 UTC, lightclient commented on EIPS/eip-reject-transactions-from-senders-with-deployed-code.md
> +1. An attacker can convince a user to send funds to an account before it is deployed. Some applications require this behaviour (e.g. state channels)
```suggestion
1. An attacker can convince a user to send funds to an account before it is deployed. Some applications require this behaviour (e.g. state channels).
```

2021-06-11 05:39 UTC, lightclient requested changes
sorry, missed these in the initial review

2021-06-11 05:39 UTC, lightclient commented on EIPS/eip-3607.md
> +This EIP is a strict security upgrade: It simply makes some transactions that were formely valid now invalid. There is no legitimate use for such transactions, so there should be no security downside
```suggestion
This EIP is a strict security upgrade: It simply makes some transactions that were formerly valid now invalid. There is no legitimate use for such transactions, so there should be no security downsides.
```

2021-06-11 05:39 UTC, lightclient commented on EIPS/eip-3607.md
> +It is unlikely that an attack like this has already occured on the Ethereum mainnet, or we would very likely have heard of it. It is inconceivable that someone would use this as a "feature" to make a
```suggestion
It is unlikely that an attack like this has already occurred on the Ethereum mainnet, or we would very likely have heard of it. It is inconceivable that someone would use this as a "feature" to make a contract an EOA at the same time, when they could simply do this by adding some methods to the contract instead of spending billions on building hardware to find hash collisions.
```

2021-06-11 09:19 UTC, MicahZoltu commented on EIPS/eip-3607.md
> +```
Consider writing this in pseudocode or a more well known/easier to read language than Go.  Also, consider extracting the assignment out of the conditional for a bit more clarity/readability.

2021-06-11 09:20 UTC, MicahZoltu commented on EIPS/eip-3607.md
> +An implementation in go-ethereum can be found [here](https://github.com/ethereum/go-ethereum/pull/23002)
Though we are no longer blocking PRs that include external links to transient things, I still recommend keeping these out of the EIP (same for similar links above).

2021-06-11 09:21 UTC, MicahZoltu approved these changes

2021-06-11 09:22 UTC, merged

2021-06-11 22:38 UTC, dankrad commented on EIPS/eip-3607.md
> +An implementation in go-ethereum can be found [here](https://github.com/ethereum/go-ethereum/pull/23002)
This link in particular would not be transient -- however the links to Hackmd  would. What is the preferred format of these references? We could add them as an appendix? Or push them to a blog with a permalink?

2021-06-11 22:39 UTC, dankrad commented on EIPS/eip-3607.md
> +```
@MariusVanDerWijden

2021-06-12 00:48 UTC, lightclient commented on EIPS/eip-3607.md
> +An implementation in go-ethereum can be found [here](https://github.com/ethereum/go-ethereum/pull/23002)
I think the most preferable method is to add a PDF or markdown to this repository to the text. Here is the format for doing that: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1.md#auxiliary-files

2021-06-12 04:58 UTC, youtacrsbyvars reviewed
###

2021-06-12 07:46 UTC, MicahZoltu commented on EIPS/eip-3607.md
> +An implementation in go-ethereum can be found [here](https://github.com/ethereum/go-ethereum/pull/23002)
Text, JSON, PDF, code, etc. are all fine as assets, we just prefer they live *permanently* within the EIPs repository rather than living externally since organizations change names, repositories change names, GitHub may change its addressing format, etc.  Also, someone should be able to read and understand this EIP in isolation without having context about go-ethereum, Go, etc.

2021-06-12 13:48 UTC, youtacrsbyvars reviewed
Yes

2021-06-15 15:31 UTC, 3sGgpQ8H commented on EIPS/eip-3607.md
> +All these scenarios are much harder to exploit for an attacker, and likely have much lower yield making the attacks unlikely to be economically viable.
The proposed solution doesn't solve the problem for those token contracts, that do implement [EIP-2612](https://eips.ethereum.org/EIPS/eip-2612), as well as for other contracts that rely on the “ecrecover” function.  A very dirty way to fix this would be to modify the behavior of the “ecrecover” function to bever return an address where any code is deployed.
Another attack scenario, the proposed solution doesn't prevent, is when an attacker approves token transfer from an address before deploying a contract at this address.  However, preparation to such attack could be detected, as the attack requires a contract to be deployed at an address, that already has some outgoing transactions.

2021-06-17 07:17 UTC, MicahZoltu commented on EIPS/eip-3607.md
> +All these scenarios are much harder to exploit for an attacker, and likely have much lower yield making the attacks unlikely to be economically viable.
Please leave comments in the discussions-to link at the top of the EIP.  Messages left here are unlikely to be seen.

2021-12-26 16:37 UTC, eulerbeat commented
Is this (EIP-3607) deployed?

2021-12-27 05:44 UTC, MicahZoltu commented
Please use the `discussions-to` link for discussions/questions about an EIP.  You can find the link at the top of the EIP: https://eips.ethereum.org/EIPS/eip-3607