ERC-1271 : Set to Last Call
ethereum/EIPs pull request #3639
Opened 2021-07-05 00:35 UTC by PhABC

2021-07-08 17:25 UTC, lightclient requested changes
@PhABC hey, this looks good on my end. I can't suggest in the diff, but I noticed the section named `Implementation` should be `Reference Implementation` now per EIP-1. If you could update that quickly, I can get this merged ASAP. Thanks!

2021-07-08 17:25 UTC, lightclient commented on EIPS/eip-1271.md
> +status: Last Call
```suggestion
status: Last Call
review-period-end: 2021-07-26
```

2021-07-09 14:59 UTC, PhABC commented
@lightclient Renamed the section! Good catch

2021-07-09 15:00 UTC, lightclient approved these changes
Thanks, looks good to me now.

2021-07-09 15:04 UTC, eip-automerger commented
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - Trying to change EIP 1271 state from Review to Last Call

2021-07-09 15:04 UTC, merged

2021-07-16 18:53 UTC, ItsYoutacRRS reviewed
Please appr