Link to hardfork specs
ethereum/EIPs pull request #3696
Opened 2021-08-03 02:07 UTC by fulldecent

2021-08-03 21:00 UTC, RicardoChacon commented on index.html
> +<p>Ethereum Improvement Proposals (EIPs) describe standards for the Ethereum platform, including core protocol specifications, client APIs, and contract standards. Hardforks are discussed separately
```suggestion
target
```

2021-08-03 21:00 UTC, RicardoChacon commented on index.html
> +<p>Ethereum Improvement Proposals (EIPs) describe standards for the Ethereum platform, including core protocol specifications, client APIs, and contract standards. Hardforks are discussed separately
the target for the <a> tag was missing a t
```suggestion
<p>Ethereum Improvement Proposals (EIPs) describe standards for the Ethereum platform, including core protocol specifications, client APIs, and contract standards. Hardforks are discussed separately in the <a target="_blank" href="https://github.com/ethereum/eth1.0-specs/">Eth1.0 Specifications</a> project.</p>
```

2021-08-03 21:02 UTC, RicardoChacon reviewed
Quick fix

2021-08-06 12:26 UTC, MicahZoltu requested changes

2021-12-06 03:04 UTC, lightclient commented on index.html
> +<p>Ethereum Improvement Proposals (EIPs) describe standards for the Ethereum platform, including core protocol specifications, client APIs, and contract standards. Hardforks are discussed separately
```suggestion
<p>Ethereum Improvement Proposals (EIPs) describe standards for the Ethereum platform, including core protocol specifications, client APIs, and contract standards. Network upgrades are discussed separately in the <a target="_blank" href="https://github.com/ethereum/pm/">Ethereum Project Management</a> repository.</p>
```

2021-12-06 03:04 UTC, lightclient approved these changes

2021-12-06 03:08 UTC, merged