Deprecate type1 transactions
ethereum/EIPs pull request #3709
Opened 2021-08-07 13:33 UTC by GregTheGreek

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

2021-08-07 13:47 UTC, axic commented
Isn't this really just a recommendation for tooling not to use 2930-style transactions?

If so, doesn't this belong under the `Informational` category?  Or does it really need an EIP?  Another option I could see is if we start issuing "Deprecation" notices under the `Core` category, which really bare no real action, just being a deprecation notice.

However if you want to reject such transactions altogether, that is a `Core` change.

2021-08-07 13:53 UTC, GregTheGreek commented
> If so, doesn't this belong under the `Informational` category?
This probably makes more sense, I was following suit on some previous EIPs i saw.

> Another option I could see is if we start issuing "Deprecation" notices under the Core category, which really bare no real action, just being a deprecation notice.
I think this also would be a great addition to make! I fear with `TransactionTypes` in general we're probably going to end up deprecating old ones as we move forward, so this could be a great first step.

> However if you want to reject such transactions altogether, that is a Core change.
I would __love__ to, but that would be unnecessarily chaotic and complicated on the protocol layer.

2021-08-07 14:25 UTC, axic commented
> > However if you want to reject such transactions altogether, that is a Core change.
>
> I would love to, but that would be unnecessarily chaotic and complicated on the protocol layer.

How would that be chaotic on the protocol layer?  I think it is pretty simple on the protocol layer.

It can however be chaotic on the wallet/dapp/ecosystem side ensuring that everyone is aware of the change.  The biggest hurdle as always is hardware wallets, as those, understandably, are the slowest in adoption/change.

2021-08-07 14:31 UTC, GregTheGreek commented
> It can however be chaotic on the wallet/dapp/ecosystem side ensuring that everyone is aware of the change. The biggest hurdle as always is hardware wallets, as those, understandably, are the slowest in adoption/change.

I guess i was thinking they would upgrade type1->type2 but simply rejecting them would be easier...

2021-08-08 03:51 UTC, MicahZoltu commented
A Core EIP would be one that actually removes it from the protocol, like makes blocks with 2930 transactions invalid.

Personally, I think it is more critical to figure out a way to EOL legacy transactions than 2930 transactions.  Legacy transactions don't follow the new 2718 transaction format and generally have a bunch of special case handling.

2021-08-10 17:38 UTC, lightclient requested changes

2021-08-10 17:38 UTC, lightclient commented on EIPS/eip-3709.md
> +Deprecates usage of `TransactionType` 1 on wallets, and providers, upgrading all type 1 transactions to a type 2 transaction.
```suggestion
Deprecates usage of [EIP-2718](./eip-2718.md) `TransactionType` 1 on wallets, and providers, upgrading all type 1 transactions to a type 2 transaction.
```

2021-08-10 17:38 UTC, lightclient commented on EIPS/eip-3709.md
> +--
```suggestion
---
```

2021-09-25 15:42 UTC, lightclient commented on EIPS/eip-3709.md
> +title: Remove Support for Type-1 Transactions
```suggestion
title: Remove Support for Type 1 Transactions
```

2021-09-25 15:42 UTC, lightclient commented on EIPS/eip-3709.md
> +review-period-end: TODO
```suggestion
```

2021-09-25 15:42 UTC, lightclient commented on EIPS/eip-3709.md
> +Deprecates usage of [EIP-2718](./eip-2718.md) `TransactionType` 1 on wallets, and providers, upgrading all type 1 transactions to a type 2 transaction.
```suggestion
Deprecates usage of [EIP-2718](./eip-2718.md) `TransactionType` 1 in wallets and providers, upgrading all type 1 transactions to a type 2 transaction.
```

2021-09-25 15:52 UTC, lightclient commented on EIPS/eip-3709.md
> +The following fields need to be changed, or ammended:
```suggestion
The following fields need to be changed, or amended:
```

2021-09-25 16:15 UTC, lightclient approved these changes

2021-09-25 16:16 UTC, merged