Add draft for ERC-3772
ethereum/EIPs pull request #3773
Opened 2021-08-27 16:41 UTC by zemse

This PR adds a draft of #3772. Pls let me know if any changes are needed.

2021-09-25 17:42 UTC, lightclient requested changes
Nice work on this EIP. I've left a few comments - thanks.

2021-09-25 17:42 UTC, lightclient commented on EIPS/eip-3772.md
> +This document specifies compression of `uint256` to smaller data structures like `uint64`, `uint96`, `uint128`, for optimizing costs for storage in Ethereum Smart Contracts. The smaller data structur
```suggestion
This document specifies compression of `uint256` to smaller data structures like `uint64`, `uint96`, `uint128`, for optimizing costs for storage. The smaller data structure (represented as `cintx`) is divided into two parts, in the first one we store `significant` bits and in the other number of left `shift`s needed on the significant bits to decompress. This document also includes two specifications for decompression due to the nature of compression being lossy, i.e. it causes underflow.
```

2021-09-25 17:42 UTC, lightclient commented on EIPS/eip-3772.md
> +This document specifies compression of `uint256` to smaller data structures like `uint64`, `uint96`, `uint128`, for optimizing costs for storage in Ethereum Smart Contracts. The smaller data structur
Ethereum is assumed :).

2021-09-25 17:42 UTC, lightclient commented on EIPS/eip-3772.md
> +- Usually, we store money amounts in uint256 which takes up one entire slot.
```suggestion
- Usually, we store money amounts in `uint256` which takes up one entire slot.
```

2021-09-25 17:42 UTC, lightclient commented on EIPS/eip-3772.md
> +In this specification, the structure for representing a compressed value is represented using `cintx`, where x is the number of bits taken by the entire compressed value. (On the implementation level
```suggestion
In this specification, the structure for representing a compressed value is represented using `cintx`, where x is the number of bits taken by the entire compressed value. On the implementation level, an `uintx` can be used for storing a `cintx` value.
```

2021-09-25 17:42 UTC, lightclient commented on EIPS/eip-3772.md
> +The rightmost or least significant 8 bits in `cintx` are reserved for storing the shift and the rest available bits are used to store the significant bits starting from the first `1` bit in `uintx`.
```suggestion
The rightmost, or least significant, 8 bits in `cintx` are reserved for storing the shift and the rest available bits are used to store the significant bits starting from the first `1` bit in `uintx`.
```

2021-09-25 17:42 UTC, lightclient commented on EIPS/eip-3772.md
> +The rightmost or least significant 7 bits in `cintx` are reserved for storing the shift and the rest available bits are used to store the significant bits starting from the first on bit in `uintx`.
```suggestion
The rightmost, or least significant, 7 bits in `cintx` are reserved for storing the shift and the rest available bits are used to store the significant bits starting from the first one bit in `uintx`.
```

2021-09-25 17:42 UTC, lightclient commented on EIPS/eip-3772.md
> +The rightmost or least significant 7 bits in `cintx` are reserved for storing the shift and the rest available bits are used to store the significant bits starting from the first on bit in `uintx`.
`s/on/one` typo?

2021-09-25 17:42 UTC, lightclient commented on EIPS/eip-3772.md
> +<!-- ## Test Cases
Please remove these comments.

2021-09-25 17:42 UTC, lightclient commented on EIPS/eip-3772.md
> +<!-- An optional section that contains a reference/example implementation that people can use to assist in understanding or implementing this specification. If the implementation is too large to reas
Please remove.

2021-09-26 16:48 UTC, zemse commented
@lightclient Thanks for your time in reviewing this. I have incorporated the changes.

2021-10-08 10:04 UTC, MicahZoltu commented on EIPS/eip-3772.md
> +
EIPs are not the appropriate place for this kind of history lesson, and should not contain external links.

2021-10-29 13:10 UTC, merged