Logographic NFT Standard
ethereum/EIPs pull request #4341
Opened 2021-10-01 16:39 UTC by simontianx

## Abstract
A vanilla non-fungible token standard proposed by [EIP-3754](./eip-3754.md) together with the established **unicode** system can create an on-chain language system particularly valuable for representing language characters that are logographs. Examples include _hanzi_ in Mandarin, _kanji_ in Japanese, _hanja_ in Korean, and etc. On-chain chatting, blogs, micro-blogs systems can be built for communities using such languages.

## Motivation
A logograph is a written character that represents a word or morpheme, whereas a unicode is an information technology standard for the consistent encoding, representation, and handling of texts. A vanilla NFT by [EIP-3754](./eip-3754.md) by specifying tokenIds as certain unicodes can open up a new language system for on-chain representation of logograpic languages.

This is particularly valuable for logographs because a rich amount of meanings can be transmitted in just a few characters or tokens. However, this is not providing enough additional utility for non-logographic languages such as English. Emojis can be included as well.

A motivating example is instead of sending the two Chinese letters of the Great Wall `长城`, two EIP-3754 tokens with ID`#38271` and ID`#22478` that are the corresponding decimal unicodes of the two characters can be sent. The receiving end decodes the IDs and retrieves the original logographic characters. A key point to pay attention to is the ordering information matters since the tuples `(#38271, #22478)` and `(#22478, #38271)` mean `长城` and `城长`, respectively, and both are legitimate words in the Chinese language.

Besides, in the eastern Asian culture, characters are sometimes considered or practically used as gifts in holidays such as Spring Feastival, etc. `(#24685, #21916, #21457, #36001)` can be used literally as a gift to express the best wishes for financial prosperity.

What is even more interesting is in that culture, people consider ancient teachings as treasures which are usually written in an obscure way that a handle of characters can be unfolded with a rich amount of meanings. Modern people now get a chance to speak to the future generations by sending tokens.

2021-10-02 18:51 UTC, YuansongFeng commented
It's an interesting idea. Though to me it makes more sense for this to be a combination of EIP 721 and unicode. Unicode is more of a unique asset than a form of ownership.

2021-10-03 10:47 UTC, simontianx commented
> It's an interesting idea. Though to me it makes more sense for this to be a combination of EIP 721 and unicode. Unicode is more of a unique asset than a form of ownership.

If we think hard about it, a logograph is indeed a form of abstract ownership of ideas, concepts, and meanings. :-)

2021-10-03 14:26 UTC, simontianx commented
@MicahZoltu Hey Micah, is it possible to hide or collapse the non-relevant activities between conversations?

2021-10-03 14:32 UTC, MicahZoltu commented
Conversations should be happening in the `discussions-to` link, not in the PR.  The PR should only have editorial type comments, not discussions about the EIP contents itself.

2021-10-19 16:48 UTC, lightclient commented on EIPS/eip-4341.md
> +replaces (*optional): <EIP number(s)>
```suggestion
```

2021-10-19 16:50 UTC, lightclient commented on EIPS/eip-4341.md
> +representation, and handling of texts. If the tokenId of an NFT is specified as
```suggestion
representation, and handling of texts. If the `tokenId` of an NFT is specified as

```

2021-10-19 16:51 UTC, lightclient commented on EIPS/eip-4341.md
> +language. This illustrates the key difference between this standard and ERC1155.
```suggestion
language. This illustrates the key difference between this standard and [ERC-1155](./eip-1155.md).

```

2021-10-19 16:52 UTC, lightclient commented on EIPS/eip-4341.md
> +If we think of [ERC1155](./eip-1155.md) together with [ERC721](./eip-721.md) being
```suggestion
If we think of [ERC-1155](./eip-1155.md) together with [ERC-721](./eip-721.md) being
```

2021-10-19 16:52 UTC, lightclient commented on EIPS/eip-4341.md
> +and this standard EIP-4341 are in the track of representing the utility sides of NFTs.
```suggestion
and this standard are in the track of representing the utility sides of NFTs.

```

2021-10-19 16:53 UTC, lightclient commented on EIPS/eip-4341.md
> +Compared with ERC1155, this standard is particularly useful in logographic
```suggestion
Compared with ERC-1155, this standard is particularly useful in logographic

```

2021-10-19 16:53 UTC, lightclient commented on EIPS/eip-4341.md
> +maintained whereas such information is completed discarded in ERC1155. It is not
```suggestion
maintained whereas such information is completed discarded in ERC-1155. It is not

```

2021-10-19 16:53 UTC, lightclient commented on EIPS/eip-4341.md
> +a problem in ERC1155 since no valuable information is encoded in the order of
```suggestion
a problem in ERC-1155 since no valuable information is encoded in the order of

```

2021-10-19 16:53 UTC, lightclient commented on EIPS/eip-4341.md
> +tokenIds, however, in this standard, as illustrated above, it is crucial in
```suggestion
`tokenId`s, however, in this standard, as illustrated above, it is crucial in

```

2021-10-19 16:53 UTC, lightclient commented on EIPS/eip-4341.md
> +representations. Therefore, the ordering information in a batch of tokenIds is
```suggestion
representations. Therefore, the ordering information in a batch of `tokenId`s is

```

2021-10-19 16:54 UTC, lightclient commented on EIPS/eip-4341.md
> +To further distinguish this standard from ERC1155, `URI`s should be excluded in
```suggestion
To further distinguish this standard from ERC-1155, `URI`s should be excluded in

```

2022-01-03 13:15 UTC, simontianx commented
> There has been no activity on this pull request for two months. It will be closed in a week if no further activity occurs. If you would like to move this EIP forward, please respond to any outstanding feedback or add a comment indicating that you have addressed all required feedback and are ready for a review.

Hi all feedbacks and comments are addressed in the latest commit and this EIP is ready for a review.

2022-01-04 05:49 UTC, MicahZoltu commented
cc @lightclient

2022-01-05 03:22 UTC, lightclient requested changes

2022-01-05 03:22 UTC, lightclient commented on EIPS/eip-4341.md
> +description: The ordering information of multiple NFTs is retained and managed.
```suggestion
description: The ordering information of multiple NFTs is retained and managed

```

2022-01-05 03:22 UTC, lightclient commented on EIPS/eip-4341.md
> +type: Standards Track,
```suggestion
type: Standards Track
```

2022-01-05 03:22 UTC, lightclient commented on EIPS/eip-4341.md
> +title: Multi Ordered NFT Standard
```suggestion
title: Ordered NFT Batch Standard
```
Just a suggestion, but I find this title much more descriptive.

2022-01-05 03:33 UTC, lightclient commented on EIPS/eip-4341.md
> +
```suggestion
```

2022-01-05 03:39 UTC, lightclient approved these changes
I pushed a couple minor fixes so that I can approve and merge this to draft. Please consider my suggestion on modifying the title to something clearer. Thank you.

2022-01-05 03:49 UTC, merged