Update EIP-3540: Set prefix to 0xEF00
ethereum/EIPs pull request #4387
Opened 2021-10-23 16:28 UTC by chfast

2021-11-01 16:59 UTC, gumb0 commented on EIPS/eip-3540.md
> +2. No contracts starting with `0xEF` bytes exist public testnets: Goerli, Ropsten, Rinkeby, Kovan and Sepolia at their London fork block.
```suggestion
2. No contracts starting with `0xEF` bytes exist on public testnets: Goerli, Ropsten, Rinkeby, Kovan and Sepolia at their London fork block.
```

2021-11-01 17:15 UTC, gumb0 requested changes

2021-11-01 17:15 UTC, gumb0 commented on EIPS/eip-3540.md
> +MAGIC = 0x00
These two versions of the code that are being added are in fact outdated, should be removed.

2021-11-03 14:16 UTC, gumb0 approved these changes

2021-11-04 10:29 UTC, axic commented on EIPS/eip-3540.md
> +- evmone: https://github.com/ethereum/evmone/pull/303
These aren't supposed to be here anymore.

2021-11-04 13:32 UTC, axic approved these changes

2021-11-04 13:43 UTC, merged

2021-11-04 14:35 UTC, alita-moore commented
@axic did you close and reopen because you waited a few minutes and it wasn't responding or did you do that right after reviewing?

2021-11-04 14:37 UTC, axic commented
A few minutes after, but not too long.

2021-11-04 14:37 UTC, alita-moore commented
okay, I see the chfast also marked this as ready for review after your review. Do you think this was related?

2021-11-04 14:42 UTC, axic commented
Likely that was the case.