Unstagnant EIP-3224
ethereum/EIPs pull request #4428
Opened 2021-11-07 04:15 UTC by ricmoo

Move EIP-3224 from Stagnant back to Draft.

2021-11-07 04:27 UTC, MicahZoltu requested changes
The Simple Summary section should be removed and a `description` header field should be added below `title` that contains essentially the same thing.  Try to keep it as short as possible, one sentence (and one line, don't hardcode newlines).

Remove external links from Test Cases.  Contracts that the tests are run against should be included either as an asset or inline, or just left out if they aren't required.

2021-11-07 04:28 UTC, ricmoo commented
I was planning on doing that once the PR was put back into draft, so that this PR would be as simple as possible. There are also a few spelling mistakes I was planning.

2021-11-07 04:28 UTC, ricmoo commented
(or should I do that first?)

2021-11-07 04:33 UTC, MicahZoltu commented
Those changes should be made before merging as draft, the same as for someone creating a new EIP.  The idea is that an EIP should be structurally sound and generally follow the various rules we have if it shows up on the EIPs page.

2021-11-07 05:16 UTC, ricmoo commented
I also removed all the external links in the security section.

2021-11-08 08:09 UTC, ricmoo commented
I've made the suggested changes.

2021-11-10 17:32 UTC, axic commented on EIPS/eip-3224.md
> +- HTML could be enbedded to attempt to trick web-based wallets into executing code using the script tag (possibly uploading any private keys to a server)
```suggestion
- HTML could be embedded to attempt to trick web-based wallets into executing code using the script tag (possibly uploading any private keys to a server)
```

2021-11-10 19:29 UTC, axic requested changes
Some issues:
- still has simple summary section.
- `function eipXXXDescribe` should probably be renamed.
- there's a TODO in rationale

And as a comment: I am not sure if this should be two EIPs, one for the on-chain element and the other for RPC (or wherever RPCs are maintained now).

2021-11-10 19:43 UTC, ricmoo commented
@axic 

It will be two EIPs, I’m just trying to get it back into draft status so I can make meaningful changes to it again. :)

For now I thought it’d be best to intentionally leave the `describeEipXXX` because I don’t wNt people jumping the gun and adding it yet. I don’t want another `eth_signTypedData_v4` situation.

I can remove the TODO. I was thinking that would be fine in a draft.

Thanks! :)

2021-11-10 20:46 UTC, ricmoo commented
Thanks. Done. :)

2021-11-10 21:15 UTC, axic approved these changes
Looks good enough to me. Not good enough to move past Draft though.

2021-11-11 05:26 UTC, merged