EIP-Draft: QR Code data transmission protocol for the Ethereum wallets
ethereum/EIPs pull request #4527
Opened 2021-12-07 12:47 UTC by aaronisme

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

2021-12-07 16:57 UTC, lightclient requested changes

2021-12-07 16:57 UTC, lightclient commented on EIPS/eip_draft_qr_code_data_transmission_protocol.md
> +eip: eip_draft_qr_code_data_transmission_protocol
```suggestion
eip: 4527
```

2021-12-07 16:57 UTC, lightclient commented on EIPS/eip_draft_qr_code_data_transmission_protocol.md
> +### Process:
```suggestion
### Process
```

2021-12-07 16:57 UTC, lightclient commented on EIPS/eip_draft_qr_code_data_transmission_protocol.md
> +
```suggestion
```

2021-12-07 16:57 UTC, lightclient commented on EIPS/eip_draft_qr_code_data_transmission_protocol.md
> +author: Aaron Chen (@aaronisme), Sora Lee (@soralit), ligi(@ligi), Dan Miller(@danjm), AndreasGassmann (@andreasgassmann), xardass(@xardass), Lixin Liu (@BitcoinLixin)
```suggestion
author: Aaron Chen (@aaronisme), Sora Lee (@soralit), ligi (@ligi), Dan Miller (@danjm), AndreasGassmann (@andreasgassmann), xardass (@xardass), Lixin Liu (@BitcoinLixin)
```

2021-12-08 01:59 UTC, alita-moore commented
> A critical exception has occurred (cc @alita-moore):
> 	Message: incomplete explicit mapping pair; a key node is missed; or followed by a non-tabulated empty line at line 4, column 15:
>     author: author: aaron chen (@aaronisme), sora  ... 
>                   ^
> 

There is a ticket in place to address this unhandled exception

2021-12-08 02:05 UTC, aaronisme commented
> > A critical exception has occurred (cc @alita-moore):
> > Message: incomplete explicit mapping pair; a key node is missed; or followed by a non-tabulated empty line at line 4, column 15:
> > author: author: aaron chen (@aaronisme), sora  ...
> > ^
> 
> There is a ticket in place to address this unhandled exception

The issue have been fixed

2021-12-08 02:07 UTC, aaronisme commented
@lightclient I have fixed the comments you mentioned and renamed the file as `eip-4527.md`. Would you please do another review ?

2021-12-08 02:09 UTC, alita-moore commented
@aaronisme yep, so this is a bot and there are certain situations it's not equipped to handle. I was making it known that I will be equipping the bot someone soon.

2021-12-08 02:11 UTC, aaronisme commented
> @aaronisme yep, so this is a bot and there are certain situations it's not equipped to handle. I was making it known that I will be equipping the bot soon.

Sure, Thanks

2022-01-27 00:52 UTC, BitcoinLixin commented
To whom it may concern,

This EIP has been implemented to Keystone hardware wallet & MetaMask extension wallet integration - https://twitter.com/MetaMask/status/1469351219290382341
Demo Video - https://youtu.be/1eM53TYG1YA

Currently,
* [Airgap.it](https://airgap.it/) is following this EIP to integrate with MetaMask extension wallet. This app can turn people's old mobile phone into an offline signer with QR code.
* Keystone team is working on MetaMask Mobile wallet integration following this EIP.
* [Rabby Wallet](https://rabby.io/) is integrating Keystone following this EIP.

2022-02-04 04:22 UTC, lightclient approved these changes
Overall looks good, just a few comments.

2022-02-07 03:33 UTC, aaronisme commented on EIPS/eip-4527.md
> +title: QR Code data transmission protocol for the Ethereum wallets
Updated

2022-02-07 03:33 UTC, aaronisme commented on EIPS/eip-4527.md
> +Since a single QR Code can only contain a limited amount of data, animated QR Codes should be utilized for data transmission. The [BlockchainCommons](https://github.com/BlockchainCommons/) have publi
Sure, updated the link and add the commit

2022-02-07 03:35 UTC, merged