Move EIP-2098 to final call
ethereum/EIPs pull request #4611
Opened 2021-12-27 22:06 UTC by ricmoo

Moving EIP-2098 to final call.

2022-01-04 16:48 UTC, poojaranjan commented on EIPS/eip-2098.md
> +status: Final Call
```suggestion
status: Last Call
last-call-deadline: 2022-01-11
```

2022-01-05 03:47 UTC, lightclient requested changes
* `s/Test Vectors/Test Cases`
* `Gas Analysis` is not a valid `##` section per EIP-1, please include that information in one of the other sections. `Rationale` seems like the best choice?
* `s/Implementations/Reference Implementation`
* `Acknowledgments` is not a valid EIP section, please remove
* `Security Considerations` is missing

2022-01-08 03:16 UTC, Pencab approved these changes

2022-01-22 13:13 UTC, ricmoo commented
These changes have been made.

2022-01-23 03:32 UTC, MicahZoltu commented on EIPS/eip-2098.md
> +status: Last Call
```suggestion
status: Last Call
last-call-deadline: 2022-02-13
```

2022-02-04 04:00 UTC, lightclient requested changes

2022-02-04 04:00 UTC, lightclient commented on EIPS/eip-2098.md
> +## Reference Implementations
```suggestion
## Reference Implementation
```

2022-02-04 04:06 UTC, lightclient approved these changes

2022-02-04 21:16 UTC, merged