EIP-4361: fix mandatory fields (domain & chainId)
ethereum/EIPs pull request #4655
Opened 2022-01-09 22:38 UTC by TimDaub

The spec's ABNF and the ABNF in the reference implementation all mandate `domain` and `chainId` to be required fields in a message, so we add them to the specification text for completeness as well.

Comment on Ethereum Magicians is here: https://ethereum-magicians.org/t/eip-4361-sign-in-with-ethereum/7263/11

2022-01-10 03:26 UTC, wyc commented
Thanks, this resolves a discrepancy in the text of the spec to match the ABNF. I agree it should be matched this way and not the other way around. Appreciate the keen eye and PR!

2022-01-11 04:48 UTC, MicahZoltu commented
@wyc If this PR is acceptable to you (an author of this EIP), please use the GitHub PR Review feature to approve it.  The bot should auto-merge once you do.

2022-01-11 15:17 UTC, wyc requested changes

2022-01-11 15:17 UTC, wyc commented on EIPS/eip-4361.md
> +1. The wallet presents the user with a structured plaintext message or equivalent interface for signing with the [EIP-191](./eip-191.md) signature scheme (string prefixed with `\x19Ethereum Signed Me
```suggestion
1. The wallet presents the user with a structured plaintext message or equivalent interface for signing with the [EIP-191](./eip-191.md) signature scheme (string prefixed with `\x19Ethereum Signed Message:\n<length of message>`). The `message` MUST incorporate an Ethereum `address`,  `domain` requesting the signing, `version` of the message, a chain identifier `chain-id`, `uri` for scoping, `nonce` acceptable to the server, and `issued-at` timestamp.
```

2022-01-12 15:21 UTC, wyc approved these changes

2022-01-13 05:03 UTC, merged