Typo in eip-191
ethereum/EIPs pull request #4677
Opened 2022-01-14 01:24 UTC by DrakeEvans

I noticed a typo in eip-191, so I thought I would fix it.  I couldn't find any contributing guidelines so I hope this is ok.

2022-01-15 08:33 UTC, MicahZoltu approved these changes

2022-01-15 08:37 UTC, MicahZoltu requested changes
Thinking twice on this, if we are going to fix the typo, we should fix it all the way.  😄

2022-01-15 08:37 UTC, MicahZoltu commented on EIPS/eip-191.md
> +    3. User `A` and `B` submits `presigned` transaction to `X`.
```suggestion
    3. User `A` and `B` submit `presigned` transactions to `X`.
```

2022-01-17 14:49 UTC, holiman approved these changes

2022-01-19 04:37 UTC, merged

2022-01-19 18:41 UTC, alita-moore commented
Did this not auto merge @MicahZoltu?

2022-01-19 18:42 UTC, alita-moore commented
oh @MicahZoltu this wasn't auto merging because you had requested changes.

2022-01-19 18:43 UTC, alita-moore commented
so you probably needed to approve it again

2022-01-23 03:36 UTC, MicahZoltu commented
> so you probably needed to approve it again

Ah, my bad.  Thanks for noticing, I'll try to keep my eye out for this in the future.