Consensus Layer Withdrawal Protection
ethereum/EIPs pull request #4736
Opened 2022-01-31 16:41 UTC by benjaminchodroff

2022-01-31 21:38 UTC, SamWilsn commented on eip-draft_clwp.md
> +requires (*optional): <EIP number(s)>
```suggestion
category: Interface
created: 2022-01-30
```

Can drop the `requires` section, and the stuff in parentheses is just a note for authors.

2022-02-05 09:06 UTC, pk910 commented
Hmm, interesting.. Are there so many withdrawal keys compromised that this is a relevant problem already?
Validators should know how to handle mnemonics.. If someone compromises your wallet mnemonic that's your problem and there is no withdrawal delay for non-community-whitelisted transactions ;)

How should the "delay rebroadcast change withdrawal address request" part of your proposal work? 
If a valid change withdrawal address request that is not "whitelisted" gets delayed by 5 epochs on every node that receives it it'll probably take a very long time till all nodes got it.. But it's still a valid request.
That's probably what you want to achieve, so a "whitelisted" request gets propagated faster as "non-whitelisted" ones are delayed.
Wouldn't it be a better approach to rebroadcast immediately, but delay inclusion in locally built blocks for 5 epochs instead?
That way non-whitelisted but valid requests are just delayed by a maximum of 5 epochs, but not longer.
An attacker is probably smart enough to broadcast his malicious "change withdrawal address request" to as many nodes as possible to get around that double/tripple/... re-broadcast delay anyway..

This proposal needs a high participation rate to have an effect. Just a single validator would be enough to include many non-whitelisted change withdrawal address requests in a block if chosen as a proposer..
The "Change Withdrawal Address Broadcast File" needs to be updated automatically to keep in sync with the claim-repository.
Btw. Who should be in control of this repository and who should be allowed to decide in a "contested claim" and who in general is responsible for security of that repository?
Is all that necessary for a hopefully small group of validators that handled their withdrawal mnemonic insecurely?

(Just commenting what came in my head as a dev interested staking user here 😉 Happy to be proven wrong)

2022-02-05 10:42 UTC, froid1911 commented
This is indeed an awesome proposal, but I have seen various Stakers who lost access to their cl withdrawal keys and only have access to the deposit and verifier keys. Therefore I propose to change the consensus_layer_withdrawal_signature to consensus_layer_verifier_signature.

2022-02-05 10:47 UTC, benjaminchodroff commented
> (Just commenting what came in my head as a dev interested staking user here 😉 Happy to be proven wrong)
Sincerely, thank you! I really appreciate any feedback -- and welcome the discussion.

Yes, the intent of the rebroadcast delay is a slight inconvenience for everyone, but not a permanent denial for anyone. While delayed, it also assumed that the request would not be included in locally built blocks too. Perhaps that isn't clear in the EIP, and thank you for the suggestion. We do not need all nodes to stop rebroadcasting, but the more that participate, the more the proposal helps. Even a slight statistical edge may help someone.

> This proposal needs a high participation rate to have an effect. 
Not necessarily. If the attackers are lazy and don't get broadcast their change withdrawal address on the first available block, it may help many legitimate users who were unaware they were compromised. If an attacker makes a public claim that is contested, at least it lets the legitimate user know they are indeed under attack -- and potentially the social mechanism could expose the hacker...

> The "Change Withdrawal Address Broadcast File" needs to be updated automatically to keep in sync with the claim-repository. 
Not necessarily. Simply not being included in the "change withdrawal address broadcast file" means by default they will be slightly delayed in being accepted if they are requesting an address that isn't their original deposit address. Additionally, this is really only for 0x00 CL addresses. It is expected new validators would default to specifying their 0x01 address upon starting their validator. 

The proposal assumes there is not a single repository. Anyone using this proposal could create a "contested claim" repository and could create a list by any social enforcement mechanism they find acceptable (aka: I'm a hacker, and I only include my own addresses as acceptable evidence!) That being said, I do intend to run my own repository and provide verifiable claims that others can verify themselves, or safely ignore.

2022-02-05 11:31 UTC, benjaminchodroff commented
> therefore I propose to change the consensus_layer_withdrawal_signature to consensus_layer_validator_signature

That idea is not "protection" and sadly outside the scope of this proposal. I do agree that a similar "Consensus Layer Recovery" EIP could be written, but would almost certainly require a change to consensus - and that is going to certainly face a harder challenge to get the community to agree.

2022-02-08 16:48 UTC, lightclient requested changes
Overall looks pretty good to me.

2022-02-08 16:48 UTC, lightclient commented on eip-draft_clwp.md
> +eip: <to be assigned>
```suggestion
eip: 4736
```

2022-02-08 16:49 UTC, lightclient commented
Please move discussions to the `discussions-to` thread.

2022-02-10 16:03 UTC, lightclient requested changes

2022-02-12 05:21 UTC, MicahZoltu commented on EIPS/eip-4736.md
> +
```suggestion
```
This is an optional section, so it can be left out until such time as you actually have something to put into it.

2022-02-12 05:21 UTC, MicahZoltu commented on EIPS/eip-4736.md
> +The Consensus Layer change withdrawal credentials operation is [not yet fully specified](https://github.com/ethereum/consensus-specs/pull/2759), but MUST have at least the following fields:
While linking to Ethereum specifications is borderline acceptable, linking to a pull request to a specification is not.  Please remove this link until such time as the specification is actually updated.

2022-02-15 06:33 UTC, MicahZoltu commented on EIPS/eip-4736.md
> +```withdrawal credential, withdrawal address```
```suggestion
`withdrawal credential, withdrawal address`
```

2022-02-15 06:34 UTC, MicahZoltu commented
Why is this an EIP?  I thought consensus layer changes had their own specification system/process and EIPs were used exclusively for execution layer specifications?

2022-02-16 17:03 UTC, benjaminchodroff commented
> Why is this an EIP?
Fair point, we are in an unchartered area with Ethereum being both EL and CL, but this is a proposal to improve Ethereum and others guided that this was the best way to do so. I hope to use this proposal to get agreement on the specification before we start to submit pull requests to implement it.

2022-02-17 08:52 UTC, MicahZoltu commented
There is certainly disagreement within the community around the future of change control post merge.  My understanding of the unstable schelling point was that we would continue to keep CL and EL change control processes separate until such time as we figure out how to consolidate them.

2022-02-19 07:49 UTC, MicahZoltu commented
I personally don't think an EIP is the best way to get community feedback on an idea.  I would prefer a HackMD article, ethresear.ch post, Ethereum Magicians post, etc. (or some combination thereof).  IMO, EIPs serve one very specific purpose well, which is standardization/specifications of Ethereum Execution Layer consensus changes, and it is a pretty poor process for basically everything else.  This all being said, this is not a dictatorship and one of the other editors may disagree with me and agree to merge this.  You will want to get CI passing first though:
> eip-4736.md:	description exceeds max length of 140 characters

2022-03-19 02:29 UTC, lightclient approved these changes

2022-03-19 02:33 UTC, merged