chore: move EIP-4626 to Last Call
ethereum/EIPs pull request #4751
Opened 2022-02-03 16:01 UTC by fubuloubu

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

2022-02-07 13:51 UTC, lightclient requested changes
Hi, there are 2 instances of "ERC20". They should be replaced with ERC-20. Otherwise, it looks good.

2022-02-07 14:12 UTC, axic commented
Please note there are some pending PRs which I think should be merged prior to going to last call.

2022-02-18 16:50 UTC, sambacha commented
> @axic, thanks for pointing that out. It appears there are two outstanding PRs:
> 
> * [4626: clarify behavior #4777](https://github.com/ethereum/EIPs/pull/4777)
> * [4626: Some copywriting changes #4781](https://github.com/ethereum/EIPs/pull/4781)
> 
> @fubuloubu, could you address these PRs and resolve the conflicts in this one? Thanks.

https://github.com/ethereum/EIPs/pull/4806 included all of the changes in this PR. This can close

_Originally posted by @Joeysantoro in https://github.com/ethereum/EIPs/issues/4781#issuecomment-1039722848_

seems like we are ready for last call now
💯

2022-02-19 07:50 UTC, MicahZoltu commented
Needs conflicts resolved.

2022-02-20 00:49 UTC, fubuloubu commented
> Needs conflicts resolved.

resolved

2022-02-21 15:15 UTC, Joeysantoro commented
Should be ready to go! @lightclient @MicahZoltu

2022-02-22 16:44 UTC, wschwab requested changes
this just needs the deadline field for the Last Call deadline, I've added it as a suggestion with two weeks from today, if there are more delays before this gets merged, you might want to move it a bit

2022-02-22 16:44 UTC, wschwab commented on EIPS/eip-4626.md
> +status: Last Call
```suggestion
status: Last Call
last-call-deadline: 2022-03-08
```

2022-02-23 01:03 UTC, fubuloubu commented on EIPS/eip-4626.md
> +status: Last Call
```suggestion
status: Last Call
last-call-deadline: 2022-03-11
```

2022-02-23 01:04 UTC, fubuloubu commented
Ready for merging

2022-02-23 07:31 UTC, wschwab approved these changes

2022-02-25 22:35 UTC, sambacha commented
> Ready for merging

ser @lightclient bot is blocking pending your approval

2022-02-28 04:26 UTC, lightclient approved these changes
LGTM!

2022-02-28 16:15 UTC, merged