EIP-4760: SELFDESTRUCT bomb
ethereum/EIPs pull request #4760
Opened 2022-02-03 20:47 UTC by dankrad

Deactivate SELFDESTRUCT by changing it to SENDALL, which does recover all funds to the caller but does not delete any contract code or storage. In order to give applications good time to switch to new constructions, do this via a stage of exponential gas cost increases.

2022-02-10 06:00 UTC, MicahZoltu requested changes
Along with inline suggestions, this needs the following additional sections:
```
## Security Considerations
All EIPs must contain a section that discusses the security implications/considerations relevant to the proposed change. Include information that might be important for security discussions, surfaces risks and can be used throughout the life cycle of the proposal. E.g. include security-relevant design decisions, concerns, important discussions, implementation-specific guidance and pitfalls, an outline of threats and risks and how they are being addressed. EIP submissions missing the "Security Considerations" section will be rejected. An EIP cannot proceed to status "Final" without a Security Considerations discussion deemed sufficient by the reviewers.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).
```

2022-02-10 06:00 UTC, MicahZoltu commented on EIPS/eip-4760.md
> +Getting rid of the `SELFDESTRUCT` opcode has been considered in the past (for arguments see [here](https://hackmd.io/@vbuterin/selfdestruct)), and there are currently no strong reasons to use it. Dis
Remove external links.

This section should discuss why certain constants were chosen like 5000, 2**16, 13, etc.  The motivation section is the appropriate place to explain why this EIP in general is a good idea, Rationale is for explaining why specific decisions were made in this specification.

2022-02-10 06:00 UTC, MicahZoltu commented on EIPS/eip-4760.md
> +Few applications are affected by this change. The only use that breaks is where a contract is re-created at the same address using `CREATE2` (after a `SELFDESTRUCT`). An analysis of the contracts whe
```suggestion
Few applications are affected by this change. The only use that breaks is where a contract is re-created at the same address using `CREATE2` (after a `SELFDESTRUCT`). The only application that is significantly affected (and where code can be analyzed) is able to switch to a different model, and should have ample time to do so.
```

2022-03-04 14:31 UTC, gcolvin requested changes

2022-03-04 14:31 UTC, gcolvin commented on EIPS/eip-4760.md
> +The `SELFDESTRUCT` opcode requires large changes to the state of an account, in particular removing all code and storage. This will not be possible in the future with Verkle trees: Each account will
Alternatively, finish creating an actual Draft EIP (not just a HackMD) for the Verkle tree spec and add it the Requires list.

2022-03-04 14:42 UTC, gcolvin reviewed
Looks good except for external link issues.

2022-03-26 08:05 UTC, MicahZoltu approved these changes
Just need to pass CI, which requires shortening the description.

2022-03-26 08:05 UTC, MicahZoltu commented on EIPS/eip-4760.md
> +description: Deactivate SELFDESTRUCT by changing it to SENDALL, which does recover all funds to the caller but does not delete any contract code or storage. In order to give applications good time to
From CI:
> eip-4760.md:	description exceeds max length of 140 characters

Consider something like this instead?
```suggestion
description: Deactivate SELFDESTRUCT by changing it to SENDALL and stage this via a stage of exponential gas cost increases.
```

2022-03-26 09:09 UTC, merged