EIP-4400: Mark for review; Update motivation; Add implementation reference
ethereum/EIPs pull request #4785
Opened 2022-02-07 12:26 UTC by Daniel-K-Ivanov

Marking this EIP for review. Since the inception of this EIP, there have been 2 implementations and there was no feedback on changing the spec.

2022-02-10 15:16 UTC, lightclient requested changes

2022-02-10 15:16 UTC, lightclient commented on EIPS/eip-4400.md
> +Other implementations of the `Consumable` role:
Please remove this note to other implementations. EIPs are not an appropriate place to advertise projects.

2022-02-25 08:25 UTC, 5534vovan commented
> Marking this EIP for review. Since the inception of this EIP, there have been 2 implementations and there was no feedback on changing the spec.

2022-03-01 12:53 UTC, Daniel-K-Ivanov commented
@lightclient @axic friendly reminder for reviewing the PR 🙏

2022-03-10 09:44 UTC, 5534vovan approved these changes

2022-03-17 17:13 UTC, Bastek8 approved these changes

2022-03-21 18:53 UTC, lightclient approved these changes
LGTM

2022-03-22 08:43 UTC, merged

2022-03-31 21:42 UTC, Andrel2s commented
Go