[DRAFT] ERC-4911 Composability Extension For ERC-721 Standard
ethereum/EIPs pull request #4926
Opened 2022-03-16 23:18 UTC by muhammedea

An extension of the ERC-721 standard to enable NFT tokens to own other NFT tokens.

2022-03-16 23:23 UTC, DELJUJAZI approved these changes

2022-03-25 21:14 UTC, SamWilsn requested changes

2022-03-25 21:14 UTC, SamWilsn commented on EIPS/eip-4911.md
> +eip: 4911
```suggestion
eip: xxxx
```
An EIP number will be assigned when you move this PR out of draft. Unfortunately you can't pick a specific EIP number.

2022-03-25 21:14 UTC, SamWilsn commented on EIPS/eip-4911.md
> +This standard outlines a smart contract interface that should be applied to ERC721 contracts to add composability feature.
```suggestion
This standard outlines a smart contract interface that should be applied to [EIP-721](./EIP-721.md) contracts to add composability feature.
```

See [EIP-1 § Linking to other EIPs](https://eips.ethereum.org/EIPS/eip-1#linking-to-other-eips)

2022-03-25 21:14 UTC, SamWilsn commented on EIPS/eip-4911.md
> +# Composability Extension For ERC-721 Standard
```suggestion
```

The title will get added for you when the EIP is rendered.

2022-03-25 21:14 UTC, SamWilsn commented on EIPS/eip-4911.md
> +
You'll need to add the `Rationale` section.

2022-04-15 12:46 UTC, ed738 approved these changes

2022-05-13 12:43 UTC, Pandapip1 commented on EIPS/eip-4911.md
> +Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).
```suggestion
Copyright and related rights waived via [CC0](../LICENSE).
```

2022-09-01 01:35 UTC, Pandapip1 commented
@eth-bot rerun

2022-09-01 01:43 UTC, Pandapip1 commented
Closing since the author hasn't been seen in >3 months (the stale threshold).

2022-09-01 01:43 UTC, closed without merging