[DRAFT] ERC1155 Usage Rights Extension
ethereum/EIPs pull request #5006
Opened 2022-04-15 00:04 UTC by emojidao

This standard is an extension of ERC-1155. It proposes an additional role (user) which can be granted to addresses. The user role represents permission to "use" the NFT, but not be able to transfer it or set operators.

2022-04-20 19:53 UTC, Hbjjhbk commented
Spoko

2022-04-20 19:54 UTC, Hbjjhbk commented
Dzięki

2022-04-20 19:54 UTC, Hbjjhbk commented
Ok

2022-05-03 15:45 UTC, lightclient requested changes

2022-05-03 15:45 UTC, lightclient commented on EIPS/eip-5006.md
> +
```suggestion
```

2022-05-03 15:45 UTC, lightclient approved these changes

2022-05-05 07:57 UTC, 0xanders approved these changes

2022-05-06 05:41 UTC, merged