Make ERC1967 final as per the end of the last call period
ethereum/EIPs pull request #5035
Opened 2022-04-24 12:16 UTC by Amxx

2022-04-25 13:23 UTC, spalladino approved these changes

2022-04-30 17:04 UTC, SamWilsn requested changes
Please see https://github.com/ethereum/EIPs/pull/5061

2022-05-03 16:00 UTC, lightclient commented
New deadline is `2022-05-14`

2022-05-17 15:19 UTC, lightclient approved these changes
LGTN

2022-05-17 15:41 UTC, merged