EIP725 Standard Improvements
ethereum/EIPs pull request #5072
Opened 2022-05-05 10:38 UTC by YamenMerhi

## What does this PR introduce?
- Adding function signature for ERC725Y functions
- Add an example to use specific notations when calling ERC725Y overloaded functions
- Mark standard as Review instead of draft
- Change the terms keys and values to dataKeys and dataValues.
- Change the term key/value store to data key/value store. (Use key/value store instead of key-value store)
- Edit `Executed` event to use bytes4 instead of bytes

2022-05-09 11:16 UTC, frozeman approved these changes

2022-05-10 07:54 UTC, frozeman commented
@lightclient, @axic, @SamWilsn

2022-05-13 19:17 UTC, SamWilsn requested changes
Other required changes I can't comment directly on:
 - The "Rationale" section should describe individual choices made in this EIP. It currently sounds like it should be in the "Motivation" section, which describes the reason why the EIP as a whole is necessary.
 - You'll need to add a "Backwards Compatibility" section. Can be quite brief.
 - You'll need to add a "Security Considerations" section. Can be quite brief.
 - Rename the "Implementation" section to "Reference Implementation".
 - Remove all external links. You can include your implementation and documents with compatible licenses in the `../assets/eip-725` directory.

2022-05-13 19:17 UTC, SamWilsn commented on EIPS/eip-725.md
> +title: General data key/value store and execution standard
We're discouraging "standard" in titles and replaced "Simple Summary" with descriptions now:

```suggestion
title: General data key/value store and execution
description: An interface for a smart contract based account with attachable data key/value store
```

2022-05-13 19:17 UTC, SamWilsn commented on EIPS/eip-725.md
>  requires: 165, 173
```suggestion
category: ERC
created: 2017-10-02
requires: 165, 173
```

Header fields are out of order (and I can't grab the existing `created:` header in this suggestion :sweat_smile:)

2022-05-13 19:17 UTC, SamWilsn commented on EIPS/eip-725.md
```suggestion
```

2022-05-13 19:17 UTC, SamWilsn commented on EIPS/eip-725.md
> +A standard interface for a smart contract based account with attachable data key/value store.
```suggestion
```

2022-06-09 09:14 UTC, frozeman commented
@SamWilsn we will update the document with all requested changes. 

Though there is one that I do not agree with and thats the removal of all external links:

ERC725 is a base standard, that references other smart contract standards, that are not standardised here in the ERC repository. Specifically [LSPs, which are "LUKSO Standard Proposals"](https://github.com/lukso-network/LIPs/tree/main/LSPs).

The reason why they are not part of the ERC canon, is that the LSP standards are part of a larger set of core standards that are all interoperable and cohesive together. Nonetheless they do function equally for any EVM chain, the ability to make these standards understood requires a less noisy and neutral place, than the current ERC space (that I started). Therefore I deem a separate repo (LIPs/LSPs) as necessary for the success and transparency around these new sets of standards (many of which use ERC725Y as a core basis).

ERC725Y should reference [LSP-2](https://github.com/lukso-network/LIPs/blob/main/LSPs/LSP-2-ERC725YJSONSchema.md), which specifically defines a way of *how* ERC725Y data keys and values are encoded and decoded. As well as link to [LSP0 ERC725Account](https://github.com/lukso-network/LIPs/blob/main/LSPs/LSP-0-ERC725Account.md), which is the first proper followup standard of ERC725.

Additionally, the ERC725 alliance also maintains an updated implementation of the ERC725 standard, that needs to be referenced from the standard document for guidance. Additionally a basic implementation will be added to the `../assets/eip-725` as well.

2022-06-10 09:25 UTC, MicahZoltu commented
Why not write this as a LUKSO Standard instead of an Ethereum standard if it depends on LUKSO standards?

The reason we have a no external links policy is because of:
* mutability - EIPs are immutable once final, not everything on the web follows that
* simplicity - an EIP that links to a bunch of external resources is more complex than an EIP that doesn't
* limited editor bandwidth - we don't have enough editors to get into a deeply nuanced argument about every external link source that people want to reference.

2022-06-17 18:32 UTC, SamWilsn commented
I have to agree with @MicahZoltu here. We try to make it so EIPs can be implemented with only this repository. If you want, you could convert LSP0 and LSP2 to EIPs instead, and link to them that way?

2022-07-02 17:45 UTC, z0r0z commented
it seems helpful to reorder the preferred operations with logic of call, delegatecall, staticcall, create, create2? @frozeman 
compare,
![image](https://user-images.githubusercontent.com/92001561/177010981-87c165e9-9911-4fc4-a9ce-c1c923a82095.png)

2022-07-22 18:17 UTC, SamWilsn commented
Please take a look at the check results over here: https://github.com/ethereum/EIPs/runs/7369111505?check_suite_focus=true

You can use \`backticks\` around interface names (ex. \`IERC725Y\`) to get `eipw` to ignore them.

2022-09-01 01:42 UTC, Pandapip1 commented
Closing since the author hasn't been seen in >3 months (the stale threshold).

2022-09-01 01:42 UTC, closed without merging