Create EIP-5071 :  NFT Token Acceptance Standard
ethereum/EIPs pull request #5083
Opened 2022-05-08 05:30 UTC by mw2000

Created this PR to start an initial conversation if such an EIP would be useful to the community in general. Have built out the barebone structure of the EIP and will be adding more to it as I hear back from the community.

2022-05-09 05:51 UTC, MicahZoltu commented on EIPS/eip-5071.md
> +
Not a valid EIP section (anymore).  Please see https://raw.githubusercontent.com/ethereum/EIPs/master/eip-template.md for the proper current structure of an EIP.
```suggestion
```

2022-05-09 05:51 UTC, MicahZoltu commented on EIPS/eip-5071.md
> +requires: 165
```suggestion
requires: 165, 721, 1155, 2981
```

2022-05-09 05:52 UTC, MicahZoltu commented on EIPS/eip-5071.md
> +eip: 5071
```suggestion
eip: 5083
```

2022-05-09 05:53 UTC, MicahZoltu commented on EIPS/eip-5071.md
> +title: NFT Token Acceptance Standard
```suggestion
title: NFT Token Acceptance Standard
description: ...
```

2022-05-09 05:58 UTC, ShayneMichaelBacik1 approved these changes

2022-05-09 06:04 UTC, MicahZoltu commented on EIPS/eip-5071.md
> +author: Mihir Wadekar (@mw2000)
```suggestion
author: Mihir Wadekar (@mw2000)
discussions-to: <link to a forum thread on Ethereum Magicians>
```

2022-05-13 01:56 UTC, abcoathup commented
Can you update the title of the PR to match the designated EIP number, e.g. EIP5083

2022-05-13 01:56 UTC, abcoathup commented
Can you update the title of the PR to match the designated EIP number, e.g. EIP5083

2022-05-13 12:35 UTC, Pandapip1 commented on EIPS/eip-5071.md
> +Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).
```suggestion
Copyright and related rights waived via [CC0](../LICENCE).
```

2022-05-16 14:40 UTC, dtedesco1 commented on EIPS/eip-5071.md
> +Buy/Sell transactions for NFTs on marketplaces often happen in a standard currency like ETH. Certain NFT Collections may want to enable payments in specific ERC20 tokens only, howwever specifying thi
```suggestion
Buy/Sell transactions for NFTs on marketplaces often happen in a standard currency like ETH. Certain NFT Collections may want to enable payments in specific ERC20 tokens only, however specifying this on each and every NFT Marketplace is cumbersome and creates friction. Instead, this EIP proposes the creation of a standard interface to allow NFT marketplaces to easily obtain this information from the smart contract itself.
```

2022-07-15 16:47 UTC, Pandapip1 commented
@mw2000 Please push an empty commit so that the new CI can run.

2022-09-24 20:49 UTC, xinbenlv commented on EIPS/eip-5083.md
> +title: NFT Token Acceptance
Reading the title and description I feel the "token acceptance" is a bit ambiguous. Can you reduce the ambiguity in the title to match the description?

2022-09-29 11:47 UTC, Pandapip1 requested changes
Please fix all the CI errors

2022-11-26 00:17 UTC, closed without merging