Initial Commit
ethereum/EIPs pull request #5094
Opened 2022-05-13 21:56 UTC by lucemans

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

2022-05-14 22:53 UTC, lucemans commented
Preview visible at [https://eip5094.luc.page/](https://eip5094.luc.page/)

2022-05-16 06:49 UTC, MicahZoltu requested changes

2022-05-16 06:49 UTC, MicahZoltu commented on EIPS/eip-5094.md
> +
```suggestion
```
This is not a valid section.  Please inline references to relevant standards, and don't link externally.

2022-05-16 06:49 UTC, MicahZoltu commented on EIPS/eip-5094.md
> +
```suggestion
```
Simple Summary is no longer a valid section. See https://raw.githubusercontent.com/ethereum/EIPs/master/eip-template.md for current template.

2022-05-16 06:49 UTC, MicahZoltu commented on EIPS/eip-5094.md
> +title: URI Format for Ethereum Network Switching
```suggestion
title: URI Format for Ethereum Network Switching
description: A way of representing various network configurations as URLs.
```
Missing description header field (new, see template for details).

2022-05-16 06:49 UTC, MicahZoltu commented on EIPS/eip-5094.md
> +author: Luc van Kampen (@lucemans), Jakob Helgesson (@svemat01), Joshua Hendrix (@thejoshuahendrix)
```suggestion
author: Luc van Kampen (@lucemans), Jakob Helgesson (@svemat01), Joshua Hendrix (@thejoshuahendrix)
discussions-to: <link to thread on Ethereum Magicians forum>
```
Missing required header field.

2022-05-16 08:18 UTC, lucemans commented
All changes have been made, currently awaiting post approval for Ethereum Magicians

2022-05-17 13:08 UTC, lucemans commented
@MicahZoltu I have made the appropriate changes and updated the Ethereum  Magicians link! Let me know what's next!

2022-05-19 06:58 UTC, MicahZoltu commented
Next step is to wait for an ERC editor to review it.  My initial feedback was just a cursory glance to help speed things along, but not a full review.

2022-05-27 19:17 UTC, SamWilsn commented on EIPS/eip-5094.md
> +This standard includes all needed information for adding a network to a wallet via URL, by including parameters such as `chainId`, `rpc_url`, `chain_name` and others, such that the network configurat
The title uses `URI`, while the body uses `URL`. I'd suggest picking one for consistency.

2022-05-27 19:17 UTC, SamWilsn commented on EIPS/eip-5094.md
> +Although understandable, as the `chain_id` provided makes up only one part of what is required to connect to a network. This EIP aims to introduce a new type of URL for usage with deep-linking, QR, a
Weird sentence structure:

```suggestion
This is understandable, as the `chain_id` provided makes up only one part of what is required to connect to a network. This EIP aims to introduce a new type of URL for usage with deep-linking, QR, and more, to allow users to seamlessly add new networks to their (for ex. mobile) wallet to then be able to more easily partake in `pay-`, `tx-`, or other Ethereum URL interactions.
```

2022-05-27 19:17 UTC, SamWilsn commented on EIPS/eip-5094.md
> +Introduction of this EIP is ment to bridge to a safer rpc listing system to be introduced in the near future.
```suggestion
Introduction of this EIP is meant to bridge to a safer RPC listing system to be introduced in the near future.
```

2022-05-27 19:17 UTC, SamWilsn commented on EIPS/eip-5094.md
> +    erc831_part             = "ethereum:network-add"
I'd recommend splitting this into two parts so that it's more obvious that `add` is part of the ERC-831 `payload` (and not `prefix`.)

2022-05-28 18:03 UTC, lucemans commented
@SamWilsn I can't seem to be able to re-request review....
But just wanted to say that the changes have been made.

2022-05-29 07:08 UTC, MicahZoltu submitted a review, later dismissed

2022-05-31 15:20 UTC, lightclient approved these changes

2022-05-31 15:23 UTC, merged

2026-04-23 14:13 UTC, Villano18 reviewed
https://www.erc4337.io/docs