ERC4907： Change status to Last Call
ethereum/EIPs pull request #5098
Opened 2022-05-17 04:39 UTC by emojidao

Change status to Last Call

2022-05-17 04:42 UTC, 0xanders approved these changes

2022-05-17 15:24 UTC, lightclient requested changes
In "Backward Compatibility" please replace "ERC721" with "ERC-721". Looks good otherwise.

2022-05-18 16:45 UTC, ed738 approved these changes

2022-05-18 16:57 UTC, ed738 approved these changes

2022-05-25 16:57 UTC, 0xanders commented
Hi @lightclient  ,  I see this pr has been approved at [EIP editor apprenticeship meeting](https://github.com/ethereum-cat-herders/EIPIP/issues/135), could you pls approve this pr and set the last call date?

2022-05-26 13:29 UTC, MicahZoltu commented on EIPS/eip-4907.md
> +status: Last Call
```suggestion
status: Last Call
last-call-deadline: YYYY-MM-DD
```
This needs a last call deadline.  It should be *at least* 14 days in the future.  Due to editor response times being a bit slow for ERCs, I recommend setting it 3-4 weeks in the future so you don't run into problems.

2022-05-31 03:18 UTC, lightclient approved these changes

2022-05-31 06:46 UTC, MicahZoltu reviewed
````
run in Terminal：
```
truffle test ./test/test.js
```
````
the chances that this works at an undefined point in the future approach 0 as the distance between now and then approach infinity.  In other words, please remove this as it will almost certainly break, and doesn't provide significant value toward standardization.

2022-05-31 06:48 UTC, merged

2022-06-10 20:10 UTC, 0xGh commented
Hi there folks! I just learnt about this proposal and I wanted to chime in and ask what would be the best place to chat about design decisions eg. `user` vs `holder` or why `useOf` doesn't return a tuple or a struct

2022-06-11 09:37 UTC, MicahZoltu commented
> what would be the best place to chat about design decisions

The discussions-to link, which is in the header of the EIP: https://ethereum-magicians.org/t/idea-erc-721-user-and-expires-extension/8572