Finalize EIP-2364
ethereum/EIPs pull request #5121
Opened 2022-06-01 15:24 UTC by Pandapip1

CC: @karalabe, @timbeiko

Closes #2365

2022-06-01 16:38 UTC, timbeiko approved these changes

2022-06-04 06:05 UTC, MicahZoltu requested changes
> Additionally, `forkid` validation via the discovery protocol requires ENR implementation ([EIP-778](./eip-778.md)) and ENR extension support ([EIP-868](./eip-868.md)), which is not mandated by the Ethereum network currently. Lastly, the discovery protocol is just one way to find peers, but systems that cannot use UDP or that rely on other mechanism (e.g. DNS discovery ([EIP-1459](./eip-1459.md))) still need a way to filter connections.

EIP-1459 is still in review, not final, which means it is blocking this from being merged.  Since it is just used as an example, can we just remove it?

> Additionally, `forkid` validation via the discovery protocol requires ENR implementation ([EIP-778](./eip-778.md)) and ENR extension support ([EIP-868](./eip-868.md)), which is not mandated by the Ethereum network currently. Lastly, the discovery protocol is just one way to find peers, but systems that cannot use UDP or that rely on other mechanism (e.g. DNS discovery) still need a way to filter connections.

2022-06-05 05:27 UTC, MicahZoltu commented
@timbeiko Can you review/approve again?  The reference to EIP-1459 was removed and I would like to get author sign-off on that change before approving.

2022-06-06 21:15 UTC, timbeiko approved these changes

2022-06-07 06:47 UTC, MicahZoltu approved these changes

2022-06-07 07:14 UTC, merged