Include EIP-1271 as required
ethereum/EIPs pull request #5178
Opened 2022-06-24 06:41 UTC by TimDaub

- EIP-4494 currently makes no mention of EIP-1271 but I strongly assume that there is interest to support signature validation through a smart contract
- There are strong reasons to believe so as [@dievardump's reference implementation](https://github.com/dievardump/erc721-with-permits/blob/main/contracts/ERC721WithPermit.sol#L116) uses OZ's [`SignatureChecker` that in turn implements EIP-1271](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/cryptography/SignatureChecker.sol#L36)
- Unclear to me: Whether or not the authors of the EIP document want to further mention 1271. Anyways, at least I think it should be mentioned in the header as required.

2022-07-15 17:07 UTC, Pandapip1 commented
@MicahZoltu @lightclient could one of you manually merge this?

2022-07-16 11:45 UTC, MicahZoltu commented
We need to get approval from one of the authors before merging.  The author may prefer to remove the reference to 2098 to resolve that one, and they may not want to require 1271 for some reason.  We should not let 4494 go to review without resolving the 2098 issue though.

2022-07-25 19:19 UTC, TimDaub commented
@dievardump @wschwab ☝🏼

2022-09-17 18:52 UTC, wschwab commented
I don't see why 1271 or 2098 should be required. We have designed the EIP to be compatible with them, but at no point in the implementation are they required. Feel free to change my mind.

2022-09-19 00:30 UTC, Pandapip1 commented
> Feel free to change my mind.

It should be explicitly stated that they may be supported, then, because EIP-1271 is assumed to not be supported.

2022-09-19 14:42 UTC, TimDaub commented
> I don't see why 1271

fair.

> 2098 should be required

You mention EIP-2098 as also @dievardump points out, and it is how you format the signature as `bytes`, and in that case, IMO, it should be added to the requirements.

2022-09-20 09:27 UTC, TimDaub commented
> we point it out, but we never say that a 4494-compliant implementation MUST support either, imho a requirement should be something required, not something that was merely accommodated

fine. defining it like this can be a pro and a con.

Pro: if a better compact signature scheme arrives it may be usable

con: being loose can lead to undefined behavior.

I tend to prefer being very explicit and specific but it's ur guy's call, feel free to close

2022-09-24 21:16 UTC, xinbenlv commented on EIPS/eip-4494.md
> +description: ERC-712-singed approvals for EIP-721 NFTs
@Pandapip1 it seems a false positive warning for EIPW? My understanding is that preamble can't add Markdown Links.

2022-09-24 21:16 UTC, xinbenlv approved these changes

2022-10-02 12:35 UTC, Pandapip1 requested changes

2022-10-02 12:35 UTC, Pandapip1 commented on EIPS/eip-4494.md
> +description: ERC-712-singed approvals for EIP-721 NFTs
```suggestion
description: EIP-712-singed approvals for EIP-721 NFTs
```

2022-11-29 00:20 UTC, closed without merging