NFT Updatable Metadata Extension
ethereum/EIPs pull request #5185
Opened 2022-06-27 16:17 UTC by clbrge

This draft EIP adds an optional extension to ERC-721 or ERC-1155 interface to allow controlled metadata updates.

2022-06-27 16:25 UTC, clbrge commented
Let me know if you want me to change the number to 5185...

2022-06-28 00:38 UTC, aekzacx1997 approved these changes

2022-06-28 06:48 UTC, MicahZoltu reviewed
Security Considerations section is missing and required.

2022-06-28 06:48 UTC, MicahZoltu commented on EIPS/eip-draft_nft_updatable.md
> +eip: ????
```suggestion
eip: 5185
```
Don't forget to rename the file to `eip-5185.md` as well.

2022-06-28 06:48 UTC, MicahZoltu commented on EIPS/eip-draft_nft_updatable.md
> +
This is not a valid EIP section.  Please move this content as a subsection of a section defined in https://raw.githubusercontent.com/ethereum/EIPs/master/eip-template.md

2022-06-28 06:48 UTC, MicahZoltu commented on EIPS/eip-draft_nft_updatable.md
> +
This is not a valid EIP section. Please move this content as a subsection of a section defined in https://raw.githubusercontent.com/ethereum/EIPs/master/eip-template.md

2022-06-28 06:48 UTC, MicahZoltu commented on EIPS/eip-draft_nft_updatable.md
> +
This is not a valid EIP section. Please move this content as a subsection of a section defined in https://raw.githubusercontent.com/ethereum/EIPs/master/eip-template.md

2022-06-28 11:20 UTC, Pandapip1 requested changes

2022-06-28 11:20 UTC, Pandapip1 commented on EIPS/eip-5185.md
> +This specification defines a standard way to allow controlled NFTs' metadata updates along predefined formulas. Updates of the original metadata are restricted and defined by a set of recipes and the
```suggestion
This specification defines a standard way to allow controlled NFTs' metadata updates along predefined formulas. Updates of the original metadata are restricted and defined by a set of recipes and the sequence and results of these recipes are deterministic and fully verifiable with on-chain metadata updates event. The proposal depends on and extends the [EIP-721](./eip-721.md) and [EIP-1155](./eip-1155.md).
```

2022-06-28 11:20 UTC, Pandapip1 commented on EIPS/eip-5185.md
> +The **metadata updates extension** is OPTIONAL for [ERC-721](./eip-721.md) and [ERC-1155](./eip-1155.md) contracts.
```suggestion
The **metadata updates extension** is OPTIONAL for [EIP-721](./eip-721.md) and [EIP-1155](./eip-1155.md) contracts.
```

2022-06-28 11:20 UTC, Pandapip1 commented on EIPS/eip-5185.md
> +There have been numerous interesting uses of ERC-721 and ERC-1155 smart contracts that associate for each token essential and significant metadata. While some projects (e.g. EtherOrcs) have experimen
```suggestion
There have been numerous interesting uses of [EIP-721](./eip-721.md) and [EIP-1155](./eip-1155.md) smart contracts that associate for each token essential and significant metadata. While some projects (e.g. EtherOrcs) have experimented successfully to manage these metadata on-chain, that experimental solution will always be limited by the cost and speed of generating and storing JSON on-chain. Symmetrically, while storing the JSON metadata at URI endpoint controlled by traditional servers permit limitless updates the the metadata for each NFT, it is somehow defeating in many uses cases, the whole purpose of using a trustless blockchain to manage NFT: indeed users may want or demand more permanence and immutability from the metadata associated with their NFT.
```
Nit

2022-06-28 11:20 UTC, Pandapip1 commented on EIPS/eip-5185.md
> +The original metadata for a given NFT is always defined as the JSON pointed by the result of `tokenURI` for ERC-721 and function `uri` for ERC-1155.
```suggestion
The original metadata for a given NFT is always defined as the JSON pointed by the result of `tokenURI` for [EIP-721](./eip-721.md) and function `uri` for [EIP-1155](./eip-1155.md).
```
Nit

2022-06-28 11:20 UTC, Pandapip1 commented on EIPS/eip-5185.md
> +The proposal is fully compatible with both ERC-721 and ERC-1155. Third party applications that don't support Updatable Metadata Extension will still be able to use the original metadata for each NFT.
```suggestion
The proposal is fully compatible with both [EIP-721](./eip-721.md) and [EIP-1155](./eip-1155.md). Third-party applications that don't support this EIP will still be able to use the original metadata for each NFT.
```
Nit(s)

2022-06-28 11:20 UTC, Pandapip1 commented on EIPS/eip-5185.md
> +
```suggestion
```

2022-07-04 03:14 UTC, lightclient approved these changes

2022-07-04 03:26 UTC, merged