move eip-2612 to Last Call
ethereum/EIPs pull request #5196
Opened 2022-07-02 23:49 UTC by z0r0z

eip-2612 has been discussed for 2 years and seen wide implementation in production ([uniswapV2](https://github.com/Uniswap/v2-core/blob/master/contracts/UniswapV2ERC20.sol)) and in contract libraries like [openzeppelin](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/extensions/draft-ERC20Permit.sol) and [solmate](https://github.com/Rari-Capital/solmate/blob/main/src/tokens/ERC20.sol). It seems time to finalize and move this as a standard extension for erc20 fungible tokens.

2022-07-03 03:16 UTC, lightclient approved these changes

2022-07-03 03:42 UTC, SamWilsn requested changes
```
error[markdown-rel-links]: non-relative link or image
  --> /tmp/eip-2612.md
   |
27 | While ERC-20 tokens have become ubiquitous in the Ethereum ecosystem, their status remains that of second class tokens from the perspective of the protocol. The ability for users to interact with Ethereum without holding any ETH has been a [long outstanding goal](./eip-101.md) and the [subject](./eip-1077.md) [of](./eip-777.md) [many](https://github.com/ethereum/EIPs/issues/1776) [EIPs](./eip-1271.md).
   |
error[markdown-rel-links]: non-relative link or image
  --> /tmp/eip-2612.md
   |
29 | So far, many of these proposals have seen very little adoption, and the ones that have been adopted (such as [ERC-777](./eip-777.md)), introduce a lot of additional functionality, causing [unexpected behavior in mainstream contracts](https://medium.com/consensys-diligence/uniswap-audit-b90335ac007).
   |
error[markdown-rel-links]: non-relative link or image
   --> /tmp/eip-2612.md
    |
154 | The `permit` function is sufficient for enabling any operation involving ERC-20 tokens to be paid for using the token itself, rather than using ETH. 
    |
error[markdown-rel-links]: non-relative link or image
   --> /tmp/eip-2612.md
    |
173 | There is also an implementation in the token [`Stake`](https://etherscan.io/address/0x0Ae055097C6d159879521C384F1D2123D1f195e6#code) with the same ABI as `dai` but with different semantics: it lets users issue "expiring approvals", that only allow `transferFrom` to occur while `expiry >= block.timestamp`.
    |
error[markdown-rel-links]: non-relative link or image
   --> /tmp/eip-2612.md
    |
175 | The specification presented here is in line with the implementation in [Uniswap-v2](https://github.com/uniswap/uniswap-v2-core).
    |
error[markdown-rel-links]: non-relative link or image
   --> /tmp/eip-2612.md
    |
184 | [UniswapV2ERC20.sol](https://github.com/Uniswap/uniswap-v2-core/blob/master/contracts/UniswapV2ERC20.sol)
    |
error[markdown-rel-links]: non-relative link or image
   --> /tmp/eip-2612.md
    |
194 | The standard [ERC-20 race condition for approvals](https://swcregistry.io/docs/SWC-114) applies to `permit` as well.
    |
```

2022-07-15 17:08 UTC, Pandapip1 commented
@z0r0z please push an empty commit.

2022-08-15 09:27 UTC, MrChico approved these changes

2022-08-15 17:33 UTC, Pandapip1 requested changes
![image](https://user-images.githubusercontent.com/45835846/184685867-471e2f7f-313c-44d3-bbf5-2a97c906d3ec.png)

2022-08-16 03:59 UTC, xinbenlv commented on EIPS/eip-2612.md
>  created: 2020-04-13
Just to confirm, is it the author's intention to *not* follow EIP-165? I believe it's the author's judgement call but just to make sure it's a conscious decision.

2022-09-01 01:51 UTC, Pandapip1 commented
Superseded by #5506

2022-09-01 01:51 UTC, closed without merging