Update eip-4972.md
ethereum/EIPs pull request #5248
Opened 2022-07-13 20:29 UTC by qizhou

Change status from draft to review

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

2022-07-14 14:14 UTC, Pandapip1 reviewed
The following is a change I feel needs to be made:

1. For `IERC721NOA`, **specify what happens when someone calls `ownerOf` on a `tokenId` that is owned by an NOA.** Should it throw? Return the zero address? This is ambiguous right now.

Here are some suggestions for other changes that I feel the standard is lacking:

3. Add methods to `IERC721NOA` and `IERC20NOA` that allow users to transfer tokens *to* NOAs, and get the balance of NOAs.
4. Add an NOA extension for EIP-1155.

2022-07-18 18:11 UTC, qizhou commented
> The following is a change I feel needs to be made:
> 
> 1. For `IERC721NOA`, **specify what happens when someone calls `ownerOf` on a `tokenId` that is owned by an NOA.** Should it throw? Return the zero address? This is ambiguous right now.
> 
> Here are some suggestions for other changes that I feel the standard is lacking:
> 
> 2. Add methods to `IERC721NOA` and `IERC20NOA` that allow users to transfer tokens _to_ NOAs, and get the balance of NOAs.
> 3. Add an NOA extension for EIP-1155. This is slightly less commonly used as EIP-721, but is common enough that it deserves to be included IMO.

Many thanks for the comments.  We are working on the comments and will update the PR shortly.

2022-07-18 18:22 UTC, SamWilsn commented
Would you mind also rebasing on top of `master`? The GitHub workflow file in this branch is out of date (and is missing some checks.)

2022-07-18 19:12 UTC, qizhou commented
> Would you mind also rebasing on top of `master`? The GitHub workflow file in this branch is out of date (and is missing some checks.)

Done.  Thanks for the suggestion.

2022-07-22 16:41 UTC, Pandapip1 commented
The eipw errors need to be fixed.

2022-07-23 17:47 UTC, qizhou commented
> The following is a change I feel needs to be made:
> 
> 1. For `IERC721NOA`, **specify what happens when someone calls `ownerOf` on a `tokenId` that is owned by an NOA.** Should it throw? Return the zero address? This is ambiguous right now.

Thanks for the comment.  The  `ownerOf` method will return a name-derived address (NDA, also 20 bytes EH address).  The NDA can be obtained by calling `addressOfName` method.

> 
> Here are some suggestions for other changes that I feel the standard is lacking:
> 
> 2. Add methods to `IERC721NOA` and `IERC20NOA` that allow users to transfer tokens _to_ NOAs, and get the balance of NOAs.

Thanks for the comment.  Currently, it can be done by transferring tokens to NDAs (and getting the balances from the NDAs)

> 3. Add an NOA extension for EIP-1155. This is slightly less commonly used as EIP-721, but is common enough that it deserves to be included IMO.
Thanks for the comment. The extension for EIP-11155 is added.  Please take a look.

2022-07-29 21:37 UTC, SamWilsn reviewed
Couple other notes I can't directly comment on:
 - Since a NOA is a contract, technically its a subtype of a contract account (as opposed to alongside as specified in the abstract.)

2022-08-01 04:35 UTC, qizhou commented
> Couple other notes I can't directly comment on:
> 
> * Since a NOA is a contract, technically its a subtype of a contract account (as opposed to alongside as specified in the abstract.)

Thanks for the comment.  The NOA is not a contract, but an account, whose owner is managed by a name service. Further, we use `address(nameStringWithNSSuffix)` as the name-derived address so that we can lookup the operators/owners of the address.  Note that the address cannot be directly used by an external account or a contract in Ethereum - it can be only used by operators (as managed NS) via `transferFrom` type of transactions. Hope this can explain it.  Please let me know if you have further comments!

2022-08-01 04:41 UTC, qizhou commented on EIPS/eip-4972.md
> +#### IEIP-721NOA
Thanks for the comment.  Update the PR accordingly.

2022-08-03 16:35 UTC, Pandapip1 requested changes

2022-08-03 16:35 UTC, Pandapip1 commented on EIPS/eip-4972.md
> +Given an NDA, we need to lookup the owner from a name service and compare it with the message sender. Note that current ENS only supports namehash (32 bytes) to owner translation, and thus we may nee
```suggestion

Given an NDA, we need to look up the owner from a name service and compare it with the message sender. Note that currently, ENS only supports namehash (32 bytes) to owner translation, and thus we may need an additional helper contract to map an NDA to a namehash for ENS.
```

2022-08-03 16:35 UTC, Pandapip1 commented on EIPS/eip-4972.md
>  No security considerations were found.
```suggestion

No security considerations were found.
```

2022-08-03 16:35 UTC, Pandapip1 commented on EIPS/eip-4972.md
>  The new account type is compatible with existing ERC token standards.
```suggestion

The new account type is compatible with existing ERC token standards.
```

2022-08-03 16:35 UTC, Pandapip1 commented on EIPS/eip-4972.md
> +Each token contract can decide how to encode the name to an NDA as long as the address space of NDAs does not overlap with existing EOA/CA spaces. We can follow the similar rule of CREATE2 opcode to
```suggestion

Each token contract can decide how to encode the name to an NDA as long as the address space of NDAs does not overlap with existing EOA/CA spaces. We can follow the similar rule of CREATE2 opcode to compute the NDA from a name service and the hash of a username as 
```

2022-08-03 16:35 UTC, Pandapip1 commented on EIPS/eip-4972.md
> +address(keccak256(0xff, keccak256(“eip-4972.addressOfName”), nameServiceAddress, keccak256(username))).
```suggestion
address(keccak256(0xff, keccak256("eip-4972.addressOfName"), nameServiceAddress, keccak256(username))).
```

2022-08-03 16:35 UTC, Pandapip1 commented on EIPS/eip-4972.md
> +#### `IERC721NOA`
```suggestion
#### `IERC721NOA`

```

2022-08-03 16:35 UTC, Pandapip1 commented on EIPS/eip-4972.md
> +```
```suggestion
```solidity
```

2022-08-03 16:35 UTC, Pandapip1 commented on EIPS/eip-4972.md
> +```
```suggestion
```solidity
```

2022-08-03 16:35 UTC, Pandapip1 commented on EIPS/eip-4972.md
>  ```
```suggestion
```solidity
```

2022-08-03 16:35 UTC, Pandapip1 commented on EIPS/eip-4972.md
>  ```
```suggestion
```solidity
```

2022-08-03 16:35 UTC, Pandapip1 commented on EIPS/eip-4972.md
>  ## Reference Implementation
```suggestion
## Reference Implementation

```

2022-08-03 16:35 UTC, Pandapip1 commented on EIPS/eip-4972.md
> +### Name Derived Address (INameOwnedAccount.addressOfName())
```suggestion
### Name Derived Address (INameOwnedAccount.addressOfName())

```

2022-08-03 16:35 UTC, Pandapip1 commented on EIPS/eip-4972.md
> +```
```suggestion
```solidity
```

2022-08-03 16:35 UTC, Pandapip1 commented on EIPS/eip-4972.md
> +#### `IERC20NOA`
```suggestion
#### `IERC20NOA`

```

2022-08-03 16:35 UTC, Pandapip1 commented on EIPS/eip-4972.md
> +```
```suggestion
```solidity
```

2022-08-03 16:35 UTC, Pandapip1 commented on EIPS/eip-4972.md
> +```
```suggestion
```solidity
```

2022-08-03 16:35 UTC, Pandapip1 commented on EIPS/eip-4972.md
> +```
```suggestion
```solidity
```

2022-08-03 16:35 UTC, Pandapip1 commented on EIPS/eip-4972.md
> +## Rationale
```suggestion
## Rationale

```

2022-08-03 16:35 UTC, Pandapip1 commented on EIPS/eip-4972.md
>  ### Name Representation
```suggestion
### Name Representation

```

2022-08-03 16:35 UTC, Pandapip1 commented on EIPS/eip-4972.md
>  ### Interface
```suggestion
### Interface

```

2022-08-03 16:35 UTC, Pandapip1 commented on EIPS/eip-4972.md
>  #### INameOwnedAccount
```suggestion
#### INameOwnedAccount

```

2022-08-03 16:35 UTC, Pandapip1 commented on EIPS/eip-4972.md
> +```
```suggestion
```solidity
```

2022-08-03 16:35 UTC, Pandapip1 commented on EIPS/eip-4972.md
> +```
```suggestion
```solidity
```

2022-08-03 16:35 UTC, Pandapip1 commented on EIPS/eip-4972.md
> +```
```suggestion
```solidity
```

2022-08-03 16:35 UTC, Pandapip1 commented on EIPS/eip-4972.md
> +```
```suggestion
```solidity
```

2022-08-04 22:59 UTC, qizhou commented
Many thanks for the comments @Pandapip1 .  We are working on some issues found by the draft, and we will update a final one for review shortly.

2022-08-28 18:55 UTC, Pandapip1 requested changes
Please fix the merge conflicts

2022-09-24 22:01 UTC, xinbenlv approved these changes

2022-09-27 12:56 UTC, Pandapip1 commented
@qizhou please resolve the merge conflicts

2022-09-28 18:20 UTC, qizhou commented
> @qizhou please resolve the merge conflicts

Thanks for rebasing with some latest changes.

2022-09-28 18:33 UTC, qizhou commented
After discussing with the team, we will withdraw the version from "review" since there are a couple of major concerns.  We are focusing on polishing EIP-4972 and will create another PR once it is ready.  Many thanks for the comments and suggestions @Pandapip1 @SamWilsn @xinbenlv

2022-09-28 18:33 UTC, closed without merging