EIP-2200: Change unordered list to ordered
ethereum/EIPs pull request #5419
Opened 2022-08-05 11:23 UTC by chfast

In the specification of EIP-2200 change the format of the list from
unordered to order. This way a particular rule can be referenced from
outside by e.g. "4.1.2".

2022-08-05 15:57 UTC, Pandapip1 requested changes
Fix the EIPW errors

2022-08-05 17:42 UTC, chfast commented
> Fix the EIPW errors

Not my errors.

2022-08-06 01:32 UTC, Pandapip1 commented
They need to be fixed in order for this PR to be merged.

2022-08-09 15:22 UTC, SamWilsn commented
Since this EIP is final, I think we should avoid changes.

2022-08-09 15:22 UTC, closed without merging

2022-08-10 13:34 UTC, chfast commented
I think you are right, people should be able to count to 3 in head. https://github.com/ethereum/evmc/pull/661

2022-08-12 18:19 UTC, chfast commented
Here is EVMC's copy of the specification with clauses numbered. https://evmc.ethereum.org/storagestatus.html