Update eip-3561.md
ethereum/EIPs pull request #5427
Opened 2022-08-08 05:34 UTC by SamPorter1984

Shorter, clearer. Slightly better rationale. Updated implementation link.

2022-08-08 14:28 UTC, Pandapip1 submitted a review, later dismissed
Please update the status to review and fix the EIP-Bot errors.

2022-08-09 15:19 UTC, SamWilsn requested changes
This EIP is in the Stagnant state, so you'll have to move it back into an active state before you can make changes.

Also, please see the errors in the Checks section. You'll need to fix those too.

Thanks!

2022-08-30 09:15 UTC, SamPorter1984 commented
Bot checks passed
And uh, fulfilled your requests
Also, changed the specification a bit, moved away from trust minimized boolean, to a more concise and logical zero trust period, which effectively makes the code multi-chain.
If ever etherscan and it's forks will not only check proxy slots, but also code validity of a proxy, this one is ready.

2022-08-30 14:03 UTC, Pandapip1 approved these changes

2022-08-30 14:08 UTC, merged