Fixed typos in 4907
ethereum/EIPs pull request #5435
Opened 2022-08-09 14:49 UTC by 0fatih

2022-08-09 18:07 UTC, Pandapip1 commented
eipw errors need to be fixed

2022-08-10 14:14 UTC, 0xanders submitted a review, later dismissed

2022-08-14 09:33 UTC, 0fatih commented
@Pandapip1 Bot complains about the title:

```
3 | title: Rental NFT, ERC-721 User And Expires Extension
  |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ too long
```

I didn't even touch the title. Should I change it?

2022-08-14 09:48 UTC, 0xanders commented
Suggest  change the title to : Rental NFT, An Extension of EIP-721

2022-08-14 11:09 UTC, 0fatih commented
Are these requirements new?

```
Error: proposals must be referenced with the form `EIP-N` (not `ERC-N`)
Error: proposals must be referenced with the form `EIP-N` (not `ERC-N`)
Error: proposals must be referenced with the form `EIP-N` (not `ERC-N`)
Error: proposals must be referenced with the form `EIP-N` (not `ERC-N`)
Error: proposals must be referenced with the form `EIP-N` (not `ERC-N`)
Error: proposals must be referenced with the form `EIP-N` (not `ERC-N`)
Error: proposals must be referenced with the form `EIP-N` (not `ERC-N`)
Error: proposals must be referenced with the form `EIP-N` (not `ERC-N`)
Error: validation found errors :(
```
Guys this is my first PR to EIPs. I wanted to start with the basics (typos). What is going on? What should I do?

2022-08-14 11:47 UTC, Pandapip1 commented
Yes, those are requirements. Just replace all instances of `ERC-X` with `EIP-X`.

2022-08-14 11:49 UTC, Pandapip1 commented on EIPS/eip-4907.md
> +title: Rental NFT, an Extension of EIP-721
```suggestion
title: Rental Extension of EIP-721
```

2022-08-14 11:55 UTC, 0xanders requested changes
line 4:  change ERC-721 to EIP-721

line 31: add \` to  [IERC4907.sol] ,  [`IERC4907.sol`]

line 90: change ERC-721 to EIP-721

line 92: change ERC-721 to EIP-721

line 97: add \` to  [ERC4907Demo.sol] ,  [`ERC4907Demo.sol`]

line 167: add \` to  [ERC4907.sol] ,  [`ERC4907.sol`]

2022-08-14 11:55 UTC, 0xanders commented on EIPS/eip-4907.md
>  description: Add a time-limited role with restricted permissions to ERC-721 tokens.
description: Add a time-limited role with restricted permissions to EIP-721 tokens.

2022-08-14 12:03 UTC, 0xanders commented
IERC4907.sol, ERC4907.sol , ERC4907Demo.sol are file names,  you can add \` to them , such as [`IERC4907.sol`]

2022-08-14 12:10 UTC, 0xanders requested changes

2022-08-14 12:10 UTC, 0xanders commented on EIPS/eip-4907.md
> +EIP4907Demo Implementation: [EIP4907Demo.sol](../assets/eip-4907/contracts/ERC4907Demo.sol)
`ERC4907Demo` Implementation: [`ERC4907Demo.sol`](../assets/eip-4907/contracts/ERC4907Demo.sol)

2022-08-14 12:10 UTC, 0xanders commented on EIPS/eip-4907.md
> +EIP4907 Implementation: [ERC4907.sol](../assets/eip-4907/contracts/ERC4907.sol)
EIP-4907 Implementation: [`ERC4907.sol`](../assets/eip-4907/contracts/ERC4907.sol)

2022-08-14 12:14 UTC, 0xanders requested changes

2022-08-14 12:14 UTC, 0xanders commented on EIPS/eip-4907.md
> +EIP-4907 Implementation: [`ERC4907.sol`](../assets/eip-4907/contracts/ERC4907.sol)
Implementation: [`ERC4907.sol`](../assets/eip-4907/contracts/ERC4907.sol)

2022-08-14 12:14 UTC, 0xanders commented on EIPS/eip-4907.md
> +EIP-4907Demo Implementation: [`EIP4907Demo.sol`](../assets/eip-4907/contracts/ERC4907Demo.sol)
Test contract implementation: [`ERC4907Demo.sol`](../assets/eip-4907/contracts/ERC4907Demo.sol)

2022-08-14 15:28 UTC, 0xanders approved these changes

2022-08-14 17:23 UTC, Pandapip1 requested changes

2022-08-14 17:23 UTC, Pandapip1 commented on EIPS/eip-4907.md
> +`EIP-4907Demo` Implementation: [`EIP4907Demo.sol`](../assets/eip-4907/contracts/ERC4907Demo.sol)
```suggestion
`ERC4907Demo` Implementation: [`ERC4907Demo.sol`](../assets/eip-4907/contracts/ERC4907Demo.sol)
```

2022-08-14 17:23 UTC, Pandapip1 commented on EIPS/eip-4907.md
> +`EIP-4907` Implementation: [`ERC4907.sol`](../assets/eip-4907/contracts/ERC4907.sol)
```suggestion
Implementation: [`ERC4907.sol`](../assets/eip-4907/contracts/ERC4907.sol)
```
Avoid self-references where possible.

2022-08-15 18:27 UTC, Pandapip1 submitted a review, later dismissed

2022-08-15 18:28 UTC, Pandapip1 commented
Needs approval by @0xanders, or @LanceSnow

2022-08-16 02:27 UTC, 0xanders commented on EIPS/eip-4907.md
> +Solidity Interface with NatSpec & OpenZeppelin v4 Interfaces (also available at [`IEIP4907.sol`](../assets/eip-4907/contracts/IERC4907.sol)):
line31:  change  `IEIP4907.sol`  to `IERC4907.sol`

2022-08-16 02:29 UTC, 0xanders commented on EIPS/eip-4907.md
> +`EIP-4907Demo` Implementation: [`EIP4907Demo.sol`](../assets/eip-4907/contracts/ERC4907Demo.sol)
line97:  change  `IEIP4907Demo.sol`  to `ERC4907Demo.sol`

2022-08-16 09:39 UTC, 0xanders submitted a review, later dismissed

2022-08-16 13:32 UTC, Pandapip1 commented on EIPS/eip-4907.md
> +`EIP-4907Demo` Implementation: [`ERC4907Demo.sol`](../assets/eip-4907/contracts/ERC4907Demo.sol)
```suggestion
`ERC4907Demo` Implementation: [`ERC4907Demo.sol`](../assets/eip-4907/contracts/ERC4907Demo.sol)
```

2022-08-16 21:28 UTC, Pandapip1 approved these changes

2022-08-28 15:41 UTC, 0xanders approved these changes

2022-08-28 15:42 UTC, merged