Move EIP-2330 to Draft status
ethereum/EIPs pull request #5436
Opened 2022-08-10 04:31 UTC by zemse

- Update gas costs.
- Add EIP-2929 access list warm/cold address/slot.
- Make changes required to pass EIP Validator checks e.g. add missing fields, remove external links, etc.

cc: @dominicletz @spalladino

2022-08-10 10:19 UTC, dominicletz approved these changes

2022-08-10 17:01 UTC, Pandapip1 requested changes

2022-08-10 17:01 UTC, Pandapip1 commented on EIPS/eip-2330.md
>  ```
```suggestion
```shell
```

2022-08-11 15:10 UTC, skaille approved these changes

2022-08-12 01:04 UTC, Pandapip1 approved these changes
I think this looks fine for a draft.

2022-08-12 01:05 UTC, Pandapip1 commented
cc: @dominicletz @spalladino re-approval necessary.

2022-08-12 10:02 UTC, dominicletz approved these changes

2022-08-12 10:03 UTC, merged