Add EIP-xxxx: EOF - Stack Validation
ethereum/EIPs pull request #5450
Opened 2022-08-12 16:14 UTC by gumb0

2022-08-12 19:37 UTC, Pandapip1 commented on EIPS/eip-xxxx.md
> +eip: xxxx
```suggestion
eip: 5450
```

2022-08-12 19:39 UTC, Pandapip1 reviewed
There are a few too many placeholders right now. Please either fill in a bit of the motivation or replace it entirely with a `TBA`

2022-08-12 19:39 UTC, Pandapip1 commented on EIPS/eip-xxxx.md
> +discussions-to:
Must be thread on ethereum magicians

2022-08-12 19:39 UTC, Pandapip1 commented on EIPS/eip-xxxx.md
> +## Reference Implementation
Should be after backwards compatibility

2022-08-12 19:39 UTC, Pandapip1 commented on EIPS/eip-xxxx.md
> +TBA
```suggestion
Needs discussion.
```
Personal preference for this section over TBA or TBD.

2022-08-12 19:39 UTC, Pandapip1 commented on EIPS/eip-xxxx.md
> +Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).
```suggestion
Copyright and related rights waived via [CC0](../LICENSE.md).
```

2022-08-12 19:39 UTC, Pandapip1 commented on EIPS/eip-xxxx.md
> +
```suggestion

TBA

```

2022-08-12 19:39 UTC, Pandapip1 commented on EIPS/eip-xxxx.md
> +### Clean stack upon termination
```suggestion
### Clean stack upon termination

TBA

```

2022-08-17 09:53 UTC, gumb0 commented on EIPS/eip-xxxx.md
> +
Replaced entire Rationale contents with TBA for now.

2022-08-19 16:56 UTC, Pandapip1 requested changes

2022-08-19 16:56 UTC, Pandapip1 commented on EIPS/eip-5450.md
> +This change poses no risk to backwards compatibility, as it is introduced only for EOF1 contracts, for which deploying undefined instructions is not allowed, therefore there are no existing contracts
Note: mention that this requires a hard fork

2022-08-19 16:56 UTC, Pandapip1 commented on EIPS/eip-5450.md
> +TBA
```suggestion
Needs discussion
```

2022-08-19 17:22 UTC, gumb0 commented on EIPS/eip-5450.md
> +TBA
Changed.

2022-08-19 17:22 UTC, gumb0 commented on EIPS/eip-5450.md
> +This change poses no risk to backwards compatibility, as it is introduced only for EOF1 contracts, for which deploying undefined instructions is not allowed, therefore there are no existing contracts
Added.

2022-08-19 20:31 UTC, Pandapip1 approved these changes
Seems to meet the basic requirements for a draft.

2022-08-19 20:32 UTC, merged