EIP-1: propose to adopt RFC 8174 (updates 2119)
ethereum/EIPs pull request #5466
Opened 2022-08-16 14:34 UTC by xinbenlv

RFC 2119 is updated by 8174. Have we discussed whether or not to adopt 8174?

2022-08-16 16:18 UTC, Pandapip1 commented
The EIP template should be updated if this change is made.

2022-08-18 00:00 UTC, xinbenlv commented
1. Request to remove label `waiting: EIP number`
2. Request for review and merge

2022-08-18 00:55 UTC, Pandapip1 commented
> Request to remove label waiting: EIP number

Can't do it, it's automated. We're working on a fix.

> Request for review and merge

:+1:

2022-08-19 04:23 UTC, xinbenlv commented
If there is no objection, and we have not fixed the bot yet, I'd suggest a manual merge so new EIPs can start using RFC 8174

2022-08-19 12:20 UTC, Pandapip1 requested changes

2022-08-19 12:20 UTC, Pandapip1 commented on EIPS/eip-1.md
> +   appear in all capitals, as shown here.
```suggestion
> The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in [RFC 2119](https://www.ietf.org/rfc/rfc2119.html) and [RFC 8174](https://www.ietf.org/rfc/rfc8174.html).
```

2022-08-19 12:20 UTC, Pandapip1 commented on eip-template.md
> +when, and only when, they appear in all capitals, as shown here.
```suggestion
The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in [RFC 2119](https://www.ietf.org/rfc/rfc2119.html) and [RFC 8174](https://www.ietf.org/rfc/rfc8174.html).
```

2022-08-19 12:34 UTC, Pandapip1 approved these changes
LGTM.

2022-09-02 21:35 UTC, SamWilsn submitted a review, later dismissed

2022-09-05 17:20 UTC, xinbenlv commented
@eth-bot please merge

2022-09-06 15:25 UTC, SamWilsn commented
I think we're just waiting on three more approvals.

2022-09-06 15:27 UTC, xinbenlv commented
Oh, I see, it was not obvious to me as it shows 

<img width="919" alt="2022-09-06_11-26-32" src="https://user-images.githubusercontent.com/640325/188674859-5afdb348-d2d6-4d09-b3eb-eb74fbf5d5d0.png">

2022-09-06 15:47 UTC, lightclient commented
Is there a reason you don't update the actual RFC number in the anchor?

2022-09-06 16:26 UTC, gcolvin commented
I'm generally OK with this, but if would cause a less clutter as a footnote.   I'd be even happier to make this a general policy that applies to all EIPs, and doesn't need to be repeated in every one of them.

2022-09-06 17:13 UTC, Pandapip1 commented
> I'd be even happier to make this a general policy that applies to all EIPs, and doesn't need to be repeated in every one of them.

Let's do the less restrictive version first. I'm also in favor of this, but in the interest of moving *something* forward let's get this merged first.

2022-09-06 18:19 UTC, gcolvin commented
> > I'd be even happier to make this a general policy that applies to all EIPs, and doesn't need to be repeated in every one of them.
> 
> Let's do the less restrictive version first. I'm also in favor of this, but in the interest of moving _something_ forward let's get this merged first.

Can we at least move it to an endnote?  It's just clutter when dropped into the middle of the most important part of an EIP.

2022-09-06 19:21 UTC, xinbenlv commented
> Is there a reason you don't update the actual RFC number in the anchor?

Which anchor? Could you share the screenshot of what you refer to?

2022-09-06 19:24 UTC, xinbenlv commented
> Can we at least move it to an endnote? It's just clutter when dropped into the middle of the most important part of an EIP.

@gcolvin 
I agree with you. I am just not sure markdown syntax supports endnote as well as LaTex etc. Would it be ok to you if I update it in a followup commit? We can update the policy in EIP-1 first. In a follow up commit we can address the formatting of endnote or footnote in the `eip-template.md`, I am assuming?

2022-09-16 16:28 UTC, SamWilsn commented
```markdown
GFM supports footnotes like this[^1]

[^1]: hello
```

GFM supports footnotes like this[^1]

[^1]: hello

2022-09-26 20:53 UTC, xinbenlv commented
> I'm generally OK with this, but if would cause a less clutter as a footnote. I'd be even happier to make this a general policy that applies to all EIPs, and doesn't need to be repeated in every one of them.

Got it. Do you mind I get the policy approved (EIP-1) first, and then I can work on the footnoting on a separate PRs e.g. updating the template, which requires less editor approval I'm assuming?

2022-09-26 20:54 UTC, xinbenlv commented
@axic @lightclient IIUC this proposal require your editor approval too. Could you share your feedback or approval?

2022-10-03 14:36 UTC, lightclient submitted a review, later dismissed
LGTM

2022-10-03 14:36 UTC, lightclient commented
Are we going to update all the EIPs that only refer to RFC 2119?

2022-10-04 01:12 UTC, xinbenlv commented
> Are we going to update all the EIPs that only refer to RFC 2119?

I don't think it's necessary to update all existing EIPs. 

I think we can just update the template so new EIPs will gradually adopt it. Also RFC 2119 or RFC 8174 are both recommendations not requirements so if some author want to opt-out they shall have the freedom to do so. (even EIP-1 itself didn't adopt it as far as I know.)

2022-10-04 01:12 UTC, xinbenlv commented
Friendly ping @axic for last approval

2022-10-04 01:16 UTC, xinbenlv commented
@gcolvin also need your approval. 
I will move it to footnote in a separate PR addressing the format on `eip-template.md` if that's the only concern from you.

2022-10-04 11:43 UTC, Pandapip1 commented
> Are we going to update all the EIPs that only refer to RFC 2119?

This is only a suggestion. EIPs are free to use or not use it. I know the general gist of RFC 8174 and it seems like generally a good idea, but requiring it for *past* EIPs would actually be a normative change in some cases.

2022-10-05 14:52 UTC, xinbenlv commented
Discussed EIPIP meeting 66 and editors on the call @SamWilsn @lightclient are ok to merge this PR with update that removes links from `eip-template.md` for now until EIPW updates.

2022-10-06 13:07 UTC, Pandapip1 commented on EIPS/eip-1.md
> +### RFC 8174
```suggestion
### RFC 2119 and RFC 8174
```

2022-10-08 01:23 UTC, SamWilsn commented on EIPS/eip-1.md
> +> The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as describ
```suggestion
> The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in RFC 2119 and RFC 8174.
```

2022-10-08 01:24 UTC, SamWilsn commented on EIPS/eip-1.md
> +EIPs are encouraged to follow [RFC 8174](https://www.ietf.org/rfc/rfc8174.html) for terminology and to insert the following at the beginning of the Specification section:
```suggestion
EIPs are encouraged to follow [RFC 2119](https://www.ietf.org/rfc/rfc2119.html) and [RFC 8174](https://www.ietf.org/rfc/rfc8174.html) for terminology and to insert the following at the beginning of the Specification section:
```

2022-10-08 01:25 UTC, SamWilsn approved these changes

2022-10-08 01:25 UTC, xinbenlv commented
Thanks @SamWilsn, LGTM

2022-10-08 01:26 UTC, merged

2024-01-07 19:18 UTC, Tura187 commented
I hope this issue has not yet reached.a decision .. I have just been able to get to my emails , due to sabotage of my devices …
Please before you you kick me out or band me at least let me have a chance to claim all of my intellectual property back that was hacked broken into burglerized robbed conned for it to be in person or persons possession…