adding a EIP draft for ERC1155 asset backed NFT extension
ethereum/EIPs pull request #5505
Opened 2022-08-19 04:24 UTC by liszechung

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

2022-08-21 16:35 UTC, Pandapip1 requested changes
Required: Run this through a spell checker. I can personally recommend Grammarly: https://www.grammarly.com/grammar-check

2022-08-21 16:35 UTC, Pandapip1 commented on EIPS/eip-5505.md
> +To propose an extension of smart contract interfaces for asset-backed, fractionalized projects using EIP-1155 standard such that total acquisition will become possible. This proposal focuses on In-Re
```suggestion
To propose an extension of smart contract interfaces for asset-backed, fractionalized projects using the [EIP-1155](./eip-1155.md) standard such that total acquisition will become possible. This proposal focuses on physical assets, where total acquisition should be able to happen.
```
Required: I don't understand the first sentence; it appears to be incomplete. Please fix.
Required: EIP-1155 needs to be linked
Required: Use the correct terminology

2022-08-21 16:35 UTC, Pandapip1 commented on EIPS/eip-5505.md
> +EIP-1155 compliant contracts MAY implement this EIP for adding functionalities to support total acquisition.
```suggestion
EIP-1155 compliant contracts MAY implement this EIP for adding functionalities to support total acquisition.

```
Required: formatting

2022-08-21 16:35 UTC, Pandapip1 commented on EIPS/eip-5505.md
> +```
```suggestion
```solidity
```
Required: Add language

2022-08-21 16:35 UTC, Pandapip1 commented on EIPS/eip-5505.md
> +Native ETH is supported by via WETH (EIP-20).
```suggestion
Native ETH is supported by via wrapped Ether ([EIP-20](./eip-20.md)).
```
Required: Use link
Recommended: Don't use undefined abbreviation

2022-08-21 16:35 UTC, Pandapip1 commented on EIPS/eip-5505.md
> +Implementation (TODO)
```suggestion
```
Required: Optional sections should be removed if not filled in

2022-08-24 08:50 UTC, liszechung reviewed
all updated according to suggestion

2022-08-24 17:04 UTC, Pandapip1 requested changes

2022-08-24 17:04 UTC, Pandapip1 commented on EIPS/eip-5505.md
> +description: Extends [EIP-1155](./eip-1155.md)  to support crucial operations for asset backed NFTs.
```suggestion
description: Extends EIP-1155 to support crucial operations for asset-backed NFTs
```

2022-08-25 15:11 UTC, merged