Minor edits
ethereum/EIPs pull request #5509
Opened 2022-08-20 08:04 UTC by msjenniferelle

Minor edits to fix grammar and spelling.

2022-08-20 12:02 UTC, xinbenlv approved these changes
Thanks for the change. LGTM

2022-08-20 12:02 UTC, xinbenlv commented on EIPS/eip-5065.md
> +This behavior is already possible by deploying a new contract that does `SELFDESTRUCT (0xFF)` but it is prohibitively expensive. In most scenarios, the contract author only wants to transfer ether ra
"transferring" seems grammatically correct, right?

2022-09-08 19:26 UTC, lightclient requested changes
Please open the changes to the other EIP in a separate PR. Thanks!

2022-09-12 01:43 UTC, fulldecent approved these changes

2022-11-11 17:55 UTC, xinbenlv commented
Thank @msjenniferelle for drafting this PR. But we generally edit one EIP at one PR, partly because it require approval by their respective owners. 

Could you split them into different PRs? Until then, consider move this PR back to draft and notify us when new PRs are ready for review again? Again, greatly appreciate your editorial contributions!

2022-11-11 19:55 UTC, lightclient commented
@xinbenlv please stop bumping stale topics for no reason. I already requested the author only change one EIP at a time so that we could collect author approvals and he did not respond. This was getting close to being closed as stale now the counter will reset and we'll get pinged at least 2 more times about its staleness before it is closed.

2022-11-12 17:14 UTC, fulldecent commented
Recommending manual close. It can always be reopened no worries if needed.

2022-11-13 17:02 UTC, closed without merging