Create eip-referable-NFT.md
ethereum/EIPs pull request #5521
Opened 2022-08-22 03:55 UTC by OniReimu

This standard proposes an extension to ERC-721 Non-Fungible Tokens (NFTs) to construct reference relationships among NFTs.

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

2022-08-23 18:19 UTC, Pandapip1 requested changes

2022-08-23 18:19 UTC, Pandapip1 commented on EIPS/eip-5521.md
> +```
```suggestion
```node
```

2022-08-23 18:19 UTC, Pandapip1 commented on EIPS/eip-5521.md
> +```
```suggestion
```solidity
```

2022-08-23 18:19 UTC, Pandapip1 commented on EIPS/eip-5521.md
> +// SPDX-License-Identifier: MIT
```suggestion
// SPDX-License-Identifier: CC0-1.0
```

2022-08-23 18:19 UTC, Pandapip1 commented on EIPS/eip-5521.md
> +```
```suggestion
```solidity
```

2022-08-23 18:19 UTC, Pandapip1 commented on EIPS/eip-5521.md
> +// SPDX-License-Identifier: MIT
```suggestion
// SPDX-License-Identifier: CC0-1.0
```

2022-08-23 18:19 UTC, Pandapip1 commented on EIPS/eip-5521.md
> +The *createdTimestamp* only covers the block-level timestamp (based on block headers), which does not support fine-grained comparison such as transaction-level.
```suggestion
The `createdTimestamp` only covers the block-level timestamp (based on block headers), which does not support fine-grained comparison such as transaction-level.
```

2022-08-23 18:19 UTC, Pandapip1 commented on EIPS/eip-5521.md
> +requires: 165, 721
```suggestion
requires: 165, 721, 5006
```

2022-08-24 01:18 UTC, OniReimu commented
Implemented your suggestions and looking forward to the next review!

Thanks for your time and help @Pandapip1 :-)

2022-08-25 16:28 UTC, Pandapip1 approved these changes
Looks fine. Needs the codespell update

2022-08-25 16:29 UTC, merged