EIP-5008: Move Status to Review
ethereum/EIPs pull request #5544
Opened 2022-08-27 13:02 UTC by emojidao

1. Move status to review
2. Move implementation and test code to assets/eip-5008/

2022-08-27 13:13 UTC, 0xanders approved these changes

2022-08-27 21:43 UTC, Pandapip1 requested changes

2022-08-27 21:43 UTC, Pandapip1 commented on EIPS/eip-5008.md
> +This standard is compatible with EIP-721 standards.
```suggestion
This standard is compatible with EIP-721.
```
Recommended: EIP-721 is a proper noun.

2022-08-27 21:43 UTC, Pandapip1 commented on EIPS/eip-5008.md
> +1. ```npx hardhat test ./test/test.ts```
```suggestion
Run:

```sh
cd ../assets/eip-5008
npm install
npx hardhat test ./test/test.ts
```
Recommended: Formatting

2022-08-27 21:43 UTC, Pandapip1 commented on assets/eip-5008/package.json
> +    "name": "EIP-5006",
```suggestion
    "name": "EIP-5006",
    "dependencies": {
        "@openzeppelin/contracts": "^4.7.3"
    },
```
Recommended: Add OZ to package.json

2022-08-28 13:25 UTC, Pandapip1 approved these changes

2022-08-28 15:21 UTC, 0xanders approved these changes

2022-08-28 15:22 UTC, merged