Update EIP-5521: Add more descriptions
ethereum/EIPs pull request #5563
Opened 2022-08-31 04:21 UTC by OniReimu

1. Add a description of the collaboration with the eip-998
2. Add customized attribute data fields for specific scenarios
3. Remove 5006 from `required` as 5006 is merely a protocol to collaborate with rather than a compulsory basis, similar to the newly-added 998.

2022-08-31 14:34 UTC, xinbenlv reviewed
@OniReimu thanks for the PR
First of all, is it creating a new EIP or is a updating descriptions?

2022-08-31 16:30 UTC, Pandapip1 requested changes
Please resolve the merge conflicts

2022-09-01 00:17 UTC, OniReimu commented
> 

Hello @xinbenlv , this is essentially an update for EIP-5521, not a new eip proposal.

2022-09-01 00:29 UTC, OniReimu commented
> 

Conflicts fixed, thank you @ Pandapip1 :)

2022-09-01 00:55 UTC, Pandapip1 commented on EIPS/eip-5521.md
> +author: Saber Yu (@OniReimu), Qin Wang <qin.wang@data61.csiro.au>, Shange Fu <shange.fu@monash.edu>, Shiping Chen <shiping.chen@data61.csiso.au>, Sherry Xu <xiwei.xu@data61.csiro.au>, Jiangshan Yu <j
Is this change intentional?

2022-09-01 00:56 UTC, Pandapip1 commented on .gitignore
> +.DS_Store
Please put this in a separate PR.

2022-09-01 00:57 UTC, OniReimu commented on EIPS/eip-5521.md
> +author: Saber Yu (@OniReimu), Qin Wang <qin.wang@data61.csiro.au>, Shange Fu <shange.fu@monash.edu>, Shiping Chen <shiping.chen@data61.csiso.au>, Sherry Xu <xiwei.xu@data61.csiro.au>, Jiangshan Yu <j
`csiso` is a typo.

2022-09-01 01:02 UTC, OniReimu commented on .gitignore
> +.DS_Store
Remove this change

2022-09-01 01:04 UTC, Ellajoke commented
Approve

2022-09-01 01:09 UTC, Pandapip1 approved these changes

2022-09-01 01:09 UTC, merged

2022-09-01 01:10 UTC, Pandapip1 commented
(FYI for any concerned editors: @eth-bot was passing, so I was able to merge it)