eip5565: Delegation Registry
ethereum/EIPs pull request #5639
Opened 2022-09-09 23:13 UTC by wwhchung

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

2022-09-09 23:28 UTC, abcoathup commented
EIP numbers are assigned by EIP editors and are generally the PR number.
https://eips.ethereum.org/EIPS/eip-1#eip-editor-responsibilities

2022-09-10 00:46 UTC, wwhchung commented
> EIP numbers are assigned by EIP editors and are generally the PR number. https://eips.ethereum.org/EIPS/eip-1#eip-editor-responsibilities

Updated

2022-09-13 16:05 UTC, wwhchung commented
@Pandapip1 @lightclient would you be able to take a look at this EIP?  It's very similar to EIP-5131, except as a standalone implementation.

It was built in collaboration with quite a few community members, and has been deployed to:
0x00000000b1BBFe1BF5C5934c4bb9c30FEF15E57A

On mainnet and goerli.

Frontend prototype can be found here:
https://token-delegation.netlify.app/

2022-09-15 13:41 UTC, Pandapip1 requested changes

2022-09-15 13:41 UTC, Pandapip1 commented on assets/eip-5639/DelegationRegistry.sol
> +// SPDX-License-Identifier: MIT
```suggestion
// SPDX-License-Identifier: CC0-1.0
```

2022-09-15 13:41 UTC, Pandapip1 commented on assets/eip-5639/IDelegationRegistry.sol
> +// SPDX-License-Identifier: MIT
```suggestion
// SPDX-License-Identifier: CC0-1.0
```

2022-09-15 13:41 UTC, Pandapip1 commented on assets/eip-5639/DelegationRegistry.sol
> +}
```suggestion
}

```

2022-09-15 13:41 UTC, Pandapip1 commented on assets/eip-5639/IDelegationRegistry.sol
> +}
```suggestion
}

```

2022-09-15 13:41 UTC, Pandapip1 commented on EIPS/eip-5639.md
> + * 0xrusowsky
```suggestion
```

2022-09-15 13:41 UTC, Pandapip1 commented on EIPS/eip-5639.md
> +- Includes test cases
```suggestion
```
Must link to the solidity files. Test cases must be in a separate section.

2022-09-15 13:41 UTC, Pandapip1 commented on EIPS/eip-5639.md
> +### Checking Delegation ###
```suggestion
### Checking Delegation
```

2022-09-15 13:41 UTC, Pandapip1 commented on EIPS/eip-5639.md
> +```
```suggestion
```solidity
```

2022-09-15 17:46 UTC, wwhchung commented
Accepted all changes @Pandapip1  

thanks! Any thoughts on getting this merged in?

2022-09-16 18:09 UTC, Pandapip1 approved these changes

2022-09-16 18:10 UTC, merged