Add EIP-5700: Bindable Token Standard
ethereum/EIPs pull request #5700
Opened 2022-09-21 03:15 UTC by leeren

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

2022-10-25 22:18 UTC, leeren commented
@Pandapip1 Seems like the failing tests are unrelated to my EIP changes? What's the right way to diagnose?

2022-11-16 14:38 UTC, Pandapip1 requested changes

2022-11-16 14:38 UTC, Pandapip1 commented on assets/eip-5700/erc721/ERC721.sol
> +////////////////////////////////////////////////////////////////////////////////
Please remove the watermarks.
```suggestion
````

2022-11-16 14:38 UTC, Pandapip1 commented on assets/eip-5700/erc1155/ERC1155.sol
> +////////////////////////////////////////////////////////////////////////////////
```suggestion
```

2022-11-17 03:47 UTC, leeren commented
@Pandapip1 removed watermarks per your request!

2023-01-16 20:06 UTC, leeren commented
Could this please be re-opened?

2023-01-17 22:08 UTC, Pandapip1 approved these changes

2023-01-17 22:11 UTC, merged

2023-05-04 04:18 UTC, leeren commented
Will be updating this soon with changes after reflecting on limitations. I've also done a deep analysis on all other EIPs touching on ownership attribution and will add a section on how this differs and the types of compromises being made. Just commenting here to make it clear that this EIP is not dead and a lot of effort will soon be put forth again to asking for feedback!