Adds @xinbenlv as an EIP Editor (#5502)
ethereum/EIPs pull request #5703
Opened 2022-09-21 16:05 UTC by SamWilsn

Reopening discussion on #5502

2022-12-02 21:29 UTC, Pandapip1 approved these changes

2022-12-02 21:31 UTC, Pandapip1 commented
I think @xinbenlv's recent contributions are more than enough to demonstrate that he both knows the EIP process and has good proposals with which to improve it.

2022-12-02 21:32 UTC, Pandapip1 submitted a review, later dismissed

2022-12-02 21:35 UTC, Pandapip1 commented
Not sure why that was enough to get @eth-bot to merge. I'm manually disabling auto-merge until at least one more editor is in agreement.

2022-12-02 21:35 UTC, xinbenlv commented
@Pandapip1 thank you for your support, but I think per Wednesday this has not gain consensus.

2022-12-02 21:36 UTC, xinbenlv requested changes
Still needs consensus, blocking merge

2022-12-02 23:04 UTC, xinbenlv commented
Just some thoughts about this nomination from my side:

On the meeting of Wednesday, I heard very warm encouragement and good words from you endorsing my editorial contributions and also some frank concern / uncertainty about whether my values "align with Ethereum".

I appreciate both the endorsement and the frank feedback.

It is true that I don't necessarily always hold identical procedural views with some editors, such as about whether to link to free source, external source or other procedures. 

I never shy away from expressing what I think is the best for our EIP effort. But I also always do my best to debate, collaborate, solicity feedback and facilitate a consensused decision. In a lot of times this means withdrawing my own ideas, retrait from my preferences. When it comes to execution, I always follow the procedure/policy of group decision because I feel strongly about respecting consensus.

Some also voiced their concern because I drafted ERC-1202, ERC-5485 indicating the valueing of some societal or philosophical ideas of leveraging / bringing voting, soverignty or governance onchain, and they are not a fan of these ideas and question if these ideas align with / shall be allowed to exist in the movement of Ethereum. I see the technical ability to conduct voting or representing governance onchain could help bring more efficiency and a stronger trust enforced by math. My ideas might be wrong, but I have always been happy to chat, debate and open to be convinced. But I see such ideas less relevant to evaluate an EIP editor nomination.

I feel the most relevant values about editing about **openness, agree to disagree, respect consensus, debate the ideas not the person**. These are my core values that I will never consider compromising. If someone did think any of these core values misalign with Ethereum or EIP efforts, I think I might not be a good fit in this community. But I don't think this is what my respected editors mean.

In general, I see brining diverse ideas and views as healthy and helpful for all society, and that's why I was surprised and deeply moved to hear it was @Pandapip1 who first nominated me for editorship, despite I debate link policy so hard with him.

Within many things in Ethereum, I particularly value the "EIP effort", or the ability that anyone could propose ideas and welcome to provide feedback. Because I value **openness to contribution.**

Personally I contributed to many contributor communities, including Wikipedia. And I also have cofounded several and get to setup governance strucutures multiple times. Everytime, I work hard to bring open-contributor spirit to the community I contributr. In some communities I even started its own ［"X"IP](github.com/zgzgorg/ZGIP) because I think XIP is having a place to propose and share ideas is a great way to harness wisdoms and help contributors have more sense of ownership by allowing them to shape the direction. And this is also why I value so much for this nomination.

Now, if being editors is about "to have power to approve merge or make governing decisions" and thus they prefer such power shall not be shared with someone who holds different precedural views, I totally underatand and am totally fine not to to have such power until this group is ready.

If being editor is about recognition of contributions and invitation to take more responsibility and deeper involvement, this is the reason I accept the nomination. because I feel editorship is more about the later.

I am greatful that some of you enjoy my contributions and look forward to continue to contribute in any capacity this EIP effort wants me to.

2022-12-03 12:15 UTC, Pandapip1 commented
> I feel the most relevant values about editing are openness, agree to disagree, respect consensus, debate the ideas not the person. These are my core values that I will never consider compromising.

I strongly agree with this.

2023-01-25 17:06 UTC, SamWilsn commented
@gcolvin is in favour of adding @xinbenlv. In light of the complete lack of ERC editors, I am also in favour.

I believe @lightclient is still opposed, and blocking this change.

@gcolvin enumerated our options if this is the case:

1. We don't have complete consensus, so we **do not** add @xinbenlv as an editor.
2. We don't have complete consensus, but the rest of the editors feel strongly enough to go ahead without @lightclient. We **do** add @xinbenlv as an editor.

I don't know which of (1) and (2) we're at right now, and I don't think we can move forward without more editors on a call.

2023-01-25 17:29 UTC, xinbenlv commented
Thanks @SamWilsn for documenting.


I also realize, both (1) and (2) are on the assumption that @lightclient is still strongly favor of blocking this PR.

There is also an (3) possibility that with more time co-working with me, @lightclient now feels open to unblock this PR.

2023-02-06 12:54 UTC, xinbenlv commented
Hi @lightclient#0001 , we discussed https://github.com/ethereum/EIPs/pull/5703 last EIPIP documented the result. We are hoping to get this discussed and hopefully come up with a decision in this EIPIP meeting. Your input is greatly appreciated. Would you mind share your views on this thread? 🙏

2023-02-07 09:19 UTC, gcolvin commented
I hardly understand what it means for a person's values to "align with Ethereum".  It's a large, diverse, diffuse community with lots of controversy, disagreements, and politics.  As Editors, we long ago decided that our role was _not_ to judge the  content of a proposal, only its form.

We made this decision when Yoichi resigned as an Editor rather than be involved with the EIP for recovering provably lost funds.  Among the Editors, Nick Johnson argued that if Ether was provably lost then, Why wouldn't you return it to its owner?  Yoichi believed that we should never violate immutability, and that he would be in danger of violating Japanese anti-hacking law if he was to merge the PR.  I felt obliged, on 1st Amendment grounds, to merge it regardless of my beliefs.  I don't recall Hudson's opinion.  In the end we merged it without Yoichi, Nick started into automating the process, and we vowed to _not_ make value judgements.

Compared to all that our disagreements about things like external links are as nothing. I think our policy is way too restrictive, but am not blocking consensus.  I don't see that it matters that I'm not "value-aligned".   We can see how our current policy works out, and change it if we need to.   And opinions about on-chain governance are irrelevant to being and Editor.  I generally oppose it,  but it so what?  I also opposed locking funds on the beacon chain, requiring 32 ETH to run a validator, and lots more.  So be it.

2023-02-07 09:22 UTC, gcolvin commented
So @xinbenlv has worked hard and contributed a lot already.  I can see many reasons to bring him aboard, and no reasons not.

2023-02-07 10:11 UTC, gcolvin submitted a review, later dismissed

2023-02-08 21:15 UTC, Pandapip1 approved these changes
Adding @xinbenlv as a non-governance ERC/Meta/Informational editor, as per the consensus reached on the most recent EIPIP meeting.

2023-02-08 21:18 UTC, merged