Adding an EIP
ethereum/EIPs pull request #5735
Opened 2022-09-30 04:13 UTC by xinbenlv

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

2022-12-24 00:16 UTC, xinbenlv commented
WIP

2023-01-08 02:00 UTC, xinbenlv commented
WIP

2023-01-24 00:25 UTC, xinbenlv commented
WIP

2023-03-24 01:29 UTC, xinbenlv commented
WIP

2023-03-26 16:46 UTC, Pandapip1 commented
@xinbenlv if you're interested, I would be love to work on this with you.

2023-03-26 16:50 UTC, Pandapip1 requested changes

2023-03-26 16:50 UTC, Pandapip1 commented on EIPS/eip-5735.md
> +All EIPs must contain a section that discusses the security implications/considerations relevant to the proposed change. Include information that might be important for security discussions, surfaces
```suggestion
Needs discussion.
```

2023-03-26 16:50 UTC, Pandapip1 commented on EIPS/eip-5735.md
> +An optional section that contains a reference/example implementation that people can use to assist in understanding or implementing this specification.  If the implementation is too large to reasonab
```suggestion
```

2023-03-26 16:50 UTC, Pandapip1 commented on EIPS/eip-5735.md
> +All EIPs that introduce backwards incompatibilities must include a section describing these incompatibilities and their severity. The EIP must explain how the author proposes to deal with these incom
```suggestion
No backward compatibility issues found. 
```

2023-03-26 16:50 UTC, Pandapip1 commented on EIPS/eip-5735.md
> +The rationale fleshes out the specification by describing what motivated the design and why particular design decisions were made. It should describe alternate designs that were considered and relate
```suggestion
TBD
```

2023-03-26 16:50 UTC, Pandapip1 commented on EIPS/eip-5735.md
> +discussions-to: <URL>
Add discussions-to link.

2023-03-26 16:53 UTC, Pandapip1 commented
I removed the optional sections and added placeholders where needed.

Once the spec and discussion link are filled out, this is ready to be merged.

2023-05-22 00:18 UTC, closed without merging