MOD: eip-5489 to review
ethereum/EIPs pull request #5736
Opened 2022-09-30 10:18 UTC by coderfengyun

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

2022-10-08 02:50 UTC, SamWilsn commented on EIPS/eip-5489.md
> +### EIP5489 Metadata JSON schema
```suggestion
### Metadata JSON schema
```

2022-10-08 03:02 UTC, coderfengyun commented
> Please fix the eipw errors

FIX

2022-10-08 03:07 UTC, coderfengyun commented
> Please fix the eipw errors

Fixed

2022-10-15 19:15 UTC, xinbenlv commented on EIPS/eip-5489.md
> +     * The URI may point to a JSON file that confirms to the "EIP5489 Metadata JSON schema".
Just to clarify, do you want to make the URI content to an optional compliant of EIP-5489 or do you want to make a  mandate?
```suggestion
     * The URI MUST point to a JSON file that confirms to the "EIP5489 Metadata JSON schema".
```

2022-10-27 12:41 UTC, Pandapip1 commented on EIPS/eip-5489.md
>  description: NFT Hyperlink Extension tries to make NFTs as decentralized medium for Web3.
Needs a better description

2022-10-31 10:40 UTC, coderfengyun commented on EIPS/eip-5489.md
>  description: NFT Hyperlink Extension tries to make NFTs as decentralized medium for Web3.
Updated

2022-10-31 11:55 UTC, Pandapip1 commented on EIPS/eip-5489.md
> +```
```suggestion
```json
```

2022-10-31 12:02 UTC, Pandapip1 requested changes

2022-11-02 03:57 UTC, coderfengyun commented on EIPS/eip-5489.md
>  This extension adds a new URI scheme, `hnft://` so that the URI pointed to by the NFT is resolvable.
What do you mean by "I-D"? Any guide will be appreciated.

2022-11-02 15:03 UTC, Pandapip1 commented on EIPS/eip-5489.md
>  This extension adds a new URI scheme, `hnft://` so that the URI pointed to by the NFT is resolvable.
Internet draft: https://www.ietf.org/how/ids/

2022-11-03 03:13 UTC, coderfengyun commented on EIPS/eip-5489.md
>  This extension adds a new URI scheme, `hnft://` so that the URI pointed to by the NFT is resolvable.
Will do it.
But when i check other EIPs(such as [eip-721](https://github.com/ethereum/EIPs/blob/3cf212612200f4b59aac2d5681a7c3d59f4dd22f/EIPS/eip-721.md?plain=1#L197)) with URI scheme, I didn't see a "I-D". Is this the new rule for EIP ?

2022-11-03 04:42 UTC, coderfengyun commented on EIPS/eip-5489.md
>  This extension adds a new URI scheme, `hnft://` so that the URI pointed to by the NFT is resolvable.
@Pandapip1 I'll be very appreciated if you give an example which use ID to describe the way the URI schema interacts with smart contracts.

2022-11-09 08:20 UTC, coderfengyun commented on EIPS/eip-5489.md
>  This extension adds a new URI scheme, `hnft://` so that the URI pointed to by the NFT is resolvable.
@Pandapip1 I'll just remove "hnft://" URI schema relative parts, and post it as "I-D" instead.

2022-11-09 15:01 UTC, Pandapip1 commented on EIPS/eip-5489.md
>  This extension adds a new URI scheme, `hnft://` so that the URI pointed to by the NFT is resolvable.
I-Ds are used to formally register URI schemas. It's okay to specify them here, but they just won't be in the list of "real" URI schemas.

2022-11-10 04:00 UTC, coderfengyun commented on EIPS/eip-5489.md
>  This extension adds a new URI scheme, `hnft://` so that the URI pointed to by the NFT is resolvable.
I see. I will post an "I-D" make it real.

2022-11-13 22:33 UTC, merged