Clarify which kinds of ERCs we want and which we don't
ethereum/EIPs pull request #5737
Opened 2022-09-30 20:58 UTC by fulldecent

Here is the blog post https://blog.phor.net/2022/09/30/What-kinds-of-things-should-be-standardized.html

This PR adds it as recommended reading.

2022-10-02 12:18 UTC, Pandapip1 approved these changes
+0. I don't like the fact that this is an external link, but it's also not part of an EIP so it's easier to remove if needbe.

2022-10-02 18:52 UTC, xinbenlv commented
@fulldecent 


I like this personal essay, but I think publishing it at personal venue is better. As of now, I am not sure EIP-1 / README is a good place for personal essay. 

Until EIP-1, README  decide to be linking to personal essays  and is committed to have a complete and balanced representations on views on the same issue, I would not be in support of this proposed inclusion.

2022-10-21 17:51 UTC, SamWilsn commented
This is good content, but I shy away from adding an external link. Would you be open to publishing this as an EIP-1 asset?

2022-10-21 17:54 UTC, fulldecent commented
@SamWilsn Thank you. So adding into EIP-1 or a separate item?

2022-10-23 14:15 UTC, Pandapip1 commented
> So adding into EIP-1 or a separate item?

Put a Markdown version of the article in `/assets/eip-1/useful-submissions.md`.

2022-10-23 14:34 UTC, xinbenlv commented
I object to add this doc to EIP repository as per my commented above

2022-10-28 01:38 UTC, fulldecent commented
@Pandapip1 Updated presentation to the format as you said.

2022-10-30 13:08 UTC, Pandapip1 requested changes

2022-10-30 13:08 UTC, Pandapip1 commented on assets/eip-1/useful-submissions.md
> +Remember, CryptoKitties and CryptoPunks came first, the blockchain NFT standard come afterwards. Don't think that having some standard will make your product successful, that causality is backwards.
```suggestion
Remember, CryptoKitties and CryptoPunks came first, and [the blockchain NFT standard](../../EIPS/eip-721.md) come afterward. Having a standard will not make your product successful. Instead, having a project will make your standard successful.
```

2022-10-30 13:08 UTC, Pandapip1 commented on assets/eip-1/useful-submissions.md
> +But if you really WANT to make something and standardize it, here's how.
```suggestion
But if you really WANT to standardize something, here's how:
```
Make this a bit more succinct

2022-10-30 13:08 UTC, Pandapip1 commented on assets/eip-1/useful-submissions.md
> +William Entriken / 2022-09-30 / this article is cross-posted with [phor.net](https://blog.phor.net/2022/09/30/What-kinds-of-things-should-be-standardized.html).
```suggestion
William Entriken / 2022-09-30 / Derived from a [phor.net](https://blog.phor.net/2022/09/30/What-kinds-of-things-should-be-standardized.html) article
```

2022-10-30 13:08 UTC, Pandapip1 commented on assets/eip-1/useful-submissions.md
> +An easy, low-effort, low-quality way to find a bunch of things to standardize is to find a popular repository of smart contracts, and then write every one of them up with a short rationale. This is f
```suggestion
An easy way to find a bunch of things to standardize is to find a popular repository of smart contracts, and then write every one of them up with a short rationale. This is fun as practice, but unless you have found a strong motivation, please do not submit these.
```
Although I generally agree with the sentiment, those last few sentences are too harsh, even by my standards.

2022-10-30 13:08 UTC, Pandapip1 commented on assets/eip-1/useful-submissions.md
> +FYI, in the United States, the post office has their own police. Watch out for that.
```suggestion
(Note: In the United States, the post office has its own police. Watch out!)
```
Might also be helpful to put that after the ✅

2022-10-30 13:08 UTC, Pandapip1 commented on assets/eip-1/useful-submissions.md
> +<mark>A standard only deserves to be written if multiple people adhere to it and people depend on its surface area.</mark>
```suggestion
**A standard only deserves to be written if multiple people adhere to it and people depend on its surface area.**
```

2022-10-30 13:08 UTC, Pandapip1 commented on assets/eip-1/useful-submissions.md
> +A <dfn>standard</dfn>, in technical settings, is an established specification which allows any compliant thing to work with any compliant user of that thing, also known as cross-connect. It is a set
```suggestion
A *standard*, in technical settings, is an established specification that allows any compliant thing to work with any compliant user of that thing, also known as cross-connect. It is a set of restrictions or marketing claims, incumbent upon the standardized product.
```

2022-10-30 13:08 UTC, Pandapip1 commented on assets/eip-1/useful-submissions.md
> +We call the compliant thing a <dfn>producer</dfn>. And the thing that is relying on those specifications is the <dfn>consumer</dfn>.
```suggestion
We call the compliant thing a *producer*. And the thing that is relying on those specifications is the *consumer*.
```

2022-10-30 13:08 UTC, Pandapip1 commented on assets/eip-1/useful-submissions.md
> +And in technical circles, we call the specific parts that are standardized as its <dfn>surface area</dfn>.
```suggestion
And in technical circles, we call the specific parts that are standardized as its *surface area*.
```
These short sentences should probably be all grouped into one paragraph.

2022-10-30 15:25 UTC, xinbenlv commented
Hi @Pandapip1

Based on this “suggestion”, ERC165 shouldnt be proposed. ERC5289 that @Pandapip1 you proposed should also not be proposed as an EIP because there were no pri~adoption. And many EIPs shall not be proposed

This is why oppose this "suggestion".

2022-10-30 17:20 UTC, Pandapip1 commented
Well, as it turns out, EIP-165 could have been improved had it been tried as a project beforehand. I think EIP-165 is a *good* example of why this should be the case.

2022-10-30 17:40 UTC, xinbenlv commented
@Pandapip1 it might be the case. But there is also merit in publishing thr ERC first that drives consensus and adoption. 

I think the "suggestion" is to say that ERC165 or ERC5289 and ENS standards shall not be even worth proposed unless tried and adopted first. I think this is not the case for many of the existing and useful ERCs. 4337 is also a counter example

Another bad example is https://eips.ethereum.org/EIPS/eip-5313 which provides very limited value to the existing of ERC173

Regardless, I think inclusion of this "suggestion" I think is worthy of a EMF discussion thread.

2023-01-19 00:19 UTC, closed without merging