Move to Last Call
ethereum/EIPs pull request #5759
Opened 2022-10-06 15:05 UTC by xinbenlv

Will update last call deadline before merge

2022-10-06 21:31 UTC, Pandapip1 requested changes
There are a few minor things that need fixing. I'll fix them myself.

2022-10-18 15:48 UTC, SamWilsn reviewed
Should EIP-165 support be optional? That would allow contracts with matching mint/burn functions to be compatible.

I'd expand on (6) a bit. I don't find "with respect to the `ERC721TokenReceiver`" clear enough. Maybe something like "`safeMint` MUST implement the same receiver restrictions as `safeTransferFrom` as defined in EIP-721".

`transfer` -> `transferred` on 68/69 and 73/74

You'll need to remove the external links to goerli. If you can, please put the source code in your assets directory.

2022-10-19 22:29 UTC, Pandapip1 commented on EIPS/eip-5679.md
>  description: An extension for minting and burning tokens for EIP-20, EIP-721, EIP-1155.
```suggestion
description: An extension for minting and burning EIP-20, EIP-721, and EIP-1155 tokens
```

2022-10-27 05:55 UTC, xinbenlv commented
> Should EIP-165 support be optional? That would allow contracts with matching mint/burn functions to be compatible.

Done

> 
> I'd expand on (6) a bit. I don't find "with respect to the `ERC721TokenReceiver`" clear enough. Maybe something like "`safeMint` MUST implement the same receiver restrictions as `safeTransferFrom` as defined in EIP-721".

Done. I think your wording is much clearer.

> `transfer` -> `transferred` on 68/69 and 73/74

Done

> You'll need to remove the external links to goerli. If you can, please put the source code in your assets directory.

Done.  I removed them to comply with your editorial comment. (For the record I oppose to the restriction for adding implementation in the format of deployment address.)

2022-10-27 05:58 UTC, xinbenlv commented
@SamWilsn thanks for reviewing, this PR is ready for merge

2022-10-27 12:58 UTC, Pandapip1 approved these changes

2022-10-27 12:59 UTC, merged