Change title to 'Semi Fungible Token Standard'
ethereum/EIPs pull request #5788
Opened 2022-10-16 15:58 UTC by PhABC

This is a change meant to reflect how ERC-1155 has been referred to over the years by projects and the community. The term Semi-Fungible Token (SFT) has been dominating the conversations and it would be appropriate for the title of this standard to reflect this.

2022-10-17 17:26 UTC, mudgen reviewed
Please do not change the reference to EIP-2535.  This week I am pushing a pull request to make the standard Final.
@PhABC There are also more than 60 projects using it. More info here: https://github.com/mudgen/awesome-diamonds

2022-10-18 02:37 UTC, PhABC commented
@mudgen I'm confused, where am I changing EIP-2535? This PR is only changing the title of ERC-1155

2022-10-18 21:15 UTC, SamWilsn requested changes
This EIP is final, and this change does not correct an error. Unfortunately we cannot merge it.

2022-10-24 13:11 UTC, mudgen commented
> @mudgen I'm confused, where am I changing EIP-2535? This PR is only changing the title of ERC-1155

@PhABC I am sorry, I was the one who was confused. All good. 

By the way EIP-2535 is Final now.

2022-11-10 22:52 UTC, xinbenlv requested changes
Thank you for the effort, unfortunately I am not convinced it's necessary or beneficial to change name. Given EIP-1155 is already final and widely adopted, changing the name requires stronger community consensus. Please consider obtain consensus between authors first for important PR like this.

2022-11-14 19:06 UTC, closed without merging