Add EIP-5806: Account abstraction through delegate transaction
ethereum/EIPs pull request #5806
Opened 2022-10-20 14:17 UTC by Amxx

2022-10-20 16:33 UTC, lightclient requested changes

2022-10-20 16:33 UTC, lightclient commented on EIPS/eip-5806.md
> +description: This EIP adds a new transaction type that allows a EOAs to execute arbitrary code through delegation
```suggestion
description: Adds a new transaction type that allows a EOAs to execute arbitrary code through delegation
```

2022-10-21 08:51 UTC, Amxx commented on EIPS/eip-5806.md
> +requires: 7, 155, 1559, 2718, 2929, 2930
Some are for reference

I think it needs 2718 to define transactions envelop and 2930 for access list. The rest my be superfluous

2022-10-21 12:16 UTC, lightclient approved these changes
LGTM

2022-10-21 12:17 UTC, merged

2023-05-28 15:06 UTC, za8457 reviewed
Amxx:EOA_delegate_transaction

2023-06-17 19:44 UTC, jskelly84 approved these changes

2023-06-17 19:45 UTC, jskelly84 approved these changes