Move to Last Call
ethereum/EIPs pull request #5809
Opened 2022-10-20 23:00 UTC by buzzcai

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

2022-10-23 17:28 UTC, Pandapip1 reviewed
There's a typo on line 83–there's an extra space.

2022-10-23 18:30 UTC, buzzcai commented
@Pandapip1 Markdown Linter is failing with "Error: Failed due to error: Error: ENOENT: no such file or directory, open 'config/.markdownlint.yaml'" while .markdownlint.yaml is in config directory last time I checked.

2022-10-23 22:19 UTC, Pandapip1 requested changes
The security considerations section needs to be completed.

2022-10-23 23:35 UTC, buzzcai commented
@Pandapip1 done

2022-10-24 11:00 UTC, Pandapip1 commented on EIPS/eip-5484.md
>  description: Interface for special NFTS with immutable ownership and pre-determined immutable burn authorization
```suggestion
description: Interface for special NFTs with immutable ownership and pre-determined immutable burn authorization
```

2022-10-24 17:40 UTC, buzzcai commented
> There's a newline missing between L74 and L75.
> 
> On L76, there's a minor grammatical eror.

@Pandapip1 do you mind pointing out the grammatical error on L76? (now L77)

2022-10-25 14:19 UTC, Pandapip1 approved these changes

2022-10-25 14:20 UTC, merged