Move EIP-5750 to Last Call
ethereum/EIPs pull request #5861
Opened 2022-10-31 20:49 UTC by xinbenlv

2022-11-01 12:57 UTC, Pandapip1 commented
There are a few typos. I'll submit a PR to fix them.

2022-11-02 00:12 UTC, xinbenlv commented
Holding this in favor of #5866. will resume when addressed comments

2022-11-04 01:14 UTC, xinbenlv commented
request for review @Pandapip1

2022-11-05 16:26 UTC, Pandapip1 approved these changes

2022-11-05 16:26 UTC, Pandapip1 requested changes
Wait never mind - typo

2022-11-05 16:26 UTC, Pandapip1 commented on EIPS/eip-5750.md
> +There are two ways to achieve extensibility for existing functions. Each comes with a their set of challenges:
```suggestion
There are two ways to achieve extensibility for existing functions. Each comes with their set of challenges:
```

2022-11-05 16:27 UTC, Pandapip1 approved these changes
Now we're good 😅

2022-11-05 16:30 UTC, merged