Update eip-1753.md
ethereum/EIPs pull request #5872
Opened 2022-11-03 22:13 UTC by bitcoinbrisbane

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

2022-11-19 17:46 UTC, xinbenlv commented on EIPS/eip-1753.md
> +This Ethereum Improvement Proposal (EIP) proposes an Ethereum standard for the issuance of licences, permits and grants (Licences) as a Non Transferable Token NTT.
Hi @bitcoinbrisbane , welcome back to EIP process. This EIP has been Stagnant for a while, if you intend to revive this EIP and resume the process to move forward, can you update the status back to Draft and then fix all linter errors?
```suggestion
This Ethereum Improvement Proposal (EIP) proposes an Ethereum standard for the issuance of licences, permits and grants (Licences) as a Non Transferable Token (NTT). 
```

2022-11-20 14:15 UTC, Pandapip1 requested changes
Please fix the walidator issues

2022-12-04 23:26 UTC, Pandapip1 requested changes
Please also fix the EIPW errors

2022-12-04 23:26 UTC, Pandapip1 commented on EIPS/eip-1753.md
> +status: Review
```suggestion
status: Draft
```

2023-02-21 00:19 UTC, closed without merging