Update EIP-721: Use latest version of solidity and remove caveats
ethereum/EIPs pull request #5887
Opened 2022-11-07 12:52 UTC by Pandapip1

All of the caveats mentioned in the EIP have been implemented in solidity. Thus, they are no longer relevant if the solidity version is updated to the most recent one.

2022-11-11 20:55 UTC, SamWilsn commented on EIPS/eip-721.md
> +pragma solidity ^0.8.17;
In `safeTransferFrom`:

```
TypeError: Data location must be "memory" or "calldata" for parameter in external function, but none was given.
```

2022-11-11 20:59 UTC, SamWilsn requested changes
I am not sure that these changes "correct errata [or] add non-normative clarifications":

 - The caveats section still applies for Solidity 0.4.20, so these changes aren't errata.
 - Removing the caveats section obviously isn't _adding_ clarifications.

I'd recommend that we discuss this on EIPIP.

2022-11-13 22:38 UTC, Pandapip1 commented
This adds a non-normative clarification: an outdated version of solidity is removed, and a new version is added. To make this work, an outdated section describing the limitations of an old version of solidity has to removed - an additional clarification that is *added*.

These are clarifications that are added to EIP-721, even though they remove stuff.

2022-11-15 15:36 UTC, SamWilsn commented
Lets discuss on discord/EIPIP.

2022-11-16 15:09 UTC, SamWilsn commented
Closing as per discussion in EIPIP. If you'd like to continue discussion, feel free to re-open.

2022-11-16 15:09 UTC, closed without merging