Orbmis/eip 5897 smart contract event hooks standard
ethereum/EIPs pull request #5902
Opened 2022-11-09 10:47 UTC by orbmis

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

2022-11-09 14:17 UTC, Pandapip1 requested changes

2022-11-09 14:17 UTC, Pandapip1 commented on EIPS/eip-5897.md
> +eip: 5897
```suggestion
eip: 5902
```
Please update the file name too.

2022-11-10 05:43 UTC, xinbenlv reviewed
This is a very interesting EIP. Thank you for your authoring. Will take a look

2022-11-10 11:11 UTC, orbmis commented
> This is a very interesting EIP. Thank you for your authoring. Will take a look

Thanks @xinbenlv .  I fear it's not that obvious how subtly different this is from existing alternatives so I'm happy to answer any questions.

2022-12-25 16:57 UTC, Pandapip1 approved these changes

2022-12-26 16:24 UTC, merged