Update README: Update automatic check descriptions
ethereum/EIPs pull request #5926
Opened 2022-11-13 15:42 UTC by Pandapip1

They're over half a year out-of-date.

2022-11-13 17:16 UTC, lightclient requested changes

2022-11-13 17:16 UTC, lightclient commented on README.md
> +  - False positives sometimes occur. When this happens, please immediately submit a PR editing [.codespell-whitelist](https://github.com/ethereum/EIPs/blob/master/config/.codespell-whitelist).
```suggestion
- False positives sometimes occur. When this happens, please immediately submit a PR editing [.codespell-whitelist](https://github.com/ethereum/EIPs/blob/master/config/.codespell-whitelist).
```

2022-11-13 17:16 UTC, lightclient commented on README.md
> +[^3]: Not a typo 😈
```suggestion
```

2022-11-13 17:16 UTC, lightclient commented on README.md
> +- EIP-1 rules are enforced using [EIP Walidator](https://github.com/ethereum/eipw)[^2][^3]
```suggestion
- EIP-1 rules are enforced using [EIP Walidator](https://github.com/ethereum/eipw)[^2]
```

2022-11-13 19:07 UTC, SamWilsn commented on README.md
> +- EIP-1 rules are enforced using [EIP Walidator](https://github.com/ethereum/eipw)[^2][^3]
```suggestion
- EIP-1 rules are enforced using [`eipw`](https://github.com/ethereum/eipw)[^2]
```

Name of the tool is `eipw`, not "EIP Walidator".

2022-11-15 19:05 UTC, lightclient commented on README.md
> +- False positives sometimes occur. When this happens, please immediately submit a PR editing [.codespell-whitelist](https://github.com/ethereum/EIPs/blob/master/config/.codespell-whitelist).
```suggestion
- False positives sometimes occur. When this happens, please submit a PR editing [.codespell-whitelist](https://github.com/ethereum/EIPs/blob/master/config/.codespell-whitelist).
```

2022-11-15 19:05 UTC, lightclient approved these changes

2022-11-15 19:10 UTC, merged