Update to Review, minor corrections to interface
ethereum/EIPs pull request #5991
Opened 2022-11-17 13:11 UTC by yaruno

Update to interface hash id comment.
Update to function syntax on interface.
Updated the Draft status to Review.

2022-11-17 13:57 UTC, Pandapip1 requested changes

2022-11-17 13:57 UTC, Pandapip1 commented on EIPS/eip-5023.md
>  ```
Line 52: there is a missing "The".

2022-11-17 13:57 UTC, Pandapip1 commented on EIPS/eip-5023.md
>  ```
Nit: specify language
```suggestion
```text
```

2022-11-17 13:57 UTC, Pandapip1 commented on EIPS/eip-5023.md
>  ```
```suggestion
```text
```
Nit: specify language

2022-11-17 13:57 UTC, Pandapip1 commented on EIPS/eip-5023.md
>    \_______/
Nit on L83: missing solidity language

2022-11-17 13:57 UTC, Pandapip1 commented on EIPS/eip-5023.md
```suggestion
```
Not sure why you need so many blank lines.

2022-11-17 13:57 UTC, Pandapip1 commented on EIPS/eip-5023.md
>  TBD
```suggestion
Needs discussion.
```

2022-11-17 14:39 UTC, yaruno commented on EIPS/eip-5023.md
>  ```
Added The to Line52.

2022-11-18 22:57 UTC, Pandapip1 approved these changes

2022-11-18 22:58 UTC, merged