EIP-2481: Move to final
ethereum/EIPs pull request #6015
Opened 2022-11-21 08:10 UTC by MariusVanDerWijden

EIP has been in last call for ~6 months. Eth/66 has long been implemented by all clients, so this should be final already

2022-11-21 09:09 UTC, cburgdorf submitted a review, later dismissed

2022-12-12 23:09 UTC, Pandapip1 requested changes
Walidator errors need to be fixed (except the discussions-to)

2022-12-13 15:18 UTC, SamWilsn requested changes
Couple changes you need to make that were too far from a changed line for me to comment on:

 - Links to devp2p are allowed, but have to be qualified by a commit hash. See the one suggestion I was able to make for the format. (needs #6091)
 - "Test cases" -> "Test Cases"

2022-12-13 15:18 UTC, SamWilsn commented on EIPS/eip-2481.md
> +title: "eth/66 request identifier"
```suggestion
title: eth/66 request identifier
```

2022-12-13 15:18 UTC, SamWilsn commented on EIPS/eip-2481.md
>  author: Christoph Burgdorf (@cburgdorf)
```suggestion
```

2022-12-13 15:18 UTC, SamWilsn commented on EIPS/eip-2481.md
> +description: Introduces a request id for all requests of the eth protocol
```suggestion
description: Introduces a request id for all requests of the eth protocol
author: Christoph Burgdorf (@cburgdorf)
```

2022-12-13 15:18 UTC, SamWilsn commented on EIPS/eip-2481.md
>  last-call-deadline: 2021-08-11
```suggestion
```

2022-12-13 15:18 UTC, SamWilsn commented on EIPS/eip-2481.md
>  The `eth` protocol defines various request and response commands that are used to exchange data between Ethereum nodes. For example, to ask a peer node for a specific set of headers, a node sends it
```suggestion
The `eth` protocol defines various request and response commands that are used to exchange data between Ethereum nodes. For example, to ask a peer node for a specific set of headers, a node sends it the [`GetBlockHeaders`](https://github.com/ethereum/devp2p/blob/40ab248bf7e017e83cc9812a4e048446709623e8/caps/eth.md#getblockheaders-0x03) command.
```

2022-12-16 21:34 UTC, SamWilsn approved these changes

2022-12-16 21:37 UTC, SamWilsn commented
@cburgdorf would you mind reapproving if everything is in order?

2022-12-19 08:57 UTC, cburgdorf approved these changes

2022-12-19 08:58 UTC, merged