EIP-5749: Move to last call
ethereum/EIPs pull request #6018
Opened 2022-11-21 23:17 UTC by kvhnuke

please refer to https://github.com/ethereum/EIPs/pull/5912#issuecomment-1314247015 to comments regarding title and the reason for `evmproviders`

2022-11-21 23:38 UTC, Pandapip1 requested changes
Line 18 has an incomplete sentence.
Line 33 has a random `..etc`. This should be removed, since it doesn't add anything and doesn't make sense in the context of the list ("et cetera" is not an example).
Line 35 has a small mistake: it says "only display" when it should really be "display" (web3modal and web3onboard will still show potentially uninstalled options by the nature that they don't inject either `window.ethereum` or `window.evmproviders`)
Line 68: The "well" in "well documented" can be removed
Line 71 and 78: ```` ``` ```` should be replaced with ```` ```text````
Line 87-91: This list should be inlined so that it's all one sentence.
Line 122: "make sure" should be replaced with "ensure"

2022-11-22 19:03 UTC, kvhnuke commented
@Pandapip1 let me know if I miss anything, all requested changes should be done

2022-11-22 19:23 UTC, Pandapip1 requested changes

2022-11-22 19:23 UTC, Pandapip1 commented on EIPS/eip-5749.md
>  ```
What you have is non-standard notation. I'd recommend using typedoc, which is standardized. In addition, the properties are underspecified:
```suggestion
```typescript
/**
 * Represents the assets needed to display a wallet
 */
interface ProviderInfo {
   /**
    * A UUIDv4 unique to the wallet provider.
    *
    * This must remain the same across versions but must be different across channels. For example, MetaMask, MetaMask Flask, and Trust Wallet should each have different UUIDs, but MetaMask 10.22.2 and MetaMask 9.8.1 should have the same UUID.
    *
    * @readonly
    */
    uuid: string;
    /**
     * The name of the wallet provider (e.g. `MetaMask` or `Trust Wallet`)
     *
     * @readonly
     */
    name: string;
    /**
     * A base64 encoded SVG image.
     *
     * Base64 is defined in RFC 4648.
     *
     * @readonly
     */
    icon: string;
    /**
     * A description of the wallet provider.
     *
     * @readonly
     */
    description: string;
}
```
```

2022-11-22 19:23 UTC, Pandapip1 commented on EIPS/eip-5749.md
>  ```
```suggestion
```typescript
/**
 * The type of `window.evmproviders`
 */
interface EVMProviders {
  /**
   * The key is RECOMMENDED to be the name of the extension in snake_case. It MUST contain only lowercase letters, numbers, and underscores.
   */
  [index: string]: string;
}
```
```

2022-11-22 21:41 UTC, kvhnuke commented on EIPS/eip-5749.md
yea I was trying to make a point on why SVG images are better, Im rewriting this sentence

2022-11-22 21:45 UTC, kvhnuke commented on EIPS/eip-5749.md
@Pandapip1 does the new sentence makes more sense?

2022-11-23 16:04 UTC, Pandapip1 reviewed
Apart from this one minor nit, LGTM

2022-11-23 16:04 UTC, Pandapip1 commented on EIPS/eip-5749.md
> +**data:image/svg+xml;** SVG image type was chosen in order to have more flexibility in modifying images, such as resizing.
```suggestion
The SVG image format was chosen for its flexibility, lightweight nature, and dynamic resizing capabilities.
```
How about this?

2022-11-23 16:04 UTC, Pandapip1 commented on EIPS/eip-5749.md
> +last-call-deadline: 2022-12-05
```suggestion
last-call-deadline: 2022-12-07
```

2022-11-23 17:05 UTC, kvhnuke commented on EIPS/eip-5749.md
> +**data:image/svg+xml;** SVG image type was chosen in order to have more flexibility in modifying images, such as resizing.
perfect, thank you!

2022-11-23 21:29 UTC, kdenhartog requested changes
How do you expect this to interact with EIP-5593? I'd think we should resolve this before moving this to last call otherwise we may hit incompatibilities that have to be resolved separately. Out of curiosity how many wallets have reviewed this work currently and are supportive of it? Also are you aware that MetaMask is looking to start modifying their ETH provider based on Chain Agnostic Standards Alliance's CAIP-25 so much of this work may become incompatible with the largest wallet in this space?

For me, I don't object to the content in this, but I do to the quick status update without making sure that wallet providers plan to implement this breaking change and that this work doesn't interfere with other efforts to update the provider object.

2022-11-24 01:00 UTC, kvhnuke commented
> How do you expect this to interact with EIP-5593? I'd think we should resolve this before moving this to last call otherwise we may hit incompatibilities that have to be resolved separately. Out of curiosity how many wallets have reviewed this work currently and are supportive of it? Also are you aware that MetaMask is looking to start modifying their ETH provider based on Chain Agnostic Standards Alliance's CAIP-25 so much of this work may become incompatible with the largest wallet in this space?
> 
> For me, I don't object to the content in this, but I do to the quick status update without making sure that wallet providers plan to implement this breaking change and that this work doesn't interfere with other efforts to update the provider object.

I believe discussions regarding the proposal should happen under the discussion link, but to answer your question, 
this will note interfere with EIP-5593, it is still upto the extension wallet to decide when to inject and it could be based on user settings.

Whole goal of this EIP is for wallets to open up a new avenue so dapps can detect which wallets are installed by the user, fight 
 for `window.ethereum` will continue to happen for the near future as this EIP is not a breaking change. However, this EIP will let wallets to inject also under `window.evmproviders={}` 
we already received support from few major wallets and major web3 onboarding libraries. 

chain agnostic standards are different topic where we have to redo the whole communication layer, I think we should visit that once that kind of standard turn into a reality

2022-11-24 01:10 UTC, Pandapip1 commented
I'd say it would be up to EIP-5593 to specify when `window.evmproviders` is injected. Compatibility with EIP-5593 seems out of the scope of this EIP, but compatibility with this EIP seems in the scope of EIP-5593.

2022-11-24 01:11 UTC, Pandapip1 approved these changes
LGTM.

2022-11-24 01:12 UTC, merged

2022-11-24 01:13 UTC, kvhnuke commented
> LGTM.

Thank you!!!