SmartDerivativeContract - added eip markdown file, interface, reference implemntation, unit tes…
ethereum/EIPs pull request #6123
Opened 2022-12-13 13:59 UTC by pekola

For the concept of a smartderivativecontract please find the following:
1. eip markdown file
2. assets/contracts: interface and ref implementation
3. assets/test: unit tests

2022-12-13 18:05 UTC, Pandapip1 commented on EIPS/eip-0000.md
> +eip: 0000
```suggestion
eip: 6123
```
Make sure to rename the file, too!

2022-12-13 18:20 UTC, Pandapip1 requested changes
The interface is a little underdefined. Would you mind adding clarification on which parameters correspond to what (yes, it's pretty obvious, but needs to be specified).

2022-12-13 18:20 UTC, Pandapip1 commented on EIPS/eip-6123.md
> +``` js
```suggestion
```solidity
```

2022-12-13 18:20 UTC, Pandapip1 commented on EIPS/eip-6123.md
> +``` js
```suggestion
```solidity
```

2022-12-13 18:20 UTC, Pandapip1 commented on EIPS/eip-6123.md
> +``` js
```suggestion
```solidity
```

2022-12-13 18:20 UTC, Pandapip1 commented on EIPS/eip-6123.md
> +``` js
```suggestion
```solidity
```

2022-12-13 18:20 UTC, Pandapip1 commented on EIPS/eip-6123.md
> +``` js
```suggestion
```solidity
```

2022-12-13 18:20 UTC, Pandapip1 commented on EIPS/eip-6123.md
> +``` js
```suggestion
```solidity
```

2022-12-13 18:20 UTC, Pandapip1 commented on EIPS/eip-6123.md
> +``` js
```suggestion
```solidity
```

2022-12-13 18:20 UTC, Pandapip1 commented on EIPS/eip-6123.md
> +``` js
```suggestion
```solidity
```

2022-12-13 18:20 UTC, Pandapip1 commented on EIPS/eip-6123.md
> +``` js
```suggestion
```solidity
```

2022-12-13 18:20 UTC, Pandapip1 commented on EIPS/eip-6123.md
> +``` js
```suggestion
```solidity
```

2022-12-13 18:20 UTC, Pandapip1 commented on EIPS/eip-6123.md
> +With this method eligible party is allowed to confirm a former requested mutual trade termination
```suggestion
Allows eligible parties to confirm a formerly-requested mutual trade termination.
```

2022-12-13 18:20 UTC, Pandapip1 commented on EIPS/eip-6123.md
> +Method enables an eligible party to request a mutual termination.
```suggestion
Allows an eligible party to request a mutual termination
```

2022-12-13 18:20 UTC, Pandapip1 commented on EIPS/eip-6123.md
> +Allows eligible particiants - e.g. counterparties or a delegated agent - to initiate a settlement.
```suggestion
Allows eligible participants (such as counterparties or a delegated agent) to initiate a settlement.
```

2022-12-13 19:53 UTC, pekola commented
> The interface is a little underdefined. Would you mind adding clarification on which parameters correspond to what (yes, it's pretty obvious, but needs to be specified).

Hi - this is not really clear to me - should we comment more on the metods and events and their arguments?

2022-12-13 20:38 UTC, pekola commented
> > The interface is a little underdefined. Would you mind adding clarification on which parameters correspond to what (yes, it's pretty obvious, but needs to be specified).
> 
> Hi - this is not really clear to me - should we comment more on the methods and events and their arguments in the interface file?

--> try to do my best to provide more clarification. See ISDC:sol

2022-12-15 17:04 UTC, cfries approved these changes

2022-12-18 10:13 UTC, cfries commented on EIPS/eip-6123.md
> +Live-cycle unit tests based on the sample implementation and usage of erc20 token is provided. See folder /assets/test.
I have update the reference to the unit tests. All test are in one file (SDC.js) and the eip now references that file.

2022-12-18 10:17 UTC, cfries commented on EIPS/eip-6123.md
> +discussions-to: https://ethereum-magicians.org/
Link to _thread on ethereum magicians_ was added by @pekola

2022-12-18 10:19 UTC, cfries approved these changes

2022-12-21 18:12 UTC, Pandapip1 approved these changes
I think this is fine for a draft

2022-12-23 08:01 UTC, cfries commented
> I think this is fine for a draft

Thank you. So it will be merged autmatically? Or anything to do for us? @eth-bot ?

2022-12-23 20:58 UTC, sackodiego approved these changes

2022-12-25 23:23 UTC, merged