add an all.xml rss feed
ethereum/EIPs pull request #6157
Opened 2022-12-16 18:15 UTC by moodysalem

fixes https://github.com/ethereum/EIPs/issues/6068

2022-12-17 03:28 UTC, SamWilsn commented on all.xml
> +        <author>{{ eip.author | xml_escape }}</author>
I think `<author>` needs to be an email address.

2022-12-17 03:28 UTC, SamWilsn commented on all.xml
> +        {% else %}
```suggestion
        {% endif %}
```

2023-01-06 20:14 UTC, Pandapip1 requested changes
I would definitely like to move all of the rss stuff into an `rss` folder.

2023-01-07 16:18 UTC, moodysalem commented
Moved it, not sure what else is needed

2023-01-07 20:49 UTC, Pandapip1 approved these changes

2023-01-31 01:16 UTC, SamWilsn approved these changes

2023-01-31 01:17 UTC, merged