Add jumpf eip
ethereum/EIPs pull request #6206
Opened 2022-12-22 14:33 UTC by lightclient

This is a follow up from #6205 which removed `JUMPF` specification from EIP-4750. We have reintroduced it with a direct dependency to EIP-5450 to avoid specifying any runtime validation semantics (which would ultimately be discarded with EIP-5450).

2022-12-22 18:06 UTC, Pandapip1 commented on EIPS/eip-6206.md
> +* Extend [EIP-4200](./eip-4200) code validation to fail if any `RJUMP*` offset points to one of the two bytes directly following a `JUMPF` instruction.
@SamWilsn, why did EIPW not catch this previously incorrect link? (was `[EIP-4200](./eip-4200)`)

2022-12-22 18:13 UTC, Pandapip1 requested changes

2022-12-22 18:13 UTC, Pandapip1 commented on EIPS/eip-6206.md
> +Allow tail call optimizations in [EOF functions](./eip-4750.md) by introducing a new instruction `JUMPF`, which jumps to a code sections without adding a new return stack frame.
```suggestion
This EIP allows for tail call optimizations in EOF functions ([EIP-4750](./eip-4750.md)) by introducing a new instruction `JUMPF`, which jumps to a code section without adding a new return stack frame.
```
Again, eipw didn't catch this somehow

2022-12-22 18:13 UTC, Pandapip1 commented on EIPS/eip-6206.md
> +It is common for function to make a call at the end of the routine only to then return. `JUMPF` optimizes this behavior by changing code sections without needing to update the return stack.
```suggestion
It is common for functions to make a call at the end of the routine only to then return. `JUMPF` optimizes this behavior by changing code sections without needing to update the return stack.
```

2022-12-22 18:13 UTC, Pandapip1 commented on EIPS/eip-6206.md
> +a new instruction `JUMPF (0xb2)` is introduced.
```suggestion
A new instruction, `JUMPF (0xb2)`, is introduced.
```

2022-12-22 18:13 UTC, Pandapip1 commented on EIPS/eip-6206.md
> +1. Has one immediate argument, `code_section_index`, encoded as a 16-bit unsigned big-endian value.
```suggestion
1. `JUMPF` has one immediate argument, `code_section_index`, encoded as a 16-bit unsigned big-endian value.
```

2022-12-22 18:13 UTC, Pandapip1 commented on EIPS/eip-6206.md
> +3. Charges 5 gas.
```suggestion
3. `JUMPF` costs 5 gas.
```

2022-12-22 18:13 UTC, Pandapip1 commented on EIPS/eip-6206.md
> +2. If data stack size exceeds `1024 - type[code_section_index].max_stack_height` (i.e. if the called function may exceed the global stack height limit), execution results in exceptional halt. This al
```suggestion
2. If the data stack size exceeds `1024 - type[code_section_index].max_stack_height` (i.e. if the called function may exceed the global stack height limit), execution results in an exceptional halt. This guarantees that the stack height after the call is within the limits.
```

2022-12-22 18:13 UTC, Pandapip1 commented on EIPS/eip-6206.md
> +4. Pops nothing and pushes nothing to data stack.
```suggestion
4. `JUMPF` neither pops nor pushes anything to the data stack.
```

2022-12-22 18:13 UTC, Pandapip1 commented on EIPS/eip-6206.md
> +* Immediate argument of `JUMPF` MUST be greater than or equal to the total number of code sections.
```suggestion
* The immediate argument of `JUMPF` MUST be greater than or equal to the total number of code sections.
```

2022-12-22 18:13 UTC, Pandapip1 commented on EIPS/eip-6206.md
> +* Stack height at `JUMPF` MUST be greater than or equal to `type[code_section_index].inputs`.
```suggestion
* The stack height at `JUMPF` MUST be greater than or equal to `type[code_section_index].inputs`.
```

2022-12-22 18:13 UTC, Pandapip1 commented on EIPS/eip-6206.md
> +* Extend [EIP-4200](./eip-4200.md) code validation to fail if any `RJUMP*` offset points to one of the two bytes directly following a `JUMPF` instruction.
```suggestion
* The code validation defined in [EIP-4200](./eip-4200.md) also fails if any `RJUMP*` offset points to one of the two bytes directly following a `JUMPF` instruction.
```

2022-12-22 18:13 UTC, Pandapip1 commented on EIPS/eip-6206.md
> +None.
```suggestion
Needs discussion.
```

2022-12-22 18:14 UTC, Pandapip1 approved these changes
LGTM now

2022-12-22 18:18 UTC, merged

2022-12-22 21:26 UTC, lightclient commented
@Pandapip1 I don't think you should be be committing to other people's EIPs without their consent. Some of your changes are good, but as an author I would like to incorporate your feedback how I see fit.

2022-12-24 13:00 UTC, Pandapip1 commented
There are some that I will commit w/o consent (typo fixes, formatting errors, and the like). The only real one that I could see anybody taking issue with is https://github.com/ethereum/EIPs/pull/6206#discussion_r1055731295, which I was on the fence about including in the commit. In the future, I'll limit it a bit further. Thanks for the feedback!