Propose Composable NFTs utilizing Equippable Parts
ethereum/EIPs pull request #6220
Opened 2022-12-27 01:08 UTC by ThunderDeliverer

This EIP draft proposal includes RMRK team's work on developing an NFT standard where an NFT can can equip fixed and slot parts and in turn equip NFTs into slot parts.

2023-01-04 22:28 UTC, Pandapip1 requested changes
The test cases/reference implementation are too complete. Please get rid of the package/config/dependency files.

2023-01-05 20:12 UTC, steven2308 commented
> The test cases/reference implementation are too complete. Please get rid of the package/config/dependency files.

I removed the not vital configuration files. Just `package.json` and `hardhat.config.ts` left.

2023-01-16 23:52 UTC, ThunderDeliverer commented
@Pandapip1 would you mind taking a look at the changes since your review. We addressed the completeness of the implementation and would love to move forward with the EIP process.

2023-01-20 17:31 UTC, Pandapip1 approved these changes
This review wasn't submitted. These changes must be made before Review, but for now, I think this is okay for a draft.

2023-01-20 17:33 UTC, merged

2023-01-24 10:36 UTC, ThunderDeliverer commented
Thank you for submitting your review. The requested changes were applied in the #6369