Move EIP-5298 to Review
ethereum/EIPs pull request #6343
Opened 2023-01-16 20:29 UTC by xinbenlv

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

2023-01-18 04:30 UTC, Pandapip1 requested changes
The specification does not specify which ens nodes are approved.

2023-01-19 22:43 UTC, xinbenlv commented
> The specification does not specify which ens nodes are approved.

I added "Any ensNode is allowed", does it clarify your question?

2023-01-20 14:37 UTC, Pandapip1 commented on EIPS/eip-5298.md
> +2. We didn't expose getters or setters to an ensRoot because we believe that shall be address outside of the scope of this EIP.
```suggestion
2. We didn't expose getters or setters for ensRoot because it is outside of the scope of this EIP.
```

2023-01-20 14:37 UTC, Pandapip1 commented on EIPS/eip-5298.md
> +Needs disucssion.
```suggestion
Needs discussion.
```

2023-01-20 14:37 UTC, Pandapip1 approved these changes

2023-01-20 14:43 UTC, merged