Multi chain token standard
ethereum/EIPs pull request #6403
Opened 2023-01-31 11:33 UTC by seunlanlege

This EIP standardizes the interface for `ERC20` token contracts which will allow provably secure, trustless bridge contracts to mint & burn tokens, enabling a new class of `ERC20` tokens that can be native to multiple chains.

2023-07-10 06:59 UTC, seunlanlege commented
This is ready for review

2023-07-29 00:35 UTC, seunlanlege commented
This is ready for review

2023-07-30 01:14 UTC, Pandapip1 requested changes
Please fix the walidator errors.

2023-09-13 15:56 UTC, SamWilsn commented on EIPS/eip-6160.md
> +We propose new [`ERC20`](./eip-20.md), [`ERC721`](./eip-721.md) and [`ERC1155`](./eip-1155.md) extension interfaces which will allow provably secure, trustless bridge contracts to mint & burn tokens,
```suggestion
We propose new [`ERC20`](./eip-20.md), [`ERC721`](./eip-721.md) and [`ERC1155`](./eip-1155.md) extension interfaces which will allow provably secure, trustless bridge contracts to mint & burn tokens, enabling a new class of tokens that can be native to multiple chains.
```

2023-09-13 15:56 UTC, SamWilsn commented on EIPS/eip-6160.md
> +[EIP-4844](./eip-4844.md) will set the stage for the Cambrian explosion of L2s on Ethereum. With multiple L2s living on the ethereum blockchain, It therefore becomes necessary to standardize an inter
```suggestion
[EIP-4844](./eip-4844.md) will set the stage for the Cambrian explosion of L2s on Ethereum. With multiple L2s living on the ethereum blockchain, it therefore becomes necessary to standardize an interface that will allow for native tokens to flow across these L2s, removing the need for wrapped representations of these assets.
```

2023-09-13 15:56 UTC, SamWilsn commented on EIPS/eip-6160.md
> +Optimisim and Arbitrum, optimistic L2s which are already live on Ethereum today currently have their own custom token interfaces¹ that allow their bridge contracts to mint & burn tokens on L1 & L2. I
We only allow very specific external references (see [EIP-1](https://eips.ethereum.org/EIPS/eip-1#linking-to-external-resources).)

```suggestion
Optimisim and Arbitrum, optimistic L2s which are already live on Ethereum today currently have their own custom token interfaces that allow their bridge contracts to mint & burn tokens on L1 & L2. In order to remove the cognitive load on token issuers & developers from extending multiple interface for all the various L2s that will live on Ethereum. It becomes necessary to define a standardized API that all token issuers should implement in order to provide these trustless bridge contracts with the interface needed to transport tokens across these different chains.
```

2023-09-13 15:56 UTC, SamWilsn commented on EIPS/eip-6160.md
> +Smart contracts implementing the EIP-6160 standard MUST implement all of the functions in the `EIP-6160` interface.
```suggestion
Smart contracts implementing this standard MUST implement all of the functions in the corresponding interface defined below.
```

2023-09-13 15:56 UTC, SamWilsn commented on EIPS/eip-6160.md
> +Smart contracts implementing the EIP-6160 standard MUST implement the `EIP-165 supportsInterface` function and MUST return the constant value `true` if *`0x01cbdea7`* is passed through the `interface
```suggestion
Smart contracts implementing the EIP-6160 standard MUST implement the [ERC-165](./eip-165.md) `supportsInterface` function and MUST return the constant value `true` if *`0x01cbdea7`* is passed through the `interfaceID` argument.
```

2023-09-13 15:56 UTC, SamWilsn commented on EIPS/eip-6160.md
> +1. Any contract complying with [EIP-20](./eip-20.md) when extended with this EIP, **MUST** implement the following interface:
```suggestion
1. Any contract complying with [ERC-20](./eip-20.md) when extended with this EIP, **MUST** implement the following interface:
```

2023-09-13 15:56 UTC, SamWilsn commented on EIPS/eip-6160.md
> +2. Any contract complying with [EIP-721](./eip-721.md) when extended with this EIP, **MUST** implement the following interface:
```suggestion
2. Any contract complying with [ERC-721](./eip-721.md) when extended with this EIP, **MUST** implement the following interface:
```

2023-09-13 15:56 UTC, SamWilsn commented on EIPS/eip-6160.md
> +3. Any contract complying with [EIP-1155](./eip-1155.md) when extended with this EIP, **MUST** implement the following interface:
```suggestion
3. Any contract complying with [ERC-1155](./eip-1155.md) when extended with this EIP, **MUST** implement the following interface:
```

2023-09-13 15:56 UTC, SamWilsn commented on EIPS/eip-6160.md
> +1. We have chosen the [EIP-5679](./eip-5679.md) standard to provide the mint & burn interface.
```suggestion
1. We have chosen the [ERC-5679](./eip-5679.md) standard to provide the mint & burn interface.
```

2023-09-13 15:56 UTC, SamWilsn commented on EIPS/eip-6160.md
> +1. We have chosen the [EIP-5679](./eip-5679.md) standard to provide the mint & burn interface.
The rationale section should explain _why_ a choice was made, not just state which decisions were considered.

2023-09-13 15:56 UTC, SamWilsn commented on EIPS/eip-6160.md
> +## Implementation
```suggestion
## Reference Implementation
```

2023-09-13 15:56 UTC, SamWilsn commented on EIPS/eip-6160.md
> +We have made an example implementation for this EIP at [polytope-labs implementation](https://github.com/polytope-labs/multichain-native-tokens/tree/main/src/tokens)
We don't allow external reference implementations. If you'd like, you can create a minimal reference implementation and include it in the `assets` directory under a permissive license (`CC0-1.0` preferred.) Failing that, just remove the whole section.

2023-09-13 15:56 UTC, SamWilsn commented on EIPS/eip-6160.md
> +This EIP is designed to be compatible with EIP-20, EIP-721, EIP-1155.
```suggestion
This EIP is designed to be compatible with ERC-20, ERC-721, ERC-1155.
```

2023-09-13 15:56 UTC, SamWilsn commented on EIPS/eip-6160.md
> +¹ Arbitrum: [ICustomToken](https://github.com/OffchainLabs/token-bridge-contracts/blob/main/contracts/tokenbridge/ethereum/ICustomToken.sol),  [IArbToken](https://github.com/OffchainLabs/token-bridge
```suggestion
```

Please remove this whole section. We don't allow external links except as mentioned in EIP-1.

2023-10-25 22:05 UTC, SamWilsn commented
I am closing this pull request because we are in the process of separating EIPs and ERCs into distinct repositories. Unfortunately, as far as we are aware, GitHub does not provide any tools to ease this migration, so every pull request will need to be re-opened manually.

As this is a PR to create / modify an ERC, I will kindly ask you to redirect this to the new repository at [ethereum/ERCs](https://github.com/ethereum/ERCs). **We have prepared [a guide](https://github.com/ethereum/ERCs/issues/8) to help with the process.**

If there is relevant history here, please link to this PR from the new pull request.

On behalf of the EIP Editors, I apologize for this inconvenience.

2023-10-25 22:05 UTC, closed without merging

2026-05-14 07:37 UTC, yoitsdave0415-star commented
> ### File `EIPS/eip-6160.md`
> Requires 1 more reviewers from @axic, @Pandapip1, @SamWilsn, @xinbenlv