Multi-operator, per-token ERC721 approval
ethereum/EIPs pull request #6464
Opened 2023-02-08 15:53 UTC by aschlosberg

### Abstract

> The ERC721 standard did not foresee the approval of multiple operators to manage a specific token on behalf of its owner. This lead to the establishment of `setApprovalForAll()` as the predominant way to authorise operators, which affords the approved address control over all assets and creates an unnecessarily broad security risk that has already been exploited in a multitude of phishing attacks. The presented EIP extends ERC721 by introducing a fine-grained, on-chain approval mechanism that allows owners to authorise multiple, specific operators on a per-token basis; this removes unnecessary access permissions and shrinks the surface for exploits to a minimum. The provided reference implementation further enables cheap revocation of all approvals on a per-owner or per-token basis.

### TL;DR

Extend ERC721 with `setExplicitApproval(address operator, uint256 tokenId, bool approved)` to allow NFT owners to avoid use of `setApprovalForAll()` when selling on multiple marketplaces.

2023-02-09 14:57 UTC, aschlosberg commented
We've addressed all linter issues, including `eth-bot`'s (using the presumptive EIP number 6464 based on the PR; it's a nice number so we'd love to keep it if possible, please).

I'll try get `eth-bot` to rerun in another comment but am guessing permissions won't allow it :)

2023-02-24 18:55 UTC, Pandapip1 commented
@eth-bot rerun

2023-02-24 18:56 UTC, Pandapip1 requested changes
Please rebase the branch. Your walidator version is outdated.

2023-02-26 00:43 UTC, Pandapip1 requested changes
Please fix [the walidator issues](https://github.com/ethereum/EIPs/pull/6464/files)

2023-02-26 17:42 UTC, aschlosberg commented
@eth-bot rerun

2023-02-26 17:45 UTC, aschlosberg commented
Thanks for taking a look, @Pandapip1, all walidator issues have been addressed.

2023-02-27 20:23 UTC, Pandapip1 requested changes

2023-02-27 20:23 UTC, Pandapip1 commented on assets/eip-6464/contracts/IERC165.sol
> +// SPDX-License-Identifier: MIT
```suggestion
// SPDX-License-Identifier: CC0-1.0
```

2023-02-27 20:23 UTC, Pandapip1 commented on assets/eip-6464/contracts/IERC6464.sol
> +// SPDX-License-Identifier: MIT
```suggestion
// SPDX-License-Identifier: CC0-1.0
```

2023-02-27 20:23 UTC, Pandapip1 commented on assets/eip-6464/contracts/IERC721.sol
> +// SPDX-License-Identifier: MIT
```suggestion
// SPDX-License-Identifier: CC0-1.0
```

2023-02-28 09:58 UTC, aschlosberg commented
I couldn't just swap out MIT for CC0 as those were OpenZeppelin versions, so I've replaced them with the originals from the EIPs themselves. Also changed ours to CC0 as requested.

2023-02-28 13:04 UTC, Pandapip1 commented on EIPS/eip-6464.md
> +```
```suggestion
```solidity
```

2023-03-03 18:55 UTC, Pandapip1 approved these changes
I'm still not sure that I understand this, but it looks complete and has no obvious errors. Hopefully you can make this a bit clearer before Review.

2023-03-03 18:56 UTC, merged

2023-03-03 20:20 UTC, aschlosberg commented
> I'm still not sure that I understand this, but it looks complete and has no obvious errors. Hopefully you can make this a bit clearer before Review.

Thanks for the reviews, @Pandapip1. Are we allowed to include lay descriptions in the Abstract? The template says it must be technical and very terse, but I think something like the following would go a long way to clarify:

> The only way to sell NFTs on more than one marketplace simultaneously is to approve each marketplace to manage _all_ of your tokens on a contract, not just the single token you wish to sell. This EIP introduces a fine-grained way to approve only specific token(s) and thus reduce the security risk from phishing scams that piggyback off marketplace contracts.