Update EIP-5507: Move to Last Call
ethereum/EIPs pull request #6556
Opened 2023-02-23 20:12 UTC by Pandapip1

2023-02-23 22:12 UTC, SamWilsn requested changes
This proposal doesn't do a good enough job explaining why these interfaces need to be standardized in an EIP. As far as I can tell, any token that wants to offer a refund can do so, and the interface used doesn't need to be standardized.

2023-02-23 22:42 UTC, Pandapip1 commented
Done. Updating this branch...

2023-02-24 16:49 UTC, Pandapip1 commented
@eth-bot rerun

2023-02-24 17:05 UTC, Pandapip1 commented
@eth-bot rerun

2023-04-18 15:41 UTC, SamWilsn commented on EIPS/eip-5507.md
> +last-call-deadline: 2023-03-13
```suggestion
last-call-deadline: 2023-05-02
```

2023-04-18 15:42 UTC, SamWilsn approved these changes
I'm still not sold that this is the best approach, but I don't think there's anything technically blocking this EIP from progressing.

2023-04-18 15:48 UTC, merged