Add a new bit based permission proposal
ethereum/EIPs pull request #6617
Opened 2023-03-06 04:11 UTC by chiro-hiro

2023-03-06 04:18 UTC, chiro-hiro commented
Hi @Pandapip1,

We add a new **Bit Based Permission** proposal as your request. I and @vdusart will update EIP-6366 as well.

2023-03-06 08:39 UTC, abcoathup commented
The PR doesn't have a `c-new` label?

2023-03-06 13:01 UTC, Pandapip1 requested changes

2023-03-06 13:01 UTC, Pandapip1 commented on EIPS/eip-bit_based_permission.md
> +By using bitwise and bitmask operations to determine access rights, we gain in efficiency, flexibility and more.
```suggestion
```
This reads like Rationale.

2023-03-06 13:01 UTC, Pandapip1 commented on EIPS/eip-bit_based_permission.md
> +This EIP offers a standard for building a bit-based permission and role system. Each permission is represented by a single bit in `uint256` from which we can defined up to `256` permissions and `2²⁵⁶
```suggestion
This EIP offers a standard for building a bit-based permission and role system. Each permission is represented by a single bit. By using an `uint256`, up to $256$ permissions and $2^{256}$ roles can be defined. We are able to specify the importance of permission based on the order of the bits.
```

2023-03-07 04:09 UTC, chiro-hiro commented on EIPS/eip-bit_based_permission.md
> +_Note_ The following specifications use syntax from Solidity `0.8.7` (or above)
@vdusart implemented a library to perform bit wise operators

2023-03-08 16:00 UTC, Pandapip1 requested changes

2023-03-09 08:07 UTC, chiro-hiro commented on EIPS/eip-6617.md
> +        @param _permissionToAdd		The permission that will be added
@vdusart I think, code formatter is broken.

2023-03-09 13:38 UTC, Pandapip1 approved these changes
Lgtm for draft

2023-03-09 13:39 UTC, merged