Move ERC-5570 to Last Call
ethereum/EIPs pull request #6703
Opened 2023-03-17 21:58 UTC by darcys22

2023-03-22 18:48 UTC, Pandapip1 requested changes
I wouldn't usually block an EIP for content-related reasons, but this has some pretty significant privacy concerns, namely, doxxing the Ethereum address used to submit a transaction, their IRL name, telephone number, email address, and **physical address** *and* revealing the contents of everything the person has bought.

The above should be addressed before this moves to last call.

2023-03-23 03:12 UTC, darcys22 commented
> I wouldn't usually block an EIP for content-related reasons, but this has some pretty significant privacy concerns, namely, doxxing the Ethereum address used to submit a transaction, their IRL name, telephone number, email address, and **physical address** _and_ revealing the contents of everything the person has bought.
> 
> The above should be addressed before this moves to last call.

Hi @Pandapip1 thanks for raising this. I have made a response in the ethereum cat herders thead because its such an important topic. https://ethereum-magicians.org/t/idea-standard-digital-receipts-using-erc-721/9908/40

Do you think this information should be conveyed directly in the ERC? I can update it to include a note recommending that the metadata be encrypted, but the description of how to encrypt it is out of scope for this ERC

2023-04-18 15:39 UTC, SamWilsn commented
Is this ready to go to last call, or are you still sorting out the privacy issues?

2023-04-18 16:03 UTC, darcys22 commented
Hi @SamWilsn i believe it is ready for last call (but definitely needing a privacy NFT ERC to be made in the future to work with this ERC).

i didnt get a response to my comment, i was thinking about adding a line to the ERC saying the privacy issues would be out of scope and recommending the data be encrypted. But that was just going to be a stab in the dark to try resolve pandapips concerns

2023-05-01 17:49 UTC, closed without merging