Add EIP-4365: Redeemable Tokens
ethereum/EIPs pull request #6732
Opened 2023-03-20 19:29 UTC by LucazFFz

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

2023-03-21 02:19 UTC, abcoathup commented
EIP editors assign an EIP number (generally the PR number, but the decision is with the editors) (from: [EIP1](https://eips.ethereum.org/EIPS/eip-1#eip-numbers))

I couldn't see where an EIP editor assigned ERC4365.

2023-03-21 13:03 UTC, LucazFFz commented
>

2023-03-22 01:44 UTC, abcoathup commented
> @abcoathup Oh okay, I must have missed that. I apologize. I will remove the EIP number. However, it would be easier to keep this number since it's not taken and used extensively in the reference implementation code. I can absolutely change that if necessary.

Need to wait for an EIP editor to assign a number and then you can update the reference implementation.  I've had this before for an implementation, search and replace should resolve it quickly.

2023-03-22 18:02 UTC, Pandapip1 requested changes
Please fix the CI errors.

We're experimenting with a new automated system to assign EIP numbers. Feel free to ignore the eip walidator error about the missing `eip` header for now, and avoid self-references. Simply refer to the current eip as "this EIP", rather than by "EIP-X".

For the code, simply use descriptive names for the classes. It's much more readable than an opaque number, anyway.

2023-03-22 18:05 UTC, Pandapip1 requested changes
You get the drill.

2023-03-22 18:05 UTC, Pandapip1 commented on EIPS/eip-draft_title_abbrev.md
> +[ERC-4365](./eip-draft_title_abbrev.md) outlines a smart contract interface that can represent any number of fungible and non-fungible redeemable token types. The standard builds upon the [ERC-1155](
```suggestion
This EIP outlines a smart contract interface that can represent any number of fungible and non-fungible redeemable token types. The standard builds upon the [ERC-1155](./eip-1155.md) standard borrowing many of the ideas introduced by it including support for multiple tokens within the same contract and batch operations.
```

2023-03-22 18:05 UTC, Pandapip1 commented on EIPS/eip-draft_title_abbrev.md
> +**Every smart contract implementing this ERC MUST implement the all of the functions in the `ERC4365` interface. Additionally, they MUST implement the ERC-165 `supportsInterface` function and MUST re
```suggestion
**Every smart contract implementing this ERC MUST implement the all of the functions in the `IRedeemableToken` interface. Additionally, they MUST implement the [ERC-165](./eip-165.md) `supportsInterface` function and MUST return the constant value `true` if the constant value `0x9d1da9d1` is passed through the `interfaceId` argument.**
```

2023-03-22 18:05 UTC, Pandapip1 commented on EIPS/eip-draft_title_abbrev.md
> +interface IERC4365 is IERC165 {
```suggestion
interface IRedeemableToken is IERC165 {
```

2023-03-22 18:05 UTC, Pandapip1 commented on EIPS/eip-draft_title_abbrev.md
> +**Smart contracts MUST implement all of the functions in the `ERC4365Receiver` interface to accept tokens being minted to them.**
```suggestion
**Smart contracts MUST implement all of the functions in the `IRedeemableTokenReceiver` interface to accept tokens being minted to them.**
```

2023-03-25 02:20 UTC, abcoathup commented on EIPS/eip-draft_title_abbrev.md
> +---
I've assigned it as 6732, so you can update the EIP and your code.

2023-03-25 02:56 UTC, mspaansen approved these changes

2023-03-29 13:52 UTC, Pandapip1 commented
@eth-bot rerun

2023-04-18 16:02 UTC, SamWilsn reviewed
In addition to my other comments, would you mind reducing your reference implementation down to something more minimal? At minimum you should remove any of the OZ source. The readers can find those implementations themselves.

Generally the reference implementation should be one or two files to illustrate your proposal, and not a fully working production contract.

2023-04-20 10:08 UTC, LucazFFz commented on EIPS/eip-6732.md
> +Contrary to the ERC-1155 standard, this ERC does not enforce transferability as it recognizes situations where implementers might not want to allow it. Additionally, it introduces several extensions
Yes that is probably a good idea

2023-04-20 10:16 UTC, LucazFFz commented on EIPS/eip-6732.md
> +- [Reference implementation](../assets/eip-6732/)
Do you mean the reference implementation's readme?

2023-04-20 10:23 UTC, LucazFFz commented on assets/eip-6732/contracts/Migrations.sol
Would it be sufficient to keep the files under the examples and token folders and remove the rest including utils and migrations?

2023-05-04 19:47 UTC, SamWilsn commented on EIPS/eip-6732.md
> +- [Reference implementation](../assets/eip-6732/)
Yeah, if you cram the whole reference implementation into a single file, just link to that. If not, you can make a `README.md` that's just a manual listing of files:

```markdown
# ERC-XXXX Reference Implementation

 * [SomeContract.sol](./SomeContract.sol)
 * [MagicInterface.sol](./MagicInterface.sol)
```

2023-05-04 19:48 UTC, SamWilsn commented on assets/eip-6732/contracts/Migrations.sol
That sounds reasonable, yes.

2023-09-13 21:42 UTC, SamWilsn requested changes
You'll also still need to remove external links and build files from your reference implementation.

2023-09-13 21:42 UTC, SamWilsn commented on EIPS/eip-6732.md
> +- Implementers are RECOMMENDED to override the `_beforeMint` hook to increment total supply upon minting and decrement upon burning.
The `_beforeMint` function is part of the reference implementation, not the specification itself. The Specification section should be understandable on its own without the other sections, while the reference implementation should help to clarify what's in the the Specification section.

```suggestion
```

2023-10-25 22:05 UTC, SamWilsn commented
I am closing this pull request because we are in the process of separating EIPs and ERCs into distinct repositories. Unfortunately, as far as we are aware, GitHub does not provide any tools to ease this migration, so every pull request will need to be re-opened manually.

As this is a PR to create / modify an ERC, I will kindly ask you to redirect this to the new repository at [ethereum/ERCs](https://github.com/ethereum/ERCs). **We have prepared [a guide](https://github.com/ethereum/ERCs/issues/8) to help with the process.**

If there is relevant history here, please link to this PR from the new pull request.

On behalf of the EIP Editors, I apologize for this inconvenience.

2023-10-25 22:05 UTC, closed without merging