Initial submission of L2 Token List Draft
ethereum/EIPs pull request #6734
Opened 2023-03-20 22:40 UTC by Therecanbeonlyone1969

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

2023-03-22 16:41 UTC, Pandapip1 commented
@eth-bot rerun

2023-03-22 16:48 UTC, Pandapip1 commented
@eth-bot rerun

2023-03-22 16:58 UTC, Pandapip1 commented
@eth-bot rerun

2023-03-22 17:58 UTC, Pandapip1 requested changes
Please fix the CI errors.

2023-03-22 21:32 UTC, Therecanbeonlyone1969 commented
> Please fix the CI errors.

@Pandapip1 done

2023-03-23 03:11 UTC, abcoathup commented on EIPS/eip-00000.md
> +eip: 00000
```suggestion
eip: 6734
```
ERC number is generally the PR number.

2023-06-13 16:00 UTC, Therecanbeonlyone1969 commented
@Pandapip1 ... please approve this PR to move this EIP to Draft. It has been sitting in a ready state for over a month. There is no reason not to merge.

2023-06-27 15:31 UTC, SamWilsn commented on EIPS/eip-6734.md
> +Weijia Zhang, Peter Robinson, "EIP-3220: Crosschain Identifier Specification [DRAFT]," Ethereum Improvement Proposals, no. 3220, October 2020.
It is sufficient to list normative EIP references in the `requires:` preamble header, and directly link to them using normal markdown syntax (eg. `[EIP-3220](./eip-3220.md)`.)

```suggestion
```

2023-06-27 15:31 UTC, SamWilsn commented on EIPS/eip-6734.md
> +JSON-LD 1.1, M. Sporny, D. Longley, G. Kellogg, M. Lanthaler, Pierre-Antoine Champin, N. Lindström, W3C Recommendation, July 2020
W3C standards can be directly linked to using normal markdown syntax (using the format [mentioned in EIP-1](https://eips.ethereum.org/EIPS/eip-1#world-wide-web-consortium-w3c).)

```suggestion
```

2023-06-27 17:51 UTC, Therecanbeonlyone1969 commented on EIPS/eip-6734.md
> +Example : It should be read that [R1] is an absolute requirement of the specification whereas [D1] is a recommendation and [O1] is truly optional.
it is consistent with RFC2119 which is the common format used by W3C, OASIS, etc.

2023-06-27 17:57 UTC, Therecanbeonlyone1969 commented on EIPS/eip-6734.md
> +* Identify and document characteristics of Layer 2 Blockchain environments for EVM compatible public blockchains that will be key in addressing mainstream and enterprise adoption.
ok

2023-06-27 18:05 UTC, Therecanbeonlyone1969 commented on EIPS/eip-6734.md
> +The schema for a canonical token list utilizes draft version 7 of json-schema.org for consistency purposes with the W3C CCG effort.
removed

2023-06-27 18:15 UTC, Therecanbeonlyone1969 commented on EIPS/eip-6734.md
> +
done

2023-06-27 18:18 UTC, Therecanbeonlyone1969 commented on EIPS/eip-6734.md
> +
avoids replicating the links everywhere ... also maintains consistency with OASIS standards. So prefer to keep it this way if it is not a hard requirement.

2023-06-27 18:19 UTC, Therecanbeonlyone1969 commented on EIPS/eip-6734.md
> +JSON-LD 1.1, M. Sporny, D. Longley, G. Kellogg, M. Lanthaler, Pierre-Antoine Champin, N. Lindström, W3C Recommendation, July 2020
done

2023-06-27 18:22 UTC, Therecanbeonlyone1969 commented on EIPS/eip-6734.md
> +Weijia Zhang, Peter Robinson, "EIP-3220: Crosschain Identifier Specification [DRAFT]," Ethereum Improvement Proposals, no. 3220, October 2020.
ok. did that already but for ease of reference added them in where explicitly referenced. hope that is still acceptable.

2023-06-27 18:25 UTC, Therecanbeonlyone1969 commented on EIPS/eip-6734.md
> +T. Berners-Lee, R. Fielding,  L. Masinter, Uniform Resource Identifier (URI): Generic Syntax, IETF RFC 3986, January 2005
done

2023-06-27 18:34 UTC, Therecanbeonlyone1969 commented on EIPS/eip-6734.md
> +CVE-2021-42574, NIST Publication, 2021
Yes totally ... I think the NIST operated National Vulnerability Data base is a suitable source to list in EIP-1 -- https://nvd.nist.gov/vuln/detail/CVE-2021-42574

2023-06-27 19:17 UTC, Therecanbeonlyone1969 commented
@SamWilsn only the NIST CVE link is giving problems. Can the Editors add the NIST NVD to the list of allowed references?

2023-07-11 15:24 UTC, SamWilsn commented on EIPS/eip-6734.md
> +This standard will build upon the current framework and augment it with concepts from the W3C DID Specification [[1]](https://www.w3.org/TR/2022/REC-did-core-20220719/) based on the JSON linked data
Please format all links as plain markdown links using the title of the standard as the anchor text.

```suggestion
This standard will build upon the current framework and augment it with concepts from [Decentralized Identifiers (DIDs)](https://www.w3.org/TR/2022/REC-did-core-20220719/) based on the JSON linked data model [JSON-LD](https://www.w3.org/TR/2020/REC-json-ld11-20200716/) such as resolvable unique resource identifiers (URIs) and JSON-LD schemas which enable easier schema verification using existing tools.
```

2023-07-11 15:24 UTC, SamWilsn commented on EIPS/eip-6734.md
> +-----
```suggestion
```

2023-07-11 15:24 UTC, SamWilsn commented on EIPS/eip-6734.md
> +
```suggestion
```

2023-07-11 15:24 UTC, SamWilsn commented on EIPS/eip-6734.md
> +The standard is extending and clarifying current custom lists such as from Arbitrum and Optimism as referenced in the [Motivation](#motivation) or the Uniswap Tokenlist Project to improve clarity, se
The rationale section should justify technical choices made within the EIP itself, while the motivation justifies the EIP as a whole.

2023-07-31 18:14 UTC, Therecanbeonlyone1969 commented
@SamWilsn addressed your requests. The last open item is to add NIST to the list of allowed URLs. Is there anything I need to in terms of the process to request that?

2023-08-22 15:52 UTC, SamWilsn commented
> @SamWilsn addressed your requests. The last open item is to add NIST to the list of allowed URLs. Is there anything I need to in terms of the process to request that?

You'll need to open a pull request to EIP-1 to add it, following the guidelines in [EIP-5757](https://eips.ethereum.org/EIPS/eip-5757). I'll add it to tomorrow's EIPIP call to discuss.

2023-08-30 20:00 UTC, SamWilsn commented
https://github.com/ethereum/EIPs/pull/7542 <- pull request to allow links to NIST CVEs

2023-09-13 21:50 UTC, SamWilsn commented on EIPS/eip-6734.md
> +There are no additional security requirements apart from the warnings that URIs utilized in implementations of this standard might be direct to malicious resources such as websites, and that implemen
```suggestion
There are no additional security requirements apart from the warnings that URIs utilized in implementations of this standard might be direct to malicious resources such as websites, and that implementers should ensure that data utilized for a canonical token list is secure and correct. Since this standard is focused on a data schema and its data properties there are no additional security considerations from for example homoglyph attacks (see [CVE-2021-42574 (2021-10-25T12:38:28)](https://nvd.nist.gov/vuln/detail/CVE-2021-42574)).
```

Until `eipw` is updated to support links to CVEs, all pull requests to this EIP will require a manual merge. Sorry about the inconvenience!

2023-09-13 21:51 UTC, merged