Update eip-6366 following the suggestion from Victor
ethereum/EIPs pull request #6770
Opened 2023-03-24 03:39 UTC by chiro-hiro

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

2023-03-24 09:53 UTC, vdusart submitted a review, later dismissed

2023-03-24 10:24 UTC, chiro-hiro commented
@eth-bot rerun

2023-04-04 15:34 UTC, SamWilsn requested changes
This proposal needs to have a fleshed out rationale section before it can move into review.

---

Line 166 has:

> SHOULD NOT expected `IEIP6366Error` interface was implemented.

I'm not sure what that means.

2023-04-04 15:34 UTC, SamWilsn commented on EIPS/eip-6366.md
> +This EIP offers an alternative to Access Control Lists (ACLs) for granting authorization and enhancing security. An `uint256` is used to store permission of given address in a ecosystem. Each permiss
```suggestion
This EIP offers an alternative to Access Control Lists (ACLs) for granting authorization and enhancing security. A `uint256` is used to store permission of given address in a ecosystem. Each permission is represented by a single bit in a `uint256` as described in [ERC-6617](./eip-6617.md). Bitwise operators and bitmasks are used to determine the access right which is much more efficient and flexible than `string` or `keccak256` comparison.
```

2023-04-10 01:21 UTC, chiro-hiro commented
> This proposal needs to have a fleshed out rationale section before it can move into review.
> 
> Line 166 has:
> 
> > SHOULD NOT expected `IEIP6366Error` interface was implemented.
> 
> I'm not sure what that means.

This interface is optional.

2023-04-14 14:41 UTC, SamWilsn commented
> This interface is optional.

Don't tell me, put it in the EIP :stuck_out_tongue: 

Perhaps:

```markdown
Compatible tokens MAY implement `IEIP6366Error` as defined below:
```

2023-09-13 21:55 UTC, SamWilsn commented
Looks like line 166 still needs to be updated, and I can't modify your branch. Please update the line, and we can move this proposal to review.

2023-09-22 07:47 UTC, chiro-hiro commented
@eth-bot rerun

2023-09-22 07:50 UTC, chiro-hiro commented
Hi @SamWilsn, I have updated this EIP following your request and also link the metadata interface to [EIP-6617](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-6617.md)

2023-09-22 15:43 UTC, SamWilsn commented
Looks like line 166 is still the old text:

> SHOULD NOT expected `IEIP6366Error` interface was implemented.

---

Is ERC-6617 ready to go to review as well? You'll need to open a PR for that too.

2023-09-22 17:16 UTC, chiro-hiro commented
Hi @SamWilsn, sorry! I pushed to wrong branch. Now everything is updated.

> Is ERC-6617 ready to go to review as well? You'll need to open a PR for that too.
Yes, ERC-6617 was moved to review.

2023-09-28 09:55 UTC, vdusart commented on EIPS/eip-6366.md
> +description: A new token that holds the permission of an address in an ecosystem
Here I will perhaps remove the `new` word
```suggestion
description: A token that holds the permission of an address in an ecosystem
```

2023-09-28 09:55 UTC, vdusart commented on EIPS/eip-6366.md
>  created: 2022-01-19
It requires 6617 
```suggestion
created: 2022-01-19
requires: 6617
```

2023-10-10 09:35 UTC, chiro-hiro commented
Hi @SamWilsn,

I updated EIP-6366
- Moved `Metadata` to `EIP-6617`
- Remove example files
- Fix the description of `Error Interface`

CC: @vdusart

2023-10-16 08:37 UTC, vdusart approved these changes

2023-10-24 00:55 UTC, SamWilsn approved these changes

2023-10-24 00:55 UTC, merged