Add EIP: Smart contact HTTP requests
ethereum/EIPs pull request #6992
Opened 2023-05-05 20:06 UTC by JKincorperated

As the transition from web2 to web3 some API's and services are not compatible with smart contract. This EIP allows for smart contracts to make HTTP requests without "making the worlds larges DDoS machine"

2023-05-08 22:41 UTC, sullof commented
@JKincorperated  
You can fix the failing check adding 
```
eip: 6992
```
as first premble.

2023-05-09 07:14 UTC, JKincorperated commented
> @JKincorperated You can fix the failing check adding
> 
> ```
> eip: 6992
> ```
> 
> as first premble.

Thanks, should be fixed now.

2023-05-11 20:59 UTC, Pandapip1 requested changes
Why not just take advantage of the fact that servers sign the body with their certificate when using HTTPS?

2023-05-12 12:41 UTC, JKincorperated commented
> Why not just take advantage of the fact that servers sign the body with their certificate when using HTTPS?

It is not possible. TLS is engineered is for encryption not signing and uses symmetric cryptography, verifying the certificate might overload smaller web servers whereas DNS servers can handle the request easily, it would be unnecessary bloat to implement a custom system to make web requests instead of using the many modules available and webservers don't even sign the body parameter.

2023-05-12 14:21 UTC, Pandapip1 commented
> It is not possible. TLS is engineered is for encryption not signing and uses symmetric cryptography, verifying the certificate might overload smaller web servers whereas DNS servers can handle the request easily, it would be unnecessary bloat to implement a custom system to make web requests instead of using the many modules available and webservers don't even sign the body parameter.

I'm afraid you're wrong here. Servers using TLS **do** provide a cryptographic signature. Here's an implementation: https://old.tlsnotary.org/

2023-05-12 15:19 UTC, JKincorperated commented
> 
> I'm afraid you're wrong here. Servers using TLS **do** provide a cryptographic signature. Here's an implementation: https://old.tlsnotary.org/

I never knew that someone has implemented this, however it would still be easier to implement this as it only uses common algorithms that should already have widespread coverage across languages. Also, using DNS would stop all of the nodes basically DDoSing that single web server for verification.

2023-05-12 17:18 UTC, JKincorperated commented
> It's easy to avoid this DDoS effect. Simply add data to proposed blocks that include HTTP request and response data.

That's the issue, to verify that that domain has responded every node must have the key and no one client could **ever** send it with the request to maintain security.

2023-05-15 20:04 UTC, lightclient requested changes
It's not possible to validate this regardless because you can get different responses for the http request. It would be trivial to split the network this way.

2023-05-15 21:57 UTC, JKincorperated commented
> It's not possible to validate this regardless because you can get different responses for the http request. It would be trivial to split the network this way.

The request is passed via call data, along with a signature of the body which has been signed by a key hosted via DNS. The data inside the request can vary, however the signature must remain and be verifiable via querying the key at the domain the request originated from. This should not split the network as the request is passed through calldata.

2023-05-16 02:32 UTC, Pandapip1 commented
I think this would be better as an ERC or precompile. Probably the former.

2023-05-16 06:20 UTC, JKincorperated commented
> I think this would be better as an ERC or precompile. Probably the former.

Would changing it to an ERC effect how the opcode is implemented?

2023-05-16 09:58 UTC, lightclient commented
@JKincorperated you say
> the server must make a DNS query to a TXT located in the domain field at the subdomain

it isn't clear if you mean the node here during the operation of the opcode - if so, then the dns server may send different reponses to the TXT query how ever it feels.

2023-05-16 10:44 UTC, JKincorperated commented
I see what you mean now, I have adjusted it so the opcode just verifies an ECC DSS signature.

2023-05-16 11:27 UTC, lightclient commented
Now that this is a pure cryptographic function, it should be defined as a precompile. We don't really implement cryptographic primitives as opcodes. Check out the format from EIP-152 for inspiration: https://eips.ethereum.org/EIPS/eip-152

2023-05-16 16:29 UTC, JKincorperated commented
I just finished changing the specs so it is a precompile, as before I started this I had no idea what a precompiled contract was, after 30 minutes of intense googling, I have adjusted the EIP accordingly. 

Also the EIP Walidator is being annoying and does not like my Ethereum magicians link.

2023-05-30 15:37 UTC, SamWilsn commented on EIPS/eip-6992.md
> +The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described
Please move this paragraph to the top of the specification section.

2023-05-30 15:37 UTC, SamWilsn commented on EIPS/eip-6992.md
> +Opcode : 0xa5
Is this proposal creating a precompile or an opcode?

2023-05-30 15:37 UTC, SamWilsn commented on EIPS/eip-6992.md
> +This EIP allows for smart contracts to verify DSS signatures.
Is this not possible today with `ecrecover`?

2023-05-30 17:49 UTC, JKincorperated commented
When I saw "ecrecover" I misread and did not think is was for verifying ECC signatures. As the EIP does exactly that, I am closing it.

2023-05-30 17:49 UTC, closed without merging