Add eip-draft_offchain_checks.md
ethereum/EIPs pull request #7099
Opened 2023-05-31 05:58 UTC by civia-code

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

2023-06-01 08:50 UTC, civia-code commented
Discussion at https://ethereum-magicians.org/t/eip-7099-off-chain-checks/14526

2023-07-25 02:38 UTC, lightclient requested changes
Seems okay, couple nits. Overall this seems very similar to a payment channel though. Is there a reason to standardize this instead of simply using a state channel? Even if not, what is beneficial about standardizing this?

2023-07-25 02:38 UTC, lightclient commented on EIPS/eip-7099.md
> +title: Offchain checks for ERC-20 distribution
```suggestion
title: Off-chain checks for ERC-20 distribution
```

2023-07-25 02:38 UTC, lightclient commented on EIPS/eip-7099.md
> +We propose a low cost approach to distribute [ERC-20](./eip-20.md) tokens for high-frequency token issuance use cases such as game rewards, implemented with a one-time deployed Check contract, the of
Sentence is a bit of a run on.

2023-07-25 02:38 UTC, lightclient commented on EIPS/eip-7099.md
> +## Backwards Compatibility
```suggestion
```
Section is optional, no need to include if nothing relevant is in the section.

2023-10-25 22:14 UTC, SamWilsn commented
I am closing this pull request because we are in the process of separating EIPs and ERCs into distinct repositories. Unfortunately, as far as we are aware, GitHub does not provide any tools to ease this migration, so every pull request will need to be re-opened manually.

As this is a PR to create / modify an ERC, I will kindly ask you to redirect this to the new repository at [ethereum/ERCs](https://github.com/ethereum/ERCs). **We have prepared [a guide](https://github.com/ethereum/ERCs/issues/8) to help with the process.**

If there is relevant history here, please link to this PR from the new pull request.

On behalf of the EIP Editors, I apologize for this inconvenience.

2023-10-25 22:14 UTC, closed without merging