Add IETF as a permissible origin
ethereum/EIPs pull request #7113
Opened 2023-06-01 01:21 UTC by SamWilsn

Originally from https://github.com/ethereum/EIPs/pull/6691 by @kdenhartog.

Splitting out so it can be discussed separately.

Changed slightly with my review feedback.

2023-06-01 02:34 UTC, kdenhartog submitted a review, later dismissed
LGTM thanks for following up on this since I never got back to it. I'll convert mine to focus just on WHATWG since I'm going to what to reference it in EIP-6963

2023-06-02 12:21 UTC, Pandapip1 requested changes
Again, I think we should ensure that EIP authors use the right reference (`RFC X`)

2023-06-02 12:21 UTC, Pandapip1 commented on EIPS/eip-1.md
> +### Internet Engineering Task Force (IETF)
Again, would mildly prefer thr following:


```suggestion
### IETF Request for Comments (RFC)
```

2023-06-02 12:21 UTC, Pandapip1 commented on EIPS/eip-1.md
> +Links to a Request For Comment (RFC) specification may be included using normal markdown syntax, such as:
```suggestion
Links to an IETF Request For Comment (RFC) specification may be included using normal markdown syntax, such as:
```

2023-06-17 23:43 UTC, merged