Update EIP-5725: Move to Last Call
ethereum/EIPs pull request #7180
Opened 2023-06-14 23:37 UTC by DeFiFoFum

![last call cat](https://media.giphy.com/media/LHZyixOnHwDDy/giphy.gif)

2023-06-29 21:24 UTC, efeDaniels commented
![banana-hello](<https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNmtsbWtlZjIwNHBocmFrNjRodzB5bHBtdTRlYm41ajRoZG5tdGFwMiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/5FDfOtafB4Gnwr9dBm/giphy.gif>)

2023-08-22 14:52 UTC, SamWilsn commented on EIPS/eip-5725.md
> +last-call-deadline: 2023-08-11
Unfortunately I can't edit your PR directly, but:

```suggestion
last-call-deadline: 2023-09-05
```

2023-08-24 21:53 UTC, DeFiFoFum commented
@SamWilsn Thanks so much for the review! 🙏 I have update the last call date to your recommended.

2023-08-28 17:22 UTC, SamWilsn requested changes

2023-08-28 17:22 UTC, SamWilsn commented on assets/eip-5725/contracts/mocks/ERC20Mock.sol
> +// SPDX-License-Identifier: GPL-3.0
Assets included with your proposal should be CC0-1.0, and must impose minimal restrictions on downstream projects. It isn't much of a reference implementation if everyone who looks at it is bound to use the GPL.

2023-08-28 17:22 UTC, SamWilsn commented on EIPS/eip-5725.md
> +A reference implementation of this EIP can be found in [ERC-5725 assets](../assets/eip-5725/README.md/).
I don't believe this slash is necessary.

2023-08-28 17:22 UTC, SamWilsn commented on assets/eip-5725/contracts/reference/LinearVestingNFT.sol
> +// SPDX-License-Identifier: GPL-3.0
Can't be GPL.

2023-08-28 17:22 UTC, SamWilsn commented on assets/eip-5725/contracts/reference/VestingNFT.sol
> +// SPDX-License-Identifier: GPL-3.0
Can't be GPL.

2023-08-28 20:20 UTC, DeFiFoFum commented
@SamWilsn thx for catching that. 🙏  All comments resolved. 🥳

2023-08-29 14:03 UTC, SamWilsn approved these changes

2023-08-29 14:04 UTC, merged