Add EIP: Circuit Breaker Standard
ethereum/EIPs pull request #7265
Opened 2023-07-03 06:55 UTC by diyahir

This standard outlines a smart contract interface for a Circuit Breaker that triggers a temporary halt on protocol-wide token outflows when a threshold is exceeded for a predefined metric. This circuit breaker does not assume the structure of the underlying protocol, and mainly serves as a pass-through vehicle for token outflows. In order to maintain correct internal accounting for integrated protocols, and to provide maximum flexibility for developers, developers can specify if the circuit breaker contract should delay settlement and temporarily custody outflows during the cooldown period, or revert on attempted outflows.

- Example implementation of a circuit breaker
- Interface
- 'ProtectedContract' Contract to be inherited by DeFi contract for CB best practices

2023-07-04 11:42 UTC, hell0men commented
It's a great idea. I think Forta Network Devs @dylankilkenny and other security analysts should be included in the discussion. Contract protection is their specialty.

2023-07-04 12:25 UTC, monokh commented
Would there be some scope here to support more custom circuit breaking? Some protocols don't have inflow/outflows into their contract but they do facilitate exchange and volume. If the circuit breaker could be based on a number managed by the implementing contract, that could work.

2023-07-04 13:56 UTC, DZGoldman commented
> it seems like Admin have way privileged roles here,they can execute functions likeupdateAssetParams, overrideRateLimit 
 startGracePeriod anytime , which may raise centralized risk concerns.
I think it might be a good idea to consider integrating with a [timelock](https://docs.openzeppelin.com/contracts/4.x/governance#timelock) function into the major changes here. So that if the threshold is changed significantly and affect users getting their funds out, they can have a grace period to exist the system.

The proposed standard is agnostic to what the admin is; i.e., it could, for a given app,  be decentralized / only operate on a timeline. So I don't think the standard itself needs to be opinionated on this.

2023-07-06 04:17 UTC, scglenn requested changes

2023-07-06 20:09 UTC, frangio commented on EIPS/eip-7265.md
> +```
This should enable syntax highlighting:

```suggestion
```solidity
```

2023-07-10 22:34 UTC, karmacoma-eth commented on assets/eip-7265/src/core/CircuitBreaker.sol
> +        uint256 _withdrawlPeriod,
typo in `_withdrawlPeriod`

2023-08-07 08:30 UTC, asquare08 requested changes

2023-08-08 07:42 UTC, asquare08 commented on assets/eip-7265/src/utils/LimiterLib.sol
> +            limiter.listTail = block.timestamp;
Why `block.timestamp` is used here and not `currentTickTimestamp`? It would be cleaner that way.

2023-10-18 16:47 UTC, SamWilsn commented on assets/eip-7265/test/mocks/MockToken.sol
> +// SPDX-License-Identifier: UNLICENSED
Assuming you have the authority to change the license, we require a more permissive license like:

```suggestion
// SPDX-License-Identifier: CC0-1.0
```

If you do not have authority to change the license, please remove this file.

2023-10-18 16:47 UTC, SamWilsn commented on assets/eip-7265/test/mocks/MockDeFiProtocol.sol
> +// SPDX-License-Identifier: UNLICENSED
Assuming you have the authority to change the license, we require a more permissive license like:

```suggestion
// SPDX-License-Identifier: CC0-1.0
```

If you do not have authority to change the license, please remove this file.

2023-10-18 16:47 UTC, SamWilsn commented on assets/eip-7265/test/core/user/CircuitBreakerUserOps.t.sol
> +// SPDX-License-Identifier: UNLICENSED
Assuming you have the authority to change the license, we require a more permissive license like:

```suggestion
// SPDX-License-Identifier: CC0-1.0
```

If you do not have authority to change the license, please remove this file.

2023-10-18 16:47 UTC, SamWilsn commented on assets/eip-7265/test/core/admin/CircuitBreakerEmergencyOps.t.sol
> +// SPDX-License-Identifier: UNLICENSED
Assuming you have the authority to change the license, we require a more permissive license like:

```suggestion
// SPDX-License-Identifier: CC0-1.0
```

If you do not have authority to change the license, please remove this file.

2023-10-18 16:47 UTC, SamWilsn commented on assets/eip-7265/test/core/admin/CircuitBreakerAdminOps.t.sol
> +// SPDX-License-Identifier: UNLICENSED
Assuming you have the authority to change the license, we require a more permissive license like:

```suggestion
// SPDX-License-Identifier: CC0-1.0
```

If you do not have authority to change the license, please remove this file.

2023-10-18 16:47 UTC, SamWilsn commented on assets/eip-7265/src/utils/LimiterLib.sol
> +// SPDX-License-Identifier: MIT
Assuming you have the authority to change the license, we require a more permissive license like:

```suggestion
// SPDX-License-Identifier: MIT OR CC0-1.0
```

2023-10-18 16:47 UTC, SamWilsn commented on assets/eip-7265/src/static/Structs.sol
> +// SPDX-License-Identifier: UNLICENSED
Assuming you have the authority to change the license, we require a more permissive license like:

```suggestion
// SPDX-License-Identifier: CC0-1.0
```

If you do not have authority to change the license, please remove this file.

2023-10-18 16:47 UTC, SamWilsn commented on assets/eip-7265/src/core/ProtectedContract.sol
> +// SPDX-License-Identifier: UNLICENSED
Assuming you have the authority to change the license, we require a more permissive license like:

```suggestion
// SPDX-License-Identifier: CC0-1.0
```

If you do not have authority to change the license, please remove this file.

2023-10-18 16:47 UTC, SamWilsn commented on assets/eip-7265/src/core/CircuitBreaker.sol
> +// SPDX-License-Identifier: UNLICENSED
Assuming you have the authority to change the license, we require a more permissive license like:

```suggestion
// SPDX-License-Identifier: CC0-1.0
```

If you do not have authority to change the license, please remove this file.

2023-10-18 16:47 UTC, SamWilsn commented on EIPS/eip-7265.md
> +title: Circuit Breaker
I don't think your title gives enough detail. Perhaps something like:

```suggestion
title: Asset Outflow Circuit Breaker Protection
```

2023-10-18 16:47 UTC, SamWilsn commented on EIPS/eip-7265.md
> +Security breaches have become pervasive in DeFi. Over $6 Billion dollars worth of assets were stolen in exploits. When something goes wrong, protocols are rapidly drained of the majority of TVL often
We generally prefer that the first use of an abbreviation is expanded:

```suggestion
Security breaches have become pervasive in DeFi. Over $6 Billion dollars worth of assets were stolen in exploits. When something goes wrong, protocols are rapidly drained of the majority of their total value locked (TVL) often in a matter of seconds. Although many protocols have smart contracts which are fully upgradeable by governance, in practice there is usually no time to upgrade or patch vulnerabilities before large amounts of TVL are drained.
```

2023-10-25 22:52 UTC, SamWilsn commented
I am closing this pull request because we are in the process of separating EIPs and ERCs into distinct repositories. Unfortunately, as far as we are aware, GitHub does not provide any tools to ease this migration, so every pull request will need to be re-opened manually.

As this is a PR to create / modify an ERC, I will kindly ask you to redirect this to the new repository at [ethereum/ERCs](https://github.com/ethereum/ERCs). **We have prepared [a guide](https://github.com/ethereum/ERCs/issues/8) to help with the process.**

If there is relevant history here, please link to this PR from the new pull request.

On behalf of the EIP Editors, I apologize for this inconvenience.

2023-10-25 22:52 UTC, closed without merging