Push ERC-223 to Review
ethereum/EIPs pull request #7339
Opened 2023-07-16 03:54 UTC by Dexaran

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

2023-07-30 01:52 UTC, Pandapip1 requested changes
The title cannot contain the EIP number

2023-07-30 02:01 UTC, xinbenlv commented on EIPS/eip-223.md
>  description: Token with event handling and communication model
```
- 223 Token with communication model
+ Token with communication model
```

2023-08-02 20:16 UTC, Dexaran commented on EIPS/eip-223.md
>  description: Token with event handling and communication model
Resolved https://github.com/ethereum/EIPs/commit/05c18b729fbac4af0b6efb950b3dc7cfdbaaa8f0

2023-08-02 20:18 UTC, Pandapip1 approved these changes
Fine for now.

2023-08-02 20:19 UTC, merged

2023-08-02 20:19 UTC, eip-automerger commented
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - Trying to change EIP 223 state from Draft to Review