Update  EIP-6059: Add the missing parameter to the specification
ethereum/EIPs pull request #7366
Opened 2023-07-19 22:26 UTC by ThunderDeliverer

During the proposal lifecycle from Draft to Final stage, an additional parameter was added to the `nestTransferFrom` method. This parameter is already taken into account within the `interfaceId`. This means that this PR fixes the inconsistency.

Additionally, the `ChildTransferred` event was missing an important quality of life parameter which doesn’t impact the `interfaceId`, but it does provide better usability of the proposal.

We also expanded the _Rationale_ and _Security consideration_ to be more illustrative of the proposal.

While we understand that finalized proposals are not meant to be updated, we feel like this one might benefit from the correction proposed here. Anyone that uses the proposal in their project either used our open-source library (which already included the proposed changes before the finalization) or the interface provided within the assets (which also includes the proposed changes). This means that modifying the proposal will align it with current implementations.

2023-07-20 13:40 UTC, Pandapip1 submitted a review, later dismissed
+1 because it does seem like this erratas a real mistake
-1 because it modifies a normative section of a Final EIP

Overall, I'm weakly in favor of correcting the mistake.

2023-07-24 14:58 UTC, lightclient requested changes
One serious breaking change to the API and one change to update the consistency of the spec to the reference implementation.

I'm definitely opposed to merging with the change to `ChildTransferred`. The standard is final and you shouldn't be modifying it any longer.

I might be able to be convinced to support changing `nestTransferFrom` since it does have a `data` field in the reference implementation. But it's still not great and definitely a spec change.

Please remove the elaborations in general.

2023-07-24 14:58 UTC, lightclient commented on EIPS/eip-6059.md
> +        bool toZero
this is a breaking change to the api

2023-07-24 14:58 UTC, lightclient commented on EIPS/eip-6059.md
> +        bytes memory data
breaking change

2023-07-24 14:58 UTC, lightclient commented on EIPS/eip-6059.md
> +The only incompatibility with ERC-721 is that Nestable tokens cannot use a token ID of 0.
remove

2023-07-24 14:58 UTC, lightclient commented on EIPS/eip-6059.md
> +It is worth noting that `balanceOf` method only accounts for immediate tokens owned by the address; the tokens that are nested into a token owned by this address will not be reflected in this value a
remove

2023-07-24 15:09 UTC, steven2308 commented on EIPS/eip-6059.md
> +The only incompatibility with ERC-721 is that Nestable tokens cannot use a token ID of 0.
```suggestion
```

2023-07-24 15:15 UTC, steven2308 commented
> I'm definitely opposed to merging with the change to `ChildTransferred`. The standard is final and you shouldn't be modifying it any longer.
We are well aware of this, however we contacted other implementers and they agreed this new parameter makes it easier since you can know if an NFT was soft locked (by being sent to address zero). All of them are using the open source package we provide, which includes this parameter on the event.

> I might be able to be convinced to support changing `nestTransferFrom` since it does have a `data` field in the reference implementation. But it's still not great and definitely a spec change.
This is the most critical part for us, thanks.

> Please remove the elaborations in general.
Will remove.

2023-07-24 20:43 UTC, Yuripetusko commented
> > I'm definitely opposed to merging with the change to `ChildTransferred`. The standard is final and you shouldn't be modifying it any longer.
> 
> We are well aware of this, however we contacted other implementers and they agreed this new parameter makes it easier since you can know if an NFT was soft locked (by being sent to address zero). All of them are using the open source package we provide, which includes this parameter on the event.
> 
> > I might be able to be convinced to support changing `nestTransferFrom` since it does have a `data` field in the reference implementation. But it's still not great and definitely a spec change.

Just to elaborate on this, While I fully agree that this is a no-no, and allowing a change to an ERC can open a pandora box. But in this particular case we have handful of devs looking into using this ERC right now and they are all in our workgroup, so we have direct contact with them. There are no projects that implemented this ERC in this form, with incorrect event and missing `data` argument in nestTransferFrom, as all devs use our implementation contract that have this event with missing field. And if you to allow us to add this change, this is the best time to do it, before anyone actually used it in production as per ERC rather than using our provided implementation. We will make sure to announce this change within our small workgroup too if the change makes it in.

2023-07-25 02:23 UTC, SamWilsn commented
> We are well aware of this, however we contacted other implementers and they agreed this new parameter makes it easier since you can know if an NFT was soft locked (by being sent to address zero).

This really should've happened before this ERC went to Final. That's the whole point of the review/last call statuses: give implementers time to try it out and provide feedback.

---

Final means, well... final. I'd recommend opening a new EIP, with a new number, if you'd like to make this change.

2023-07-25 02:31 UTC, closed without merging

2023-07-25 06:34 UTC, ThunderDeliverer commented
Could we perhaps at least update the `nestTransferFrom` so that the specified interface matches the interface ID as well as the example implementation?

2023-07-25 11:57 UTC, lightclient commented
I recommend opening a new EIP to completely replace this one.