Update eip-1559.md
ethereum/EIPs pull request #7423
Opened 2023-07-28 12:35 UTC by Aryan9592

This PR clarifies the language by replacing the term 'transaction' with 'senders' to explicitly identifies who pays the base and priority fee. Makes the fee payment process more understandable for new readers.

2023-07-28 12:51 UTC, lightclient approved these changes
This is slightly clearer.

2023-07-29 23:59 UTC, Pandapip1 approved these changes

2023-10-04 14:18 UTC, minimalsm requested changes

2023-10-04 14:18 UTC, minimalsm commented on EIPS/eip-1559.md
> +Senders will always pay the base fee per gas of the block their transaction was included in, and they will pay the priority fee per gas set in the transaction, as long as the combined amount of the t
```suggestion
The sender of the transaction will always pay the base fee per gas of the block their transaction was included in, and they will pay the priority fee per gas set in the transaction, as long as the combined amount of the two fees doesn't exceed the transaction's maximum fee per gas.
```

2023-10-04 14:18 UTC, g11tech approved these changes

2023-10-04 14:19 UTC, merged