ETH Address Convention
ethereum/EIPs pull request #7808
Opened 2023-10-03 21:15 UTC by Joeysantoro

2023-10-04 02:15 UTC, abcoathup commented on EIPS/eip-7808.md
> +eip: 7808
```suggestion
eip: 7528
```
Assigning next sequential EIP/ERC number.
EIP/ERC numbering changed to sequential from 7500 and is no longer the PR number.

Please also update the filename and the Eth Magicians discussion.

2023-10-04 02:16 UTC, abcoathup commented on EIPS/eip-7808.md
> +requires: [EIP-20](https://eips.ethereum.org/EIPS/eip-20), [EIP-4626](https://eips.ethereum.org/EIPS/eip-4626)
```suggestion
requires: 20, 4626
```

2023-10-04 03:15 UTC, abcoathup commented on EIPS/eip-7808.md
> +This standard allows protocols and off-chain data infrastructure to  coordinate around a shared understanding that any time 0xe is used as an address in an [EIP-20](https://eips.ethereum.org/EIPS/eip
```suggestion
This standard allows protocols and off-chain data infrastructure to coordinate around a shared understanding that any time 0xe is used as an address in an [EIP-20](https://eips.ethereum.org/EIPS/eip-20) context, it means ETH.
```

2023-10-12 20:16 UTC, Joeysantoro commented
@axic , @Pandapip1 , @SamWilsn , @xinbenlv this should be ready to move to Review!

2023-10-18 13:48 UTC, lightclient approved these changes

2023-10-18 13:49 UTC, lightclient requested changes

2023-10-18 13:49 UTC, lightclient commented on EIPS/eip-7528.md
> +status: Review
```suggestion
status: Draft
```

2023-10-18 20:11 UTC, lightclient approved these changes

2023-10-18 20:11 UTC, merged