ADD EIP: Multi-edition NFT Distribution
ethereum/EIPs pull request #7853
Opened 2023-10-15 09:13 UTC by henrywfyeung

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

2023-10-15 09:51 UTC, Bushido154 approved these changes

2023-10-17 02:29 UTC, abcoathup commented on EIPS/eip-distributor.md
> +eip: 9527
```suggestion
eip: 7536
```
Assigning next sequential EIP/ERC number.
EIP/ERC numbering changed to sequential from 7500 and is no longer the PR number.

Please also update the filename.

2023-10-18 17:53 UTC, Pandapip1 requested changes
ERCs are referenced ERC-XXXX, not `ERCXXXX`, and your multiline code blocks are missing the language

2023-10-18 18:50 UTC, Pandapip1 requested changes
Additionally: Licenses MUST be CC0-1.0, NOT MIT

2023-10-18 18:50 UTC, Pandapip1 commented on EIPS/eip-7536.md
> +Upon fulfilling the corresponding rules from a specific edition, one can obtain the child token and will be able to use the token within the boundaries set by the parent token holder.
```suggestion
This standard extends [ERC-721](./eip-721.md) to enable conditional minting of various editions of child tokens with specific privileges attached. An edition is defined as a version of a child token that encapsulates a descriptor to the parent, the address to a validator that validates rules before minting the child token, and a set of actions that can be invoked upon obtaining the child token. Each parent token can create multiple editions, each with a different set of rules to obtain the child tokens, and with different levels of privileges attached in the form of permitted actions. Upon fulfilling the corresponding rules from a specific edition, one can obtain the child token and will be able to use the token within the boundaries set by the parent token holder.
```

2023-10-18 18:50 UTC, Pandapip1 commented on EIPS/eip-7536.md
> +![Parent Child and Edition Relationship Diagram](../assets/eip-7536/assets/edition.png)
Does not belong in Abstract. Abstracts should be text-only.

2023-10-18 18:50 UTC, Pandapip1 commented on EIPS/eip-7536.md
> +This standard gives the interfaces for implementing such a tiered system. It empowers any ERC-721 tokens with the ability to create editions of child tokens that give privileges at a cost.
```suggestion
```
This is implied

2023-10-18 18:50 UTC, Pandapip1 commented on EIPS/eip-7536.md
> +## Rationale
Usage belongs more in Rationale than Spec, and the wording can be significantly improved

```suggestion
## Rationale

### Usage

The Distributor Interface enables any ERC-721 token to create multiple editions, each with distinct rules validated by the Validator Interface before minting a child token, and a set of actions available post-minting. This is advantageous for community building, with diverse use cases like:

- **Copy Issuance of Unique Artwork/Content:** Artists can issue multiple copies of their unique artworks with different functions and rules, providing flexibility to both creators and collectors.
- **Partial Copyright Transfer:** Creators can conditionally delegate varying levels of copyrights, allowing for derivative work production without selling the original copy.

Consider using this standard for:

- Selling copies of unique Art/Music NFTs while retaining control over the copies.
- Selling time-limited copies of artwork with attached copyright statements for derivative work production.
- Issuing non-transferable Graduation Certificates as NFTs, where the university retains the revocation right.
```

2023-10-18 18:50 UTC, Pandapip1 commented on EIPS/eip-7536.md
> +}
```suggestion
pragma solidity >=0.8.0 <0.9.0;

/**
 * @notice This interface enables an [ERC-721](./eip-721.md) compliant contract to mint child tokens. A contract implementing this interface SHOULD allow any ERC-721 compliant parent token to create editions. Each edition SHOULD contain an address to a contract implementing the Validator Interface for validating minting rules, record the contract address and the tokenId of the parent token, and specify a set of permissible actions via uint96 flags.
 */
interface IDistributor {

    /**
     * @dev Emitted when a new edition is created.
     * @param editionHash The hash of the edition configuration.
     * @param tokenContract The token contract of the NFT descriptor.
     * @param tokenId The token id of the NFT descriptor.
     * @param validator The address of the validator contract.
     * @param actions The permitted functions in the descriptor contract.
     */
    event SetEdition(bytes32 editionHash, address tokenContract, uint256 tokenId, address validator, uint96 actions);
    
    /**
     * @dev Emitted when an edition is paused or resumed.
     * @param editionHash The hash of the edition configuration.
     * @param isPaused The state of the edition.
     */
    event PauseEdition(bytes32 editionHash, bool isPaused);

    /**
     * @dev Allows the parent token holder to set an edition, enabling others to mint child tokens given certain conditions.
     * @param tokenContract The token contract of the Parent token.
     * @param tokenId The token id of the Parent token.
     * @param validator The address of the validator contract.
     * @param actions The permitted functions in the descriptor contract.
     * @param initData Data input into the validator contract for setting up rules; may encode additional edition parameters.
     * @return editionHash Returns the hash of the edition configuration.
     */
    function setEdition(
        address tokenContract,
        uint256 tokenId,
        address validator,
        uint96  actions,
        bytes calldata initData
    ) external returns (bytes32 editionHash);
    
    /**
     * @dev Allows the parent token holder to pause or resume an edition.
     * @param editionHash The hash of the edition.
     * @param isPaused The state of the edition.
     */ 
    function pauseEdition(
        bytes32 editionHash,
        bool isPaused
    ) external;
}
```
Copyedited

2023-10-18 18:50 UTC, Pandapip1 commented on EIPS/eip-7536.md
> +This standard consists of a Distributor Interface and a Validator Interface. The Distributor interface MUST be implemented by a [ERC-721](./eip-721.md) compliant contract that enables the minting of
```suggestion
```
This is established in the interfaces themselves

2023-10-18 18:50 UTC, Pandapip1 commented on EIPS/eip-7536.md
> +}
```suggestion
pragma solidity >=0.8.0 <0.9.0;

/**
 * @notice The Validator Interface defines rules for minting child tokens. The parent token holder registers these rules for a specific edition, identified by the edition configuration hash (editionHash). Collectors wishing to mint a child token from this edition must pass validation by successfully calling the validate function, supplying necessary information including initiator address, editionHash, and optional fulfillment data.
 */
interface IValidator {

    /**
     * @dev Initializes validator rules using the edition hash and initialization data. Decodes the data to required parameters, establishing the rules determining who can mint a copy of the edition.
     * @param editionHash The hash of the edition configuration.
     * @param initData The data bytes for initializing validation rules; parameters are encoded into bytes.
     */
    function setRules(
        bytes32 editionHash, 
        bytes calldata initData
    ) external;
    
    /**
     * @dev Validates the fulfillment of rules set by the parent token holder, using supplied data.
     * @param initiator The party initiating validation.
     * @param editionHash The hash of the edition configuration.
     * @param conditionType The type of condition for validation.
     * @param fulfillmentData Additional data required for passing validator rules.
     */
    function validate(
        address initiator, 
        bytes32 editionHash,
        uint256 conditionType,
        bytes calldata fulfillmentData
    ) external payable;

}
```
Copyedited

2023-10-18 18:50 UTC, Pandapip1 commented on EIPS/eip-7536.md
> +```
```suggestion
```solidity
```

2023-10-18 18:50 UTC, Pandapip1 commented on EIPS/eip-7536.md
> +```
```suggestion
```solidity
```

2023-10-26 17:34 UTC, SamWilsn commented
I am closing this pull request because we are in the process of separating EIPs and ERCs into distinct repositories. Unfortunately, as far as we are aware, GitHub does not provide any tools to ease this migration, so every pull request will need to be re-opened manually.

As this is a PR to create / modify an ERC, I will kindly ask you to redirect this to the new repository at [ethereum/ERCs](https://github.com/ethereum/ERCs). **We have prepared [a guide](https://github.com/ethereum/ERCs/issues/8) to help with the process.**

If there is relevant history here, please link to this PR from the new pull request.

On behalf of the EIP Editors, I apologize for this inconvenience.

2023-10-26 17:34 UTC, closed without merging