Update erc1363 to modern recommendations
ethereum/EIPs pull request #7877
Opened 2023-10-19 13:47 UTC by vittominacori

This PR wants to only update EIP content in order to follow the most updated recommendation from EIP-1.

* Some texts have been updated to better explain the ERC-1363 behavior, after years of discussion. No changes in behavior.
* Some texts have been moved from abstract or motivation to the dedicated rationale section.
* References to EIPs have been moved to the `EIP-N` format.
* Code specification have been indented and commented.
* The creation date have been updated with the date of the first issue opening and the first commit into the reference implementation (erroneously it was the date of PR instead).
* References to test cases and reference implementation have been aded as it was not permitted before (but it seems that many EIPs have them).

2023-10-23 10:15 UTC, vittominacori commented
@axic, @gcolvin, @lightclient, @Pandapip1, @SamWilsn

Is this is PR waiting for ci to pass before discussing?

These are the reason ci failed:

```
Error: error[markdown-order-section]: body has extra section(s)
  --> EIPS/eip-13[6](https://github.com/ethereum/EIPs/actions/runs/6586057763/job/17893640657?pr=7877#step:3:7)3.md
   |
13 | ## Simple Summary
```

Simple Summary has been added in the first draft of this EIP and it is still available on eip-20 or eip-721. Should this be removed?

```
Error: error[preamble-re-discussions-to]: preamble header `discussions-to` should point to a thread on ethereum-magicians.org
```

There is not link to magicians forum as it was not discussed there in 2018. It points to the issue like the eip-721

```
Error: error[preamble-req]: preamble is missing header(s): `description`
```

There is no description in original eip as it was not required. It can be simply added if required.

2023-10-23 15:54 UTC, Pandapip1 requested changes
This does not make the minimum changes necessary, and does not fully satisfy EIP-1.

2023-10-23 18:41 UTC, Pandapip1 commented
Whenever you change something, it has to comply with EIP-1. So, for example, the Simple Summary should be moved to the description preamble entry. Self-references should not be by number, etc...

If you don't change something, like the discussion link, you don't need to bring it up to date.

2023-10-23 21:03 UTC, vittominacori commented
I've submitted the suggested changes to totally apply with EIP-1.

I've move some text to the right section. I've also updated some text just to clarify the meaning as it was written in 2018 and it sound like obsolete wording.

I've not changed any code/interface (just indentation and some comments).

2023-10-26 17:30 UTC, SamWilsn commented
I am closing this pull request because we are in the process of separating EIPs and ERCs into distinct repositories. Unfortunately, as far as we are aware, GitHub does not provide any tools to ease this migration, so every pull request will need to be re-opened manually.

As this is a PR to create / modify an ERC, I will kindly ask you to redirect this to the new repository at [ethereum/ERCs](https://github.com/ethereum/ERCs). **We have prepared [a guide](https://github.com/ethereum/ERCs/issues/8) to help with the process.**

If there is relevant history here, please link to this PR from the new pull request.

On behalf of the EIP Editors, I apologize for this inconvenience.

2023-10-26 17:30 UTC, closed without merging