all: update link to new ercs repo
ethereum/EIPs pull request #7922
Opened 2023-10-25 15:44 UTC by lightclient

Missed in #7206: the new ERCs repo has a folder `ERCS` similar to our `EIPS`. This is case sensitive in the path causing the redirects here to fail. This PR fixes the URLs accordingly.

2023-10-25 15:45 UTC, merged

2024-03-04 06:30 UTC, stvnreaves commented
[]()

2024-12-09 08:41 UTC, Andrade110895 requested changes

2024-12-09 08:41 UTC, Andrade110895 commented on EIPS/eip-1191.md
> +This file was moved to https://github.com/ethereum/ercs/blob/master/ERCS/erc-1191.md
4000 para miy

2024-12-09 08:41 UTC, Andrade110895 commented on EIPS/eip-1417.md
> -This file was moved to https://github.com/ethereum/ercs/blob/master/ercs/erc-1417.md
🎲5000$