Removes EIP-7212 as was moved to the RIPs repo as RIP-7212 now
ethereum/EIPs pull request #8101
Opened 2024-01-09 20:14 UTC by CarlBeek

As an artifact of the new RIP process, EIP-7212 has been converted from an EIP to an RIP. As RIP-7212 has already been created and there are no EIPs that depend on EIP-7212, it makes sense to just delete here to complete the move. CC @poojaranjan @ulerdogan

2024-01-09 20:24 UTC, ulerdogan requested changes
Hello Carl. Thanks for applying decided changes on EIP->RIP process. I recommend also deleting following files which are referenced by the EIP:
- [p256Verify_benchmark_test](./assets/eip-7212/p256Verify_benchmark_test)
- [ecrecover_benchmark_test](./assets/eip-7212/ecrecover_benchmark_test)

2024-01-09 20:46 UTC, CarlBeek commented
ACK, thanks @ulerdogan, `./assets/eip-7212/` removed too

2024-01-09 20:53 UTC, ulerdogan approved these changes
Thanks, I think ready to go!

RIP EIP-7212 😢🪦

<img src="https://media1.tenor.com/m/bl_3kYhSzsgAAAAC/spongebob-rip-sad-sponge-bob.gif">

2024-01-09 21:00 UTC, poojaranjan commented
Perhaps we can "move" and not "remove". 

At the time of EIP/ERC split many ERCs were moved out of EIPs repo but ERC history was preserved. Like [this](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-6982.md).

2024-01-09 21:14 UTC, CarlBeek commented
Interesting, I like it. I will update to do that instead

2024-01-09 21:20 UTC, CarlBeek commented on EIPS/eip-7212.md
> +category: EIP
Question: should this be `category: RIP` instead?

```suggestion
category: RIP
```

2024-01-10 10:53 UTC, ulerdogan commented
We don't have `RIP` category defined on the EIP-1. Do we need a change there? I think we can keep as it is in the `Core` category as EIP itself was a 'Core EIP' similar to the moved ERCs' categories were still ERC.

2024-01-10 15:31 UTC, poojaranjan commented
@ulerdogan 

> We don't have RIP category defined on the EIP-1. Do we need a change there? 

As we progress with a proposal, an author gets more clarity on the Type/Category. Changing either or both for a proposal before it is moved to `Final` is fine

There is a general agreement on adding RIP as a Standard Track Category discussed in [EIPIP Meeting 95](https://www.youtube.com/watch?v=qgcphJxvVDs). 

We were hoping to have the PR to EIP-1 coming in by RIP working group. But, it can be made by anyone.

2024-05-03 01:24 UTC, HoangTranMap commented
OK all

Vào 7:20, Th 6, 3 thg 5, 2024 github-actions[bot] ***@***.***>
đã viết:

> There has been no activity on this pull request for 2 weeks. It will be
> closed after 3 months of inactivity. If you would like to move this PR
> forward, please respond to any outstanding feedback or add a comment
> indicating that you have addressed all required feedback and are ready for
> a review.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ethereum/EIPs/pull/8101#issuecomment-2091943311>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BH4WUEM7ZEIMWH4POB2AGEDZALJ3PAVCNFSM6AAAAABBTVVBO6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAOJRHE2DGMZRGE>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2024-06-22 20:29 UTC, Scamreno approved these changes

2024-06-22 20:30 UTC, Scamreno approved these changes
#8101

2024-06-22 20:32 UTC, Scamreno approved these changes
#8101 #8650 #8649 #8650 #8546

2024-06-22 20:33 UTC, Scamreno commented
#8101

2024-06-22 20:36 UTC, Scamreno approved these changes

2024-06-22 20:39 UTC, Scamreno commented
Just trying to find a way to get some of my money coming in because I haven't received anything since I started this in 2013

2024-09-03 14:26 UTC, closed without merging