Move to Last Call
ethereum/EIPs pull request #8153
Opened 2024-01-31 16:00 UTC by timbeiko

5656 is part of Dencun, which is going live.

2024-01-31 17:12 UTC, jwasinger approved these changes

2024-01-31 21:50 UTC, SamWilsn requested changes
Please fill out the Security Considerations section. I assume there's very little risk of DoS or memory exhaustion attacks, right?

2024-02-01 14:00 UTC, timbeiko commented
cc: @charles-cooper

2024-02-01 14:34 UTC, charles-cooper commented
> cc: @charles-cooper

am i able to modify this branch directly?

2024-02-01 14:34 UTC, charles-cooper commented
> Please fill out the Security Considerations section. I assume there's very little risk of DoS or memory exhaustion attacks, right?

yes, the analysis for DoS and memory exhaustion is the same as other opcodes which touch memory, as the memory expansion is priced the same.

2024-02-01 16:52 UTC, timbeiko commented
> am i able to modify this branch directly?

feel free to create a new one if that's easier, and add the status change as part of the same PR!

2024-02-07 02:26 UTC, timbeiko commented on EIPS/eip-5656.md
> +last-call-deadline: 2024-02-15
```suggestion
last-call-deadline: 2024-02-20
```

2024-02-07 02:26 UTC, timbeiko commented
@charles-cooper I added a line based on your comment, thanks!

2024-02-07 02:34 UTC, charles-cooper commented
we should probably add the additional line to the security considerations:

"Clients should take care that their implementation does *not* use an intermediate buffer (see for instance that the C stdlib `memmove` function does not use an intermediate buffer, per the Notes section of the documentation of [memmove](https://en.cppreference.com/w/cpp/string/byte/memmove), as this is a potential DoS vector. Most language builtins / standard library functions for moving bytes have the correct performance characteristics here."

2024-02-07 14:45 UTC, timbeiko commented
Added, thanks @charles-cooper! @SamWilsn, we're ready to merge

2024-02-07 15:19 UTC, timbeiko commented on EIPS/eip-5656.md
> +cccccbhbldkgfgvfhrbkedvhrjrebvruhuhubfdvlrhf
```suggestion
---
```

2024-02-08 15:04 UTC, SamWilsn approved these changes

2024-02-08 15:05 UTC, merged

2024-02-08 15:05 UTC, eip-automerger commented
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - Trying to change EIP 5656 state from Review to Last Call