Update eip-1193.md: author username
ethereum/EIPs pull request #8290
Opened 2024-03-07 21:11 UTC by wolovim

updated username in 2022; airdrop farmer registered the old one a few weeks ago.

2024-03-08 03:33 UTC, lightclient approved these changes

2024-03-08 03:34 UTC, lightclient commented
I am okay with this change and have verified @wolovim is the same human being who co-authored this EIP!

2024-03-08 13:03 UTC, xinbenlv commented
While I am personally in favor of merging this PR and allowing updating author even in Final EIP, updating authors in a Final EIP is considered disallowed per https://github.com/ethcatherders/EIPIP/issues/308

I urge my fellow EIP Editor peer to consider updating this policy other wise unfortunately we will have to reject this PR

2024-03-09 01:03 UTC, SamWilsn requested changes
[Call for Input: Update Author's Username in EIP-1193](https://github.com/ethcatherders/EIPIP/issues/325)

2024-04-10 18:15 UTC, SamWilsn approved these changes

2024-04-10 18:15 UTC, merged

2025-01-13 07:54 UTC, Tru2thisNu approved these changes

2025-01-13 07:54 UTC, Tru2thisNu approved these changes