add ERC-4377:A Protocol for ERC20 Tokens Which Released Based On Predefined Periods
ethereum/EIPs pull request #8348
Opened 2024-03-22 03:06 UTC by erc4377

A protocol for ERC20 tokens which released based on predefined periods controlled by smart contracts, enhancing the ERC repository. 
The smart contract allows token released based on predefined periods, enabling lock token balances and gradually release tokens.
**ATTENTION: ERC-RELATED PULL REQUESTS NOW OCCUR IN [ETHEREUM/ERCS](https://github.com/ethereum/ercs)**

--

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

2024-03-22 09:20 UTC, abcoathup commented on EIPS/eip-4377.md
> +eip: 4377
```suggestion
eip: 
```
ERC numbers are issued by editors & associates.  They are now sequential.

Once you have created a PR in the ERC repo a number will be manually issued.

2024-03-22 09:22 UTC, abcoathup commented
To create an ERC (application layer) please close this PR and create a new PR in the ERC repo: https://github.com/ethereum/ERCs

2024-03-24 06:33 UTC, abcoathup commented
@erc4377 please close this PR now that you have created a PR in the ERC repo: https://github.com/ethereum/ERCs/pull/341

2024-04-15 15:39 UTC, gaudren requested changes

2024-04-15 15:39 UTC, gaudren commented on EIPS/eip-4377.md
> +title: A Protocol for ERC20 Tokens Which Released Based On Predefined Periods Controlled by Smart Contracts
Titles must be 45 characters or less. Please rework it to be more succinct.

2024-04-15 15:39 UTC, gaudren commented on EIPS/eip-4377.md
> +The smart contract allows token released based on predefined periods, enabling lock token balances and gradually release tokens.
Re-states same information as the line above:

```suggestion
```

2024-04-15 15:39 UTC, gaudren commented on EIPS/eip-4377.md
> +5. Low-Cost Swap Algorithm.
This should be in the Motivation section.

2024-04-15 15:39 UTC, gaudren commented on EIPS/eip-4377.md
> + canReleaseAmount = total * (currentTimestamp - startTime) / duration;
```suggestion
 `canReleaseAmount = total * (currentTimestamp - startTime) / duration;`
```

2024-04-15 15:39 UTC, gaudren commented on EIPS/eip-4377.md
> +Our team has introduced a novel “Sorter” mechanism in this protocol, which automatically consolidates multiple transfers in smart contracts. This feature ensures token release based on different tran
```suggestion
This proposal introduces a novel “Sorter” mechanism in this protocol, which automatically consolidates multiple transfers in smart contracts. This feature ensures token release based on different transfer times while minimizing gas fees significantly. 
```

2024-04-15 15:39 UTC, gaudren commented on EIPS/eip-4377.md
> +A protocol for ERC20 tokens which released based on predefined periods controlled by smart contracts, enhancing the ERC repository.
```suggestion
A protocol for ERC20 tokens which released based on predefined periods controlled by smart contracts. 
```

2024-04-15 15:39 UTC, gaudren commented on EIPS/eip-4377.md
> +Customized White List: Specified addresses or contracts are exempted from the above features and locking restrictions, allowing this protocol to be widely and properly applied. For example, Uniswap c
```suggestion
Customized Whitelist: Specified addresses or contracts are exempted from the above features and locking restrictions, allowing this protocol to be widely and properly applied. Examples include Uniswap contracts, and treasury addresses.
```

You might want to explain how these examples are relevant.

2024-04-15 15:39 UTC, gaudren commented on EIPS/eip-4377.md
> +The motivation behind this protocol is to enrich the ERC repository. By allowing ERC20 tokens to have custom linear release schedules, lock-up mechanisms, and whitelisting, this protocol can find app
```suggestion
By allowing ERC-20 tokens to have custom linear release schedules, lock-up mechanisms, and whitelisting, this protocol can find applications in scenarios such as MEME tokens, games, DAO organizations, and options trading.
```

2024-04-15 15:39 UTC, gaudren commented on EIPS/eip-4377.md
> +## Rationale
This doesn't explain the choices you have made for this EIP, and code block should generally be included in the Reference Implementation. Use this section to help the reader understand why you have done something in plain English.

2024-04-15 15:39 UTC, gaudren commented on EIPS/eip-4377.md
> +## Specification
You don't have any specifications. What is an implementer supposed to do?

2024-04-15 15:39 UTC, gaudren commented on EIPS/eip-4377.md
> +Roy Davies(roydj2021@gmail.com), Ali Kaya (ali.kayatur747@gmail.com), "ERC-4377: A Protocol for ERC20 Tokens Which Released Based On Predefined Periods Controlled by Smart Contracts [DRAFT]," Ethereu
```suggestion
```

This section will be generated automatically when rendered.

2024-07-25 00:19 UTC, closed without merging