add sentence to make atomicBatch more explicitly one-chain-at-a-time
ethereum/EIPs pull request #8626
Opened 2024-06-06 08:55 UTC by bumblefudge

As per a conversation with @pedrouid and @jxom

2024-06-10 17:14 UTC, lukasrosario requested changes
requesting that we make the expected behavior for calls across chains clearer. specifically, do calls on one chain need to land before executing calls on the next chain? or can they be made closer to in parallel?

2024-06-12 15:57 UTC, bumblefudge commented
i would _assume_ parallel but what do i know about defi. my intuition is that either way, it should be a SHOULD for now and future EIPs would extend the capability definition (or propose an alternative) to be more explicit or opinionated unless people working on such use cases or mechanisms want to speak up and argue one way or the other?

2024-06-19 15:13 UTC, pedrouid commented
Hey @lukasrosario that's a great question but I think it applies for both single-chain and multi-chain Atomic Batching

What is the intended behavior for ordering even in a single-chain scenario? Should the Wallet respect the order of the items in the array? Ordering can be lost depending on the serialization and deserialization process involved

I think the Atomic Batching needs to have clearer expectations even without the changes included in this PR

2024-06-20 10:29 UTC, drortirosh commented
i'm not sure how can you provide such behavior: there is no way to guarantee cross-chain atomic batch, so it is "Best effort" at best.

2024-08-08 13:24 UTC, pedrouid commented
This can be closed in favor of the already merged #8771

2025-01-20 15:27 UTC, closed without merging