Add EIP: Increase Blob Base Fee
ethereum/EIPs pull request #8849
Opened 2024-09-02 16:10 UTC by MaxResnick

**ATTENTION: ERC-RELATED PULL REQUESTS NOW OCCUR IN [ETHEREUM/ERCS](https://github.com/ethereum/ercs)**

--

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

2024-09-03 04:37 UTC, abcoathup commented on EIPS/eip-draft_increase_blob_base_fee.md
> +eip: <to be assigned>
```suggestion
eip: 7762
```
Assigning next sequential EIP/ERC/RIP number.

Please also update the filename.

2024-09-03 04:38 UTC, abcoathup commented on EIPS/eip-draft_increase_blob_base_fee.md
> +discussions-to: <URL>
Please create a discussions topic in Eth Magicians using the template in the EIPs category:
https://ethereum-magicians.org/c/eips/5

2024-09-03 15:55 UTC, Magken91 approved these changes

2024-09-03 20:51 UTC, Allzz77123 approved these changes

2024-09-03 20:52 UTC, Allzz77123 approved these changes

2024-09-04 01:48 UTC, abcoathup commented on EIPS/eip-7762.md
> +eip: <7762>
```suggestion
eip: 7762
```

2024-09-04 01:49 UTC, abcoathup commented on EIPS/eip-7762.md
> +discussions-to: <https://ethereum-magicians.org/t/eip-7762-increase-min-base-fee-per-blob-gas/20949>
```suggestion
discussions-to: https://ethereum-magicians.org/t/eip-7762-increase-min-base-fee-per-blob-gas/20949
```

2024-09-06 03:16 UTC, jamesavechives approved these changes

2024-09-06 07:59 UTC, lightclient commented on EIPS/eip-7762.md
> +discussions-to: <https://ethereum-magicians.org/t/eip-7762-increase-min-base-fee-per-blob-gas/20949>
same here

2024-09-06 08:00 UTC, lightclient commented on EIPS/eip-7762.md
> +## Rationale
```suggestion
## Rationale

```

2024-09-06 08:00 UTC, lightclient commented on EIPS/eip-7762.md
> +<div style="page-break-after: always;"></div>
inline html is not allowed. please remove

2024-09-06 08:01 UTC, lightclient commented on EIPS/eip-7762.md
> +author: <Max Resnick (@MaxResnick)>
```suggestion
author: Max Resnick (@MaxResnick)
```

2024-09-06 08:02 UTC, lightclient commented on EIPS/eip-7762.md
> +- Rollups that use blobs as a data availability layer will need to update their posting strategies.
```suggestion
Rollups that use blobs as a data availability layer will need to update their posting strategies. 
```

2024-09-06 08:02 UTC, lightclient commented
If you would like this EIP to be merged, please undraft the PR.

2024-09-06 09:24 UTC, XstRUhayabusa requested changes
Dankeschön

2024-09-07 03:38 UTC, JanKortes212 commented on EIPS/eip-7762.md
> +author: <Max Resnick (@MaxResnick)>
ok

2024-09-09 20:09 UTC, lightclient commented
@MaxResnick can you please fix the CI issues so we can merge this EIP.

2024-09-11 20:51 UTC, MaxResnick commented
@lightclient should be good to go

2024-09-19 02:44 UTC, macfarla commented on EIPS/eip-7762.md
> +Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).
```suggestion
Copyright and related rights waived via [CC0](../LICENSE.md).
```

2024-09-19 02:49 UTC, macfarla commented on base_fee_225.png
the images are added twice in separate locations, perhaps unintentional?

2024-09-25 14:05 UTC, g11tech commented
CI still not passing

2024-09-25 17:06 UTC, MaxResnick commented
> CI still not passing

Passing now

2024-09-25 17:34 UTC, g11tech approved these changes

2024-09-25 17:35 UTC, merged