Update EIP-658: fix grammar
ethereum/EIPs pull request #8923
Opened 2024-10-02 14:43 UTC by RenanSouza2

In this PR one grammar mistake is fixed

2024-10-16 14:15 UTC, SamWilsn requested changes
Are we sure this isn't ["if and only if"](https://en.wikipedia.org/wiki/If_and_only_if)?

2025-05-06 12:59 UTC, g11tech approved these changes
might require force merge @SamWilsn

2025-05-08 00:18 UTC, RenanSouza2 commented
> Are we sure this isn't ["if and only if"](https://en.wikipedia.org/wiki/If_and_only_if)?

I agree with you that "if and only if" is better but it's not really my place to approve the changes

2025-05-27 16:28 UTC, SamWilsn commented
> I agree with you that "if and only if" is better but it's not really my place to approve the changes

I mean more that "iff" is a commonly accepted shorthand for "if and only if", so getting rid of the "f" would change the meaning.

2025-05-28 00:38 UTC, lightclient commented
Agree with Sam. Will err on side of caution and simply close this PR.

2025-05-28 00:38 UTC, closed without merging